apiVersion: solarSystem/v1
kind: solarSystems
name: Unukalhai
description: A solar system named Unukalhai
position:
  x: 32089561.621863835
  'y': -4355787.622638215
  z: -21590148.303906485
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Unukalhai
stars:
  - name: Unukalhai A
    description: ''
    tags: []
    radius: 12.19
    temperature: 4687
    solarMass: 1.61
    age: 1294815635764
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 67
      semiMajorAxis: 146.28
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Unukalhai
  - name: Unukalhai B
    description: ''
    tags: []
    radius: 12.19
    temperature: 4687
    solarMass: 1.61
    age: 1294815635764
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 247
      semiMajorAxis: 146.28
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Unukalhai
planets:
  - name: Unukalhai 1
    description: ''
    tags: []
    isPlanet:
      radius: 281
      age: 76800225
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
      terranMass: 0.008672435489656703
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 205
    satellite:
      semiMajorAxis: 514096891
      eccentricity: 0.01
      inclination: 0.58
      orbitalArc: 284
      axialTilt: 6.32
      parentId: Unukalhai
      showOrbit: true
    satellites: []
  - name: Unukalhai 2
    description: ''
    tags: []
    isPlanet:
      radius: 6662
      age: 8479962069
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
      terranMass: 0.00813157367708443
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      classification: L
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
    population: 48472
    temperature: 225
    satellite:
      semiMajorAxis: 845775363
      eccentricity: 0
      inclination: 1.24
      orbitalArc: 333
      axialTilt: 13.34
      parentId: Unukalhai
      showOrbit: true
    satellites:
      - name: Unukalhai 2a
        description: ''
        tags: []
        isPlanet:
          radius: 916.7359122999562
          age: 725126691
          ringMapAsset: null
          terranMass: 0.9000001479167267
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          classification: C
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 41
        satellite:
          semiMajorAxis: 201610.65817729998
          eccentricity: 0.01
          inclination: 1.79
          orbitalArc: 336
          axialTilt: 7.89
          parentId: Unukalhai 2
          showOrbit: true
        satellites: []
      - name: Unukalhai 2b
        description: ''
        tags: []
        isPlanet:
          radius: 1476.3532758083784
          age: 3410203035
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 156273
        temperature: 255
        satellite:
          semiMajorAxis: 420760.68360538787
          eccentricity: 0.01
          inclination: 1.03
          orbitalArc: 26
          axialTilt: 17.51
          parentId: Unukalhai 2
          showOrbit: true
        satellites: []
commSatellite: null
assets: {}
