apiVersion: solarSystem/v1
kind: solarSystems
name: Tabit
description: A solar system named Tabit
position:
  x: -13102348.533921417
  'y': -1677782.8704102528
  z: 4141202.036365892
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tabit
stars:
  - name: Tabit A
    description: ''
    tags: []
    solarMass: 1.288
    age: 23727728972415
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.317
    temperature: 6518
    satellite:
      axialTilt: 0
      semiMajorAxis: 15.803999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 233
      showOrbit: false
      parentId: Tabit
  - name: Tabit B
    description: ''
    tags: []
    solarMass: 1.288
    age: 23727728972415
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.317
    temperature: 6518
    satellite:
      axialTilt: 0
      semiMajorAxis: 15.803999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 413
      showOrbit: false
      parentId: Tabit
planets:
  - name: Tabit 1
    description: ''
    tags: []
    satellite:
      axialTilt: 15.2
      semiMajorAxis: 115974072.66666794
      eccentricity: 0
      inclination: 0.65
      orbitalArc: 105
      showOrbit: true
      parentId: Tabit
    isPlanet:
      age: 7351847735
      classification: O
      radius: 5584
      terranMass: 0.006945389255286517
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 125430502
    temperature: 303
    satellites: []
  - name: Tabit 2
    description: ''
    tags: []
    satellite:
      axialTilt: 22.88
      semiMajorAxis: 211710329.444458
      eccentricity: 0.01
      inclination: 0.87
      orbitalArc: 315
      showOrbit: true
      parentId: Tabit
    isPlanet:
      age: 632410479
      classification: D
      radius: 60
      terranMass: 0.0003796400434474173
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 267
    satellites: []
  - name: Tabit 3
    description: ''
    tags: []
    satellite:
      axialTilt: 3.11
      semiMajorAxis: 289525575.92618763
      eccentricity: 0.02
      inclination: 1.82
      orbitalArc: 222
      showOrbit: true
      parentId: Tabit
    isPlanet:
      age: 52211033
      classification: C
      radius: 4243
      terranMass: 0.008048429450057765
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 55
    satellites:
      - name: Tabit 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 1.94
          semiMajorAxis: 180667.2467580475
          eccentricity: 0.01
          inclination: 1.93
          orbitalArc: 159
          showOrbit: true
          parentId: Tabit 3
        isPlanet:
          age: 161673104
          classification: C
          radius: 652.2283276463809
          terranMass: 1.800000002214686
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 42
  - name: Tabit 4
    description: ''
    tags: []
    satellite:
      axialTilt: 30.95
      semiMajorAxis: 1693276338.9507918
      eccentricity: 0.01
      inclination: 0.78
      orbitalArc: 326
      showOrbit: true
      parentId: Tabit
    isPlanet:
      age: 5263303417
      classification: O
      radius: 6206
      terranMass: 0.0026035560947152677
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 668867709
    temperature: 300
    satellites:
      - name: Tabit 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 17.87
          semiMajorAxis: 167080.42188342713
          eccentricity: 0.01
          inclination: 1.4
          orbitalArc: 195
          showOrbit: true
          parentId: Tabit 4
        isPlanet:
          age: 4390721731
          classification: P
          radius: 516.6582701652679
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 106790
        temperature: 261
      - name: Tabit 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 14.64
          semiMajorAxis: 416586.481769595
          eccentricity: 0.01
          inclination: 0.73
          orbitalArc: 31
          showOrbit: true
          parentId: Tabit 4
        isPlanet:
          age: 391387399
          classification: D
          radius: 1243.5417366256568
          terranMass: 1.3399998989913342
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 278
  - name: Tabit 5
    description: ''
    tags: []
    satellite:
      axialTilt: 22.43
      semiMajorAxis: 3376407469
      eccentricity: 0.01
      inclination: 0.63
      orbitalArc: 341
      showOrbit: true
      parentId: Tabit
    isPlanet:
      age: 881298514
      classification: C
      radius: 2785
      terranMass: 0.0028169363953156187
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 36
    satellites:
      - name: Tabit 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 29.8
          semiMajorAxis: 59850.72854186662
          eccentricity: 0
          inclination: 0.67
          orbitalArc: 96
          showOrbit: true
          parentId: Tabit 5
        isPlanet:
          age: 283690119
          classification: D
          radius: 330.5999566022889
          terranMass: 0.4199999471661815
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 198
      - name: Tabit 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 28.53
          semiMajorAxis: 112997.72703739449
          eccentricity: 0.01
          inclination: 0.01
          orbitalArc: 20
          showOrbit: true
          parentId: Tabit 5
        isPlanet:
          age: 1587422631
          classification: A
          radius: 334.3128018857825
          terranMass: 0.200000214162991
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAcid.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1441
commSatellite: null
assets: {}
