apiVersion: solarSystem/v1
kind: solarSystems
name: Alzirr
description: A solar system named Alzirr
position:
  x: -29509455.35097081
  'y': -6890275.7164122425
  z: -5908543.201059336
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alzirr
stars:
  - name: Alzirr A
    description: ''
    tags: []
    solarMass: 1.706
    age: 7598182244984
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.71
    temperature: 6480
    satellite:
      axialTilt: 0
      semiMajorAxis: 32.519999999999996
      eccentricity: 0
      inclination: 0
      orbitalArc: 323
      showOrbit: false
      parentId: Alzirr
  - name: Alzirr B
    description: ''
    tags: []
    solarMass: 1.706
    age: 7598182244984
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.71
    temperature: 6480
    satellite:
      axialTilt: 0
      semiMajorAxis: 32.519999999999996
      eccentricity: 0
      inclination: 0
      orbitalArc: 503
      showOrbit: false
      parentId: Alzirr
planets:
  - name: Alzirr 1
    description: ''
    tags: []
    satellite:
      axialTilt: 6.59
      semiMajorAxis: 456784488
      eccentricity: 0.01
      inclination: 1.66
      orbitalArc: 19
      showOrbit: true
      parentId: Alzirr
    isPlanet:
      age: 360809438
      classification: C
      radius: 3765
      terranMass: 0.005915087810373122
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 47
    satellites:
      - name: Alzirr 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 7.71
          semiMajorAxis: 227618.46195776542
          eccentricity: 0.01
          inclination: 0.58
          orbitalArc: 73
          showOrbit: true
          parentId: Alzirr 1
        isPlanet:
          age: 646354172
          classification: D
          radius: 836.8325807270787
          terranMass: 1.0899998838951357
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 177
  - name: Alzirr 2
    description: ''
    tags: []
    satellite:
      axialTilt: 7.76
      semiMajorAxis: 972367620
      eccentricity: 0.01
      inclination: 1.7
      orbitalArc: 317
      showOrbit: true
      parentId: Alzirr
    isPlanet:
      age: 608738496
      classification: D
      radius: 177
      terranMass: 0.02208788119251177
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 337
    satellites: []
commSatellite: null
assets: {}
