apiVersion: solarSystem/v1
kind: solarSystems
name: Polaris Australis
description: A solar system named Polaris Australis
position:
  x: 1828928.767701211
  'y': 147770249.19861674
  z: 1974729.044449066
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Polaris Australis
stars:
  - name: Polaris Australis A
    description: ''
    tags: []
    solarMass: 1.59
    age: 1566810359368
    spectralType: F
    hue: 60
    isWhite: false
    radius: 4.4
    temperature: 7415
    satellite:
      axialTilt: 0
      semiMajorAxis: 52.800000000000004
      eccentricity: 0
      inclination: 0
      orbitalArc: 208
      showOrbit: false
      parentId: Polaris Australis
  - name: Polaris Australis B
    description: ''
    tags: []
    solarMass: 1.59
    age: 1566810359368
    spectralType: F
    hue: 60
    isWhite: false
    radius: 4.4
    temperature: 7415
    satellite:
      axialTilt: 0
      semiMajorAxis: 52.800000000000004
      eccentricity: 0
      inclination: 0
      orbitalArc: 388
      showOrbit: false
      parentId: Polaris Australis
planets:
  - name: Polaris Australis 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.25
      semiMajorAxis: 694200319.3333324
      eccentricity: 0.01
      inclination: 1.01
      orbitalArc: 78
      showOrbit: true
      parentId: Polaris Australis
    isPlanet:
      age: 911466810
      classification: C
      radius: 4675
      terranMass: 0.013488487858901204
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 48
    satellites:
      - name: Polaris Australis 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 1.35
          semiMajorAxis: 105704.55584786432
          eccentricity: 0.01
          inclination: 1.37
          orbitalArc: 202
          showOrbit: true
          parentId: Polaris Australis 1
        isPlanet:
          age: 7117037165
          classification: P
          radius: 241.904390297284
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 116456
        temperature: 256
      - name: Polaris Australis 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 25.68
          semiMajorAxis: 161038.52282345056
          eccentricity: 0.01
          inclination: 0.48
          orbitalArc: 87
          showOrbit: true
          parentId: Polaris Australis 1
        isPlanet:
          age: 9773597641
          classification: L
          radius: 407.69246284417864
          terranMass: 0.7000001584630592
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 32603
        temperature: 227
  - name: Polaris Australis 2
    description: ''
    tags: []
    satellite:
      axialTilt: 34.8
      semiMajorAxis: 1028872191.555553
      eccentricity: 0.02
      inclination: 1.08
      orbitalArc: 97
      showOrbit: true
      parentId: Polaris Australis
    isPlanet:
      age: 309436255
      classification: C
      radius: 3254
      terranMass: 0.001278556744047059
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 43
    satellites:
      - name: Polaris Australis 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.77
          semiMajorAxis: 217817.66343733124
          eccentricity: 0.02
          inclination: 0.85
          orbitalArc: 77
          showOrbit: true
          parentId: Polaris Australis 2
        isPlanet:
          age: 616346368
          classification: C
          radius: 803.7552156359086
          terranMass: 0.5000001707404381
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 50
  - name: Polaris Australis 3
    description: ''
    tags: []
    satellite:
      axialTilt: 16.49
      semiMajorAxis: 1230664439
      eccentricity: 0.01
      inclination: 1.41
      orbitalArc: 188
      showOrbit: true
      parentId: Polaris Australis
    isPlanet:
      age: 604299467
      classification: E
      radius: 7043
      terranMass: 0.004431922024720284
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 1356
    satellites: []
commSatellite: null
assets: {}
