apiVersion: solarSystem/v1
kind: solarSystems
name: Furud
description: A solar system named Furud
position:
  x: -164136870.21826398
  'y': 95381062.93805969
  z: -14586167.759527322
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Furud
stars:
  - name: Furud A
    description: ''
    tags: []
    solarMass: 7.7
    age: 110994517054
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.72
    temperature: 18700
    satellite:
      axialTilt: 0
      semiMajorAxis: 68.64
      eccentricity: 0
      inclination: 0
      orbitalArc: 242
      showOrbit: false
      parentId: Furud
  - name: Furud B
    description: ''
    tags: []
    solarMass: 7.7
    age: 110994517054
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.72
    temperature: 18700
    satellite:
      axialTilt: 0
      semiMajorAxis: 68.64
      eccentricity: 0
      inclination: 0
      orbitalArc: 422
      showOrbit: false
      parentId: Furud
planets:
  - name: Furud 1
    description: ''
    tags: []
    satellite:
      axialTilt: 23.76
      semiMajorAxis: 1576941053.9999995
      eccentricity: 0.01
      inclination: 1.45
      orbitalArc: 86
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 703451378
      classification: C
      radius: 2742
      terranMass: 0.010419163153907108
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 55
    satellites:
      - name: Furud 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.78
          semiMajorAxis: 39198.921074926926
          eccentricity: 0.02
          inclination: 0.55
          orbitalArc: 69
          showOrbit: true
          parentId: Furud 1
        isPlanet:
          age: 377711720
          classification: D
          radius: 285.3240611256157
          terranMass: 0.3899996227678788
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 209
      - name: Furud 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 1.7
          semiMajorAxis: 175178.95232447822
          eccentricity: 0.02
          inclination: 1.22
          orbitalArc: 81
          showOrbit: true
          parentId: Furud 1
        isPlanet:
          age: 4983376573
          classification: K
          radius: 295.80341922773596
          terranMass: 1.10000009650315
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 33188
        temperature: 137
      - name: Furud 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 33.36
          semiMajorAxis: 281570.55009965063
          eccentricity: 0
          inclination: 1.08
          orbitalArc: 85
          showOrbit: true
          parentId: Furud 1
        isPlanet:
          age: 457878018
          classification: D
          radius: 668.8136581939445
          terranMass: 0.23999992921843094
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 221
  - name: Furud 2
    description: ''
    tags: []
    satellite:
      axialTilt: 30.72
      semiMajorAxis: 2904873251.999999
      eccentricity: 0.01
      inclination: 0.26
      orbitalArc: 38
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 9083744091
      classification: J
      radius: 66951
      terranMass: 0.8097337421401716
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 333
    satellites:
      - name: Furud 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 0.39
          semiMajorAxis: 1408833.6129353442
          eccentricity: 0.02
          inclination: 1.69
          orbitalArc: 117
          showOrbit: true
          parentId: Furud 2
        isPlanet:
          age: 1856670879
          classification: E
          radius: 6356.081821303776
          terranMass: 1.3000000690081563
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 898
      - name: Furud 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 22.72
          semiMajorAxis: 3393579.103917358
          eccentricity: 0.02
          inclination: 1.17
          orbitalArc: 345
          showOrbit: true
          parentId: Furud 2
        isPlanet:
          age: 9728634994
          classification: P
          radius: 12476.393764402052
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 159878
        temperature: 255
  - name: Furud 3
    description: ''
    tags: []
    satellite:
      axialTilt: 28.51
      semiMajorAxis: 3298737792.333327
      eccentricity: 0.01
      inclination: 1.66
      orbitalArc: 6
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 169630633
      classification: D
      radius: 74
      terranMass: 0.005100140221475222
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 246
    satellites: []
  - name: Furud 4
    description: ''
    tags: []
    satellite:
      axialTilt: 2.02
      semiMajorAxis: 3667617577.66663
      eccentricity: 0.01
      inclination: 0.51
      orbitalArc: 91
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 219860226
      classification: C
      radius: 4941
      terranMass: 0.031465011941812344
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 39
    satellites: []
  - name: Furud 5
    description: ''
    tags: []
    satellite:
      axialTilt: 30.74
      semiMajorAxis: 3987631784.6666303
      eccentricity: 0.01
      inclination: 1.22
      orbitalArc: 315
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 178424168
      classification: D
      radius: 233
      terranMass: 0.0006860395135574555
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 288
    satellites: []
  - name: Furud 6
    description: ''
    tags: []
    satellite:
      axialTilt: 0.65
      semiMajorAxis: 4303443760.999774
      eccentricity: 0.01
      inclination: 1
      orbitalArc: 264
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 5316422196
      classification: L
      radius: 4677
      terranMass: 0.008260995670060155
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 9236
    temperature: 215
    satellites:
      - name: Furud 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.12
          semiMajorAxis: 228983.5127917851
          eccentricity: 0.02
          inclination: 0.32
          orbitalArc: 180
          showOrbit: true
          parentId: Furud 6
        isPlanet:
          age: 7666823516
          classification: P
          radius: 713.3442766099224
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 28913
        temperature: 268
  - name: Furud 7
    description: ''
    tags: []
    satellite:
      axialTilt: 0.99
      semiMajorAxis: 5082521514.999327
      eccentricity: 0.02
      inclination: 0.02
      orbitalArc: 174
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 927899173
      classification: D
      radius: 333
      terranMass: 0.0063584051808164704
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 214
    satellites: []
  - name: Furud 8
    description: ''
    tags: []
    satellite:
      axialTilt: 3.28
      semiMajorAxis: 5714815705
      eccentricity: 0.01
      inclination: 0.79
      orbitalArc: 291
      showOrbit: true
      parentId: Furud
    isPlanet:
      age: 822277161
      classification: D
      radius: 185
      terranMass: 0.009348028118624792
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 229
    satellites: []
commSatellite: null
assets: {}
