apiVersion: solarSystem/v1
kind: solarSystems
name: Phecda
description: A solar system named Phecda
position:
  x: -697366.6791400594
  'y': -35264948.1421968
  z: -25900260.80369423
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Phecda
stars:
  - name: Phecda A
    description: ''
    tags: []
    solarMass: 2.412
    age: 5844627133257
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.385
    temperature: 6751
    satellite:
      axialTilt: 0
      semiMajorAxis: 40.62
      eccentricity: 0
      inclination: 0
      orbitalArc: 190
      showOrbit: false
      parentId: Phecda
  - name: Phecda B
    description: ''
    tags: []
    solarMass: 2.412
    age: 5844627133257
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.385
    temperature: 6751
    satellite:
      axialTilt: 0
      semiMajorAxis: 40.62
      eccentricity: 0
      inclination: 0
      orbitalArc: 370
      showOrbit: false
      parentId: Phecda
planets:
  - name: Phecda 1
    description: ''
    tags: []
    satellite:
      axialTilt: 2.78
      semiMajorAxis: 336016709.3333342
      eccentricity: 0
      inclination: 1.57
      orbitalArc: 294
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 6976258756
      classification: H
      radius: 6613
      terranMass: 0.0008473848706759024
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 518
    satellites: []
  - name: Phecda 2
    description: ''
    tags: []
    satellite:
      axialTilt: 13.53
      semiMajorAxis: 583718490.0000058
      eccentricity: 0.02
      inclination: 1.19
      orbitalArc: 67
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 1137131840
      classification: E
      radius: 5415
      terranMass: 0.009830452016354182
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 1227
    satellites:
      - name: Phecda 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 6.08
          semiMajorAxis: 173646.34380837102
          eccentricity: 0.01
          inclination: 1.83
          orbitalArc: 115
          showOrbit: true
          parentId: Phecda 2
        isPlanet:
          age: 182841282
          classification: D
          radius: 482.4922285394842
          terranMass: 0.40999973337053874
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 189
      - name: Phecda 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 21.19
          semiMajorAxis: 466971.4285854458
          eccentricity: 0.01
          inclination: 1.62
          orbitalArc: 188
          showOrbit: true
          parentId: Phecda 2
        isPlanet:
          age: 535548937
          classification: D
          radius: 1078.4559551626924
          terranMass: 1.269999759492767
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 314
  - name: Phecda 3
    description: ''
    tags: []
    satellite:
      axialTilt: 7.31
      semiMajorAxis: 700774084.0000728
      eccentricity: 0.02
      inclination: 0.09
      orbitalArc: 6
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 88235798
      classification: D
      radius: 345
      terranMass: 0.002163098855807304
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 207
    satellites: []
  - name: Phecda 4
    description: ''
    tags: []
    satellite:
      axialTilt: 26.75
      semiMajorAxis: 776582607.6685421
      eccentricity: 0.01
      inclination: 1.67
      orbitalArc: 73
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 6086944178
      classification: K
      radius: 3679
      terranMass: 0.01047729853963599
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 12747
    temperature: 140
    satellites:
      - name: Phecda 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 10.96
          semiMajorAxis: 354745.58196150284
          eccentricity: 0
          inclination: 1.39
          orbitalArc: 189
          showOrbit: true
          parentId: Phecda 4
        isPlanet:
          age: 3191219891
          classification: G
          radius: 836.6641083997708
          terranMass: 0.5
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 494
  - name: Phecda 5
    description: ''
    tags: []
    satellite:
      axialTilt: 10.5
      semiMajorAxis: 925819811.2359757
      eccentricity: 0.02
      inclination: 1.32
      orbitalArc: 235
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 4021418379
      classification: L
      radius: 4194
      terranMass: 0.022570236271055005
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 14133
    temperature: 268
    satellites:
      - name: Phecda 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 4.28
          semiMajorAxis: 172069.72467155918
          eccentricity: 0
          inclination: 0.96
          orbitalArc: 346
          showOrbit: true
          parentId: Phecda 5
        isPlanet:
          age: 9975705751
          classification: B
          radius: 522.7020541694952
          terranMass: 0.9000006920367646
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 607
      - name: Phecda 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 39.87
          semiMajorAxis: 314547.27176969865
          eccentricity: 0.01
          inclination: 0.55
          orbitalArc: 41
          showOrbit: true
          parentId: Phecda 5
        isPlanet:
          age: 366209712
          classification: D
          radius: 757.3729448075112
          terranMass: 1.0899997059198194
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 339
      - name: Phecda 5c
        description: ''
        tags: []
        satellite:
          axialTilt: 18.98
          semiMajorAxis: 409450.0847450958
          eccentricity: 0.02
          inclination: 0.22
          orbitalArc: 300
          showOrbit: true
          parentId: Phecda 5
        isPlanet:
          age: 453099628
          classification: D
          radius: 847.7227427434696
          terranMass: 0.5299998564124453
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 153
  - name: Phecda 6
    description: ''
    tags: []
    satellite:
      axialTilt: 1.15
      semiMajorAxis: 1942271499.2359753
      eccentricity: 0.01
      inclination: 0.36
      orbitalArc: 220
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 4108235998
      classification: J
      radius: 28962
      terranMass: 1.3880558806641623
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 247
    satellites: []
  - name: Phecda 7
    description: ''
    tags: []
    satellite:
      axialTilt: 31.89
      semiMajorAxis: 3136140670
      eccentricity: 0.01
      inclination: 0.42
      orbitalArc: 229
      showOrbit: true
      parentId: Phecda
    isPlanet:
      age: 908787490
      classification: D
      radius: 148
      terranMass: 0.0038035218119773697
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 359
    satellites: []
commSatellite: null
assets: {}
