apiVersion: solarSystem/v1
kind: solarSystems
name: Salm
description: A solar system named Salm
position:
  x: 13330091.276031442
  'y': -34303086.25309565
  z: 76847820.9096117
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Salm
stars:
  - name: Salm A
    description: ''
    tags: []
    radius: 2.8
    temperature: 7709
    solarMass: 2.14
    age: 4457330246349
    spectralType: A
    hue: 180
    isWhite: true
    satellite:
      orbitalArc: 306
      semiMajorAxis: 33.599999999999994
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Salm
  - name: Salm B
    description: ''
    tags: []
    radius: 2.8
    temperature: 7709
    solarMass: 2.14
    age: 4457330246349
    spectralType: A
    hue: 180
    isWhite: true
    satellite:
      orbitalArc: 486
      semiMajorAxis: 33.599999999999994
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Salm
planets:
  - name: Salm 1
    description: ''
    tags: []
    isPlanet:
      radius: 2784
      age: 7250754612
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
      terranMass: 0.0044856269096499625
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      classification: K
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
    population: 26482
    temperature: 123
    satellite:
      semiMajorAxis: 1758874711.333333
      eccentricity: 0.01
      inclination: 1.83
      orbitalArc: 188
      axialTilt: 36.55
      parentId: Salm
      showOrbit: true
    satellites:
      - name: Salm 1a
        description: ''
        tags: []
        isPlanet:
          radius: 248.13897711563368
          age: 23610991
          ringMapAsset: null
          terranMass: 0.8999997013134944
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          classification: D
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 288
        satellite:
          semiMajorAxis: 107940.45504530065
          eccentricity: 0.02
          inclination: 1.09
          orbitalArc: 355
          axialTilt: 22.6
          parentId: Salm 1
          showOrbit: true
        satellites: []
  - name: Salm 2
    description: ''
    tags: []
    isPlanet:
      radius: 58917
      age: 6803787760
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: null
      terranMass: 0.7329038712610265
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 138
    satellite:
      semiMajorAxis: 2908879913
      eccentricity: 0.02
      inclination: 0.77
      orbitalArc: 311
      axialTilt: 37.33
      parentId: Salm
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
