apiVersion: solarSystem/v1
kind: solarSystems
name: Algieba
description: A solar system named Algieba
position:
  x: -27187983.576906018
  'y': -23207715.925364394
  z: -58286608.63002304
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Algieba
stars:
  - name: Algieba A
    description: ''
    tags: []
    solarMass: 1.66
    age: 298687546944
    spectralType: K
    hue: 30
    isWhite: false
    radius: 28.5
    temperature: 4457
    satellite:
      axialTilt: 0
      semiMajorAxis: 342
      eccentricity: 0
      inclination: 0
      orbitalArc: 123
      showOrbit: false
      parentId: Algieba
  - name: Algieba B
    description: ''
    tags: []
    solarMass: 1.66
    age: 298687546944
    spectralType: K
    hue: 30
    isWhite: false
    radius: 28.5
    temperature: 4457
    satellite:
      axialTilt: 0
      semiMajorAxis: 342
      eccentricity: 0
      inclination: 0
      orbitalArc: 303
      showOrbit: false
      parentId: Algieba
planets:
  - name: Algieba 1
    description: ''
    tags: []
    satellite:
      axialTilt: 38.33
      semiMajorAxis: 1452147821.333333
      eccentricity: 0.01
      inclination: 1.52
      orbitalArc: 208
      showOrbit: true
      parentId: Algieba
    isPlanet:
      age: 82115786
      classification: D
      radius: 402
      terranMass: 0.02326487991490796
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 203
    satellites: []
  - name: Algieba 2
    description: ''
    tags: []
    satellite:
      axialTilt: 35.53
      semiMajorAxis: 2584954773.5555553
      eccentricity: 0.01
      inclination: 0.33
      orbitalArc: 206
      showOrbit: true
      parentId: Algieba
    isPlanet:
      age: 9459939322
      classification: K
      radius: 3217
      terranMass: 0.008548986338853738
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 1886
    temperature: 303
    satellites:
      - name: Algieba 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 5.85
          semiMajorAxis: 214745.89681105304
          eccentricity: 0.02
          inclination: 1.93
          orbitalArc: 253
          showOrbit: true
          parentId: Algieba 2
        isPlanet:
          age: 952721275
          classification: D
          radius: 613.5597051744372
          terranMass: 0.7899996709437069
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 246
  - name: Algieba 3
    description: ''
    tags: []
    satellite:
      axialTilt: 11.52
      semiMajorAxis: 3978354306
      eccentricity: 0.02
      inclination: 1.11
      orbitalArc: 197
      showOrbit: true
      parentId: Algieba
    isPlanet:
      age: 6664798101
      classification: J
      radius: 41160
      terranMass: 1.5084172097694635
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: null
    population: 0
    temperature: 316
    satellites:
      - name: Algieba 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 11.82
          semiMajorAxis: 2309326.3676856356
          eccentricity: 0
          inclination: 1.07
          orbitalArc: 193
          showOrbit: true
          parentId: Algieba 3
        isPlanet:
          age: 8532453686
          classification: H
          radius: 7828.224975205544
          terranMass: 2.300000077729564
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 0
        temperature: 781
commSatellite: null
assets: {}
