apiVersion: solarSystem/v1
kind: solarSystems
name: Edasich
description: A solar system named Edasich
position:
  x: 21353270.789385095
  'y': -45518193.50720288
  z: -17148601.12888592
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Edasich
stars:
  - name: Edasich A
    description: ''
    tags: []
    solarMass: 1.56
    age: 1520764581291
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.99
    temperature: 4504
    satellite:
      axialTilt: 0
      semiMajorAxis: 143.88
      eccentricity: 0
      inclination: 0
      orbitalArc: 276
      showOrbit: false
      parentId: Edasich
  - name: Edasich B
    description: ''
    tags: []
    solarMass: 1.56
    age: 1520764581291
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.99
    temperature: 4504
    satellite:
      axialTilt: 0
      semiMajorAxis: 143.88
      eccentricity: 0
      inclination: 0
      orbitalArc: 456
      showOrbit: false
      parentId: Edasich
planets:
  - name: Edasich 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.32
      semiMajorAxis: 316756562
      eccentricity: 0
      inclination: 0.58
      orbitalArc: 174
      showOrbit: true
      parentId: Edasich
    isPlanet:
      age: 3770728378
      classification: B
      radius: 3046
      terranMass: 0.020580011644257715
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 121
    satellites: []
  - name: Edasich 2
    description: ''
    tags: []
    satellite:
      axialTilt: 7.57
      semiMajorAxis: 627399532
      eccentricity: 0.01
      inclination: 1.32
      orbitalArc: 290
      showOrbit: true
      parentId: Edasich
    isPlanet:
      age: 506444887
      classification: C
      radius: 2710
      terranMass: 0.012725870949096236
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 36
    satellites: []
  - name: Edasich 3
    description: ''
    tags: []
    satellite:
      axialTilt: 6.2
      semiMajorAxis: 1153009271
      eccentricity: 0.01
      inclination: 0.81
      orbitalArc: 6
      showOrbit: true
      parentId: Edasich
    isPlanet:
      age: 9904914298
      classification: K
      radius: 4264
      terranMass: 0.007607594820298792
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 27600
    temperature: 154
    satellites: []
commSatellite: null
assets: {}
