apiVersion: solarSystem/v1
kind: solarSystems
name: Aldhibah
description: A solar system named Aldhibah
position:
  x: 69609806.24551572
  'y': -158207650.19413406
  z: -15819240.081377847
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Aldhibah
stars:
  - name: 'Aldhibah '
    description: ''
    tags: []
    solarMass: 5.94
    age: 176607602608
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.19
    temperature: 15000
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 169
      showOrbit: false
      parentId: Aldhibah
planets:
  - name: Aldhibah 1
    description: ''
    tags: []
    satellite:
      axialTilt: 11.13
      semiMajorAxis: 2348452839.9999995
      eccentricity: 0.01
      inclination: 1.27
      orbitalArc: 106
      showOrbit: true
      parentId: Aldhibah
    isPlanet:
      age: 7382625331
      classification: J
      radius: 39722
      terranMass: 0.6860594852282804
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 159
    satellites: []
  - name: Aldhibah 2
    description: ''
    tags: []
    satellite:
      axialTilt: 22.91
      semiMajorAxis: 3386424564.999998
      eccentricity: 0.02
      inclination: 1.14
      orbitalArc: 240
      showOrbit: true
      parentId: Aldhibah
    isPlanet:
      age: 3616131313
      classification: J
      radius: 53278
      terranMass: 0.7337042269305569
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 207
    satellites: []
  - name: Aldhibah 3
    description: ''
    tags: []
    satellite:
      axialTilt: 25.67
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 1.09
      orbitalArc: 138
      showOrbit: true
      parentId: Aldhibah
    isPlanet:
      age: 5650691484
      classification: J
      radius: 39217
      terranMass: 1.820380682171178
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 156
    satellites:
      - name: Aldhibah 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.71
          semiMajorAxis: 2143843.3105023396
          eccentricity: 0.02
          inclination: 1.4
          orbitalArc: 238
          showOrbit: true
          parentId: Aldhibah 3
        isPlanet:
          age: 8839167472
          classification: H
          radius: 7852.905899275969
          terranMass: 1.1000001271866893
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 0
        temperature: 577
commSatellite: null
assets: {}
