apiVersion: solarSystem/v1
kind: solarSystems
name: Sadalsuud
description: A solar system named Sadalsuud
position:
  x: 170553372.8862769
  'y': 27573135.286967266
  z: 225427861.5125495
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sadalsuud
stars:
  - name: 'Sadalsuud '
    description: ''
    tags: []
    solarMass: 4.97
    age: 126411146397
    spectralType: G
    hue: 45
    isWhite: false
    radius: 47.88
    temperature: 5608
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 344
      showOrbit: false
      parentId: Sadalsuud
planets:
  - name: Sadalsuud 1
    description: ''
    tags: []
    satellite:
      axialTilt: 32.08
      semiMajorAxis: 4350131666
      eccentricity: 0.01
      inclination: 0.55
      orbitalArc: 64
      showOrbit: true
      parentId: Sadalsuud
    isPlanet:
      age: 560276375
      classification: D
      radius: 145
      terranMass: 0.00012613697730528263
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 400
    satellites: []
commSatellite: null
assets: {}
