apiVersion: solarSystem/v1
kind: solarSystems
name: Jishui
description: A solar system named Jishui
position:
  x: -65256532.044131815
  'y': -49558436.912106805
  z: -30140847.69895378
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Jishui
stars:
  - name: Jishui A
    description: ''
    tags: []
    solarMass: 2
    age: 4113979987914
    spectralType: F
    hue: 60
    isWhite: false
    radius: 4
    temperature: 6470
    satellite:
      axialTilt: 0
      semiMajorAxis: 48
      eccentricity: 0
      inclination: 0
      orbitalArc: 253
      showOrbit: false
      parentId: Jishui
  - name: Jishui B
    description: ''
    tags: []
    solarMass: 2
    age: 4113979987914
    spectralType: F
    hue: 60
    isWhite: false
    radius: 4
    temperature: 6470
    satellite:
      axialTilt: 0
      semiMajorAxis: 48
      eccentricity: 0
      inclination: 0
      orbitalArc: 433
      showOrbit: false
      parentId: Jishui
planets:
  - name: Jishui 1
    description: ''
    tags: []
    satellite:
      axialTilt: 0.53
      semiMajorAxis: 296007194.33333325
      eccentricity: 0.01
      inclination: 0.18
      orbitalArc: 16
      showOrbit: true
      parentId: Jishui
    isPlanet:
      age: 782940582
      classification: D
      radius: 335
      terranMass: 0.007858140537253968
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 348
    satellites: []
  - name: Jishui 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.51
      semiMajorAxis: 889768293.8888888
      eccentricity: 0
      inclination: 1.08
      orbitalArc: 232
      showOrbit: true
      parentId: Jishui
    isPlanet:
      age: 239289000
      classification: C
      radius: 2238
      terranMass: 0.021070876299981355
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 43
    satellites: []
  - name: Jishui 3
    description: ''
    tags: []
    satellite:
      axialTilt: 25.08
      semiMajorAxis: 2379605970.8888884
      eccentricity: 0
      inclination: 1.65
      orbitalArc: 293
      showOrbit: true
      parentId: Jishui
    isPlanet:
      age: 8805723827
      classification: J
      radius: 55889
      terranMass: 0.6062342439734456
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 290
    satellites: []
  - name: Jishui 4
    description: ''
    tags: []
    satellite:
      axialTilt: 38.43
      semiMajorAxis: 3968454217
      eccentricity: 0.01
      inclination: 0.51
      orbitalArc: 248
      showOrbit: true
      parentId: Jishui
    isPlanet:
      age: 245566388
      classification: D
      radius: 100
      terranMass: 0.001586940856211499
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 296
    satellites: []
commSatellite: null
assets: {}
