apiVersion: solarSystem/v1
kind: solarSystems
name: Zosma
description: A solar system named Zosma
position:
  x: -5682584.84416382
  'y': -10695141.72980067
  z: -27998547.911110613
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Zosma
stars:
  - name: Zosma A
    description: ''
    tags: []
    solarMass: 2.2
    age: 5849105368874
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.14
    temperature: 8296
    satellite:
      axialTilt: 0
      semiMajorAxis: 25.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 305
      showOrbit: false
      parentId: Zosma
  - name: Zosma B
    description: ''
    tags: []
    solarMass: 2.2
    age: 5849105368874
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.14
    temperature: 8296
    satellite:
      axialTilt: 0
      semiMajorAxis: 25.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 485
      showOrbit: false
      parentId: Zosma
planets:
  - name: Zosma 1
    description: ''
    tags: []
    satellite:
      axialTilt: 11.06
      semiMajorAxis: 2312910640
      eccentricity: 0.01
      inclination: 0.05
      orbitalArc: 34
      showOrbit: true
      parentId: Zosma
    isPlanet:
      age: 3329542847
      classification: J
      radius: 66464
      terranMass: 1.67703192258301
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 278
    satellites:
      - name: Zosma 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 16.93
          semiMajorAxis: 2229224.789819001
          eccentricity: 0.01
          inclination: 0.01
          orbitalArc: 68
          showOrbit: true
          parentId: Zosma 1
        isPlanet:
          age: 211563428
          classification: D
          radius: 5175.973227274411
          terranMass: 0.6399997376643645
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 348
      - name: Zosma 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 31.12
          semiMajorAxis: 3768182.1911182096
          eccentricity: 0.02
          inclination: 1.62
          orbitalArc: 81
          showOrbit: true
          parentId: Zosma 1
        isPlanet:
          age: 9438391511
          classification: H
          radius: 8993.274919136538
          terranMass: 0.9000000940423692
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 587
commSatellite: null
assets: {}
