apiVersion: solarSystem/v1
kind: solarSystems
name: Xuange
description: A solar system named Xuange
position:
  x: 20244288.38638465
  'y': -37511755.34448741
  z: -29905284.88922671
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Xuange
stars:
  - name: Xuange A
    description: ''
    tags: []
    radius: 1.7
    temperature: 8887
    solarMass: 1.66
    age: 5310786089666
    spectralType: A
    hue: 180
    isWhite: true
    satellite:
      orbitalArc: 38
      semiMajorAxis: 20.4
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Xuange
  - name: Xuange B
    description: ''
    tags: []
    radius: 1.7
    temperature: 8887
    solarMass: 1.66
    age: 5310786089666
    spectralType: A
    hue: 180
    isWhite: true
    satellite:
      orbitalArc: 218
      semiMajorAxis: 20.4
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Xuange
planets:
  - name: Xuange 1
    description: ''
    tags: []
    isPlanet:
      radius: 320
      age: 988019816
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
      terranMass: 0.0038302753365364022
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 257
    satellite:
      semiMajorAxis: 145808793
      eccentricity: 0.01
      inclination: 0.89
      orbitalArc: 231
      axialTilt: 29.84
      parentId: Xuange
      showOrbit: true
    satellites: []
  - name: Xuange 2
    description: ''
    tags: []
    isPlanet:
      radius: 6023
      age: 3396231362
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
      terranMass: 0.022627830051381102
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      classification: G
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
    population: 0
    temperature: 510
    satellite:
      semiMajorAxis: 420187663
      eccentricity: 0.01
      inclination: 1.78
      orbitalArc: 108
      axialTilt: 23.58
      parentId: Xuange
      showOrbit: true
    satellites: []
  - name: Xuange 3
    description: ''
    tags: []
    isPlanet:
      radius: 6231
      age: 1440728746
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.00035644418291047526
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
      classification: F
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 602
    satellite:
      semiMajorAxis: 673098545.6666662
      eccentricity: 0
      inclination: 1.11
      orbitalArc: 347
      axialTilt: 20.08
      parentId: Xuange
      showOrbit: true
    satellites:
      - name: Xuange 3a
        description: ''
        tags: []
        isPlanet:
          radius: 316.204647137121
          age: 2229731477
          ringMapAsset: null
          terranMass: 1.7000000834937694
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
          classification: F
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 861
        satellite:
          semiMajorAxis: 99413.203969406
          eccentricity: 0.01
          inclination: 1.69
          orbitalArc: 106
          axialTilt: 29.84
          parentId: Xuange 3
          showOrbit: true
        satellites: []
      - name: Xuange 3b
        description: ''
        tags: []
        isPlanet:
          radius: 485.9741590175136
          age: 728869751
          ringMapAsset: null
          terranMass: 1.0699997790876108
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: D
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 294
        satellite:
          semiMajorAxis: 217230.44908082858
          eccentricity: 0
          inclination: 1.3
          orbitalArc: 0
          axialTilt: 38.44
          parentId: Xuange 3
          showOrbit: true
        satellites: []
  - name: Xuange 4
    description: ''
    tags: []
    isPlanet:
      radius: 1202
      age: 368808796
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.017627818032900557
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      classification: C
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 54
    satellite:
      semiMajorAxis: 968098885.3333318
      eccentricity: 0.01
      inclination: 0.98
      orbitalArc: 314
      axialTilt: 0.51
      parentId: Xuange
      showOrbit: true
    satellites:
      - name: Xuange 4a
        description: ''
        tags: []
        isPlanet:
          radius: 158.66817093257987
          age: 332208960
          ringMapAsset: null
          terranMass: 1.28999962384661
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          classification: D
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 225
        satellite:
          semiMajorAxis: 29519.45808749446
          eccentricity: 0.02
          inclination: 1.41
          orbitalArc: 160
          axialTilt: 16.23
          parentId: Xuange 4
          showOrbit: true
        satellites: []
      - name: Xuange 4b
        description: ''
        tags: []
        isPlanet:
          radius: 157.7973714137211
          age: 5372165998
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 66614
        temperature: 255
        satellite:
          semiMajorAxis: 54832.42707674098
          eccentricity: 0.02
          inclination: 1.37
          orbitalArc: 91
          axialTilt: 24.41
          parentId: Xuange 4
          showOrbit: true
        satellites: []
      - name: Xuange 4c
        description: ''
        tags: []
        isPlanet:
          radius: 187.88172520612875
          age: 8194413214
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.1000001511509185
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          classification: K
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
        population: 41090
        temperature: 208
        satellite:
          semiMajorAxis: 78346.6794109557
          eccentricity: 0.01
          inclination: 1.44
          orbitalArc: 176
          axialTilt: 37.33
          parentId: Xuange 4
          showOrbit: true
        satellites: []
  - name: Xuange 5
    description: ''
    tags: []
    isPlanet:
      radius: 58312
      age: 7881049402
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.25848659400676527
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 193
    satellite:
      semiMajorAxis: 1233602034.9999905
      eccentricity: 0.02
      inclination: 1.08
      orbitalArc: 196
      axialTilt: 21.23
      parentId: Xuange
      showOrbit: true
    satellites: []
  - name: Xuange 6
    description: ''
    tags: []
    isPlanet:
      radius: 1922
      age: 741181916
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.004370821203773873
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      classification: C
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 40
    satellite:
      semiMajorAxis: 1359477561.3333206
      eccentricity: 0.01
      inclination: 1.6
      orbitalArc: 178
      axialTilt: 13.8
      parentId: Xuange
      showOrbit: true
    satellites:
      - name: Xuange 6a
        description: ''
        tags: []
        isPlanet:
          radius: 110.20735476908912
          age: 7917226137
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 99365
        temperature: 264
        satellite:
          semiMajorAxis: 82682.38394398082
          eccentricity: 0.02
          inclination: 0.48
          orbitalArc: 95
          axialTilt: 6.51
          parentId: Xuange 6
          showOrbit: true
        satellites: []
      - name: Xuange 6b
        description: ''
        tags: []
        isPlanet:
          radius: 477.7295110415271
          age: 52831346
          ringMapAsset: null
          terranMass: 0.300000101379187
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          classification: C
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 40
        satellite:
          semiMajorAxis: 161950.30424307767
          eccentricity: 0.02
          inclination: 0.34
          orbitalArc: 335
          axialTilt: 7.41
          parentId: Xuange 6
          showOrbit: true
        satellites: []
  - name: Xuange 7
    description: ''
    tags: []
    isPlanet:
      radius: 68631
      age: 2896415368
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.16408454669618153
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 198
    satellite:
      semiMajorAxis: 2031334123.3333206
      eccentricity: 0
      inclination: 0.2
      orbitalArc: 226
      axialTilt: 13.96
      parentId: Xuange
      showOrbit: true
    satellites:
      - name: Xuange 7a
        description: ''
        tags: []
        isPlanet:
          radius: 11555.353614746944
          age: 8332734834
          ringMapAsset: null
          terranMass: 0.10000015517563413
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
          classification: B
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 245
        satellite:
          semiMajorAxis: 4379479.019989092
          eccentricity: 0.01
          inclination: 0.29
          orbitalArc: 4
          axialTilt: 11.99
          parentId: Xuange 7
          showOrbit: true
        satellites: []
  - name: Xuange 8
    description: ''
    tags: []
    isPlanet:
      radius: 177
      age: 672116065
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
      terranMass: 0.006004295485765562
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 202
    satellite:
      semiMajorAxis: 2635723637.77776
      eccentricity: 0.01
      inclination: 1.45
      orbitalArc: 161
      axialTilt: 26.29
      parentId: Xuange
      showOrbit: true
    satellites: []
  - name: Xuange 9
    description: ''
    tags: []
    isPlanet:
      radius: 158
      age: 242987957
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
      terranMass: 0.0121292695920875
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 192
    satellite:
      semiMajorAxis: 3570589110
      eccentricity: 0.02
      inclination: 0.51
      orbitalArc: 212
      axialTilt: 13.64
      parentId: Xuange
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
