apiVersion: solarSystem/v1
kind: solarSystems
name: Xuange
description: A solar system named Xuange
position:
  x: 20244288.38638465
  'y': -37511755.34448741
  z: -29905284.88922671
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Xuange
stars:
  - name: Xuange A
    description: ''
    tags: []
    solarMass: 1.66
    age: 5310786089666
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.7
    temperature: 8887
    satellite:
      axialTilt: 0
      semiMajorAxis: 20.4
      eccentricity: 0
      inclination: 0
      orbitalArc: 38
      showOrbit: false
      parentId: Xuange
  - name: Xuange B
    description: ''
    tags: []
    solarMass: 1.66
    age: 5310786089666
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.7
    temperature: 8887
    satellite:
      axialTilt: 0
      semiMajorAxis: 20.4
      eccentricity: 0
      inclination: 0
      orbitalArc: 218
      showOrbit: false
      parentId: Xuange
planets:
  - name: Xuange 1
    description: ''
    tags: []
    satellite:
      axialTilt: 29.84
      semiMajorAxis: 145808793
      eccentricity: 0.01
      inclination: 0.89
      orbitalArc: 231
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 988019816
      classification: D
      radius: 320
      terranMass: 0.0038302753365364022
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 257
    satellites: []
  - name: Xuange 2
    description: ''
    tags: []
    satellite:
      axialTilt: 23.58
      semiMajorAxis: 420187663
      eccentricity: 0.01
      inclination: 1.78
      orbitalArc: 108
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 3396231362
      classification: G
      radius: 6023
      terranMass: 0.022627830051381102
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 510
    satellites: []
  - name: Xuange 3
    description: ''
    tags: []
    satellite:
      axialTilt: 20.08
      semiMajorAxis: 673098545.6666662
      eccentricity: 0
      inclination: 1.11
      orbitalArc: 347
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 1440728746
      classification: F
      radius: 6231
      terranMass: 0.00035644418291047526
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 602
    satellites:
      - name: Xuange 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 29.84
          semiMajorAxis: 99413.203969406
          eccentricity: 0.01
          inclination: 1.69
          orbitalArc: 106
          showOrbit: true
          parentId: Xuange 3
        isPlanet:
          age: 2229731477
          classification: F
          radius: 316.204647137121
          terranMass: 1.7000000834937694
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 861
      - name: Xuange 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 38.44
          semiMajorAxis: 217230.44908082858
          eccentricity: 0
          inclination: 1.3
          orbitalArc: 0
          showOrbit: true
          parentId: Xuange 3
        isPlanet:
          age: 728869751
          classification: D
          radius: 485.9741590175136
          terranMass: 1.0699997790876108
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 294
  - name: Xuange 4
    description: ''
    tags: []
    satellite:
      axialTilt: 0.51
      semiMajorAxis: 968098885.3333318
      eccentricity: 0.01
      inclination: 0.98
      orbitalArc: 314
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 368808796
      classification: C
      radius: 1202
      terranMass: 0.017627818032900557
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 54
    satellites:
      - name: Xuange 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 16.23
          semiMajorAxis: 29519.45808749446
          eccentricity: 0.02
          inclination: 1.41
          orbitalArc: 160
          showOrbit: true
          parentId: Xuange 4
        isPlanet:
          age: 332208960
          classification: D
          radius: 158.66817093257987
          terranMass: 1.28999962384661
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 225
      - name: Xuange 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 24.41
          semiMajorAxis: 54832.42707674098
          eccentricity: 0.02
          inclination: 1.37
          orbitalArc: 91
          showOrbit: true
          parentId: Xuange 4
        isPlanet:
          age: 5372165998
          classification: P
          radius: 157.7973714137211
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 66614
        temperature: 255
      - name: Xuange 4c
        description: ''
        tags: []
        satellite:
          axialTilt: 37.33
          semiMajorAxis: 78346.6794109557
          eccentricity: 0.01
          inclination: 1.44
          orbitalArc: 176
          showOrbit: true
          parentId: Xuange 4
        isPlanet:
          age: 8194413214
          classification: K
          radius: 187.88172520612875
          terranMass: 1.1000001511509185
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 41090
        temperature: 208
  - name: Xuange 5
    description: ''
    tags: []
    satellite:
      axialTilt: 21.23
      semiMajorAxis: 1233602034.9999905
      eccentricity: 0.02
      inclination: 1.08
      orbitalArc: 196
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 7881049402
      classification: J
      radius: 58312
      terranMass: 0.25848659400676527
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 193
    satellites: []
  - name: Xuange 6
    description: ''
    tags: []
    satellite:
      axialTilt: 13.8
      semiMajorAxis: 1359477561.3333206
      eccentricity: 0.01
      inclination: 1.6
      orbitalArc: 178
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 741181916
      classification: C
      radius: 1922
      terranMass: 0.004370821203773873
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 40
    satellites:
      - name: Xuange 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 6.51
          semiMajorAxis: 82682.38394398082
          eccentricity: 0.02
          inclination: 0.48
          orbitalArc: 95
          showOrbit: true
          parentId: Xuange 6
        isPlanet:
          age: 7917226137
          classification: P
          radius: 110.20735476908912
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 99365
        temperature: 264
      - name: Xuange 6b
        description: ''
        tags: []
        satellite:
          axialTilt: 7.41
          semiMajorAxis: 161950.30424307767
          eccentricity: 0.02
          inclination: 0.34
          orbitalArc: 335
          showOrbit: true
          parentId: Xuange 6
        isPlanet:
          age: 52831346
          classification: C
          radius: 477.7295110415271
          terranMass: 0.300000101379187
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 40
  - name: Xuange 7
    description: ''
    tags: []
    satellite:
      axialTilt: 13.96
      semiMajorAxis: 2031334123.3333206
      eccentricity: 0
      inclination: 0.2
      orbitalArc: 226
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 2896415368
      classification: J
      radius: 68631
      terranMass: 0.16408454669618153
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 198
    satellites:
      - name: Xuange 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 11.99
          semiMajorAxis: 4379479.019989092
          eccentricity: 0.01
          inclination: 0.29
          orbitalArc: 4
          showOrbit: true
          parentId: Xuange 7
        isPlanet:
          age: 8332734834
          classification: B
          radius: 11555.353614746944
          terranMass: 0.10000015517563413
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 245
  - name: Xuange 8
    description: ''
    tags: []
    satellite:
      axialTilt: 26.29
      semiMajorAxis: 2635723637.77776
      eccentricity: 0.01
      inclination: 1.45
      orbitalArc: 161
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 672116065
      classification: D
      radius: 177
      terranMass: 0.006004295485765562
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 202
    satellites: []
  - name: Xuange 9
    description: ''
    tags: []
    satellite:
      axialTilt: 13.64
      semiMajorAxis: 3570589110
      eccentricity: 0.02
      inclination: 0.51
      orbitalArc: 212
      showOrbit: true
      parentId: Xuange
    isPlanet:
      age: 242987957
      classification: D
      radius: 158
      terranMass: 0.0121292695920875
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 192
    satellites: []
commSatellite: null
assets: {}
