apiVersion: solarSystem/v1
kind: solarSystems
name: Fomalhaut
description: A solar system named Fomalhaut
position:
  x: 3087411.655871943
  'y': 6533074.606242581
  z: 11067331.298019836
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Fomalhaut
stars:
  - name: Fomalhaut A
    description: ''
    tags: []
    solarMass: 1.92
    age: 5994025774602
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.842
    temperature: 8590
    satellite:
      axialTilt: 0
      semiMajorAxis: 22.104
      eccentricity: 0
      inclination: 0
      orbitalArc: 331
      showOrbit: false
      parentId: Fomalhaut
  - name: Fomalhaut B
    description: ''
    tags: []
    solarMass: 1.92
    age: 5994025774602
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.842
    temperature: 8590
    satellite:
      axialTilt: 0
      semiMajorAxis: 22.104
      eccentricity: 0
      inclination: 0
      orbitalArc: 511
      showOrbit: false
      parentId: Fomalhaut
planets:
  - name: Fomalhaut 1
    description: ''
    tags: []
    satellite:
      axialTilt: 5.8
      semiMajorAxis: 1028639570
      eccentricity: 0.01
      inclination: 0.08
      orbitalArc: 266
      showOrbit: true
      parentId: Fomalhaut
    isPlanet:
      age: 8140615897
      classification: J
      radius: 30658
      terranMass: 0.08336771833555953
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 136
    satellites: []
  - name: Fomalhaut 2
    description: ''
    tags: []
    satellite:
      axialTilt: 7.71
      semiMajorAxis: 2132431445.6666656
      eccentricity: 0.02
      inclination: 1.42
      orbitalArc: 347
      showOrbit: true
      parentId: Fomalhaut
    isPlanet:
      age: 317218212
      classification: C
      radius: 1068
      terranMass: 0.001704864983140716
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 49
    satellites: []
  - name: Fomalhaut 3
    description: ''
    tags: []
    satellite:
      axialTilt: 5.36
      semiMajorAxis: 3065334832
      eccentricity: 0
      inclination: 0.17
      orbitalArc: 160
      showOrbit: true
      parentId: Fomalhaut
    isPlanet:
      age: 9478353321
      classification: J
      radius: 64890
      terranMass: 0.5268781674902137
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 165
    satellites:
      - name: Fomalhaut 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 3.67
          semiMajorAxis: 2091991.4753251134
          eccentricity: 0
          inclination: 1.51
          orbitalArc: 179
          showOrbit: true
          parentId: Fomalhaut 3
        isPlanet:
          age: 859596431
          classification: D
          radius: 11439.615638323157
          terranMass: 1.3599998466482182
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 300
      - name: Fomalhaut 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 34.3
          semiMajorAxis: 4694531.609667045
          eccentricity: 0
          inclination: 0.39
          orbitalArc: 213
          showOrbit: true
          parentId: Fomalhaut 3
        isPlanet:
          age: 7418947633
          classification: K
          radius: 10742.635262395985
          terranMass: 2.1000001045731063
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 5895
        temperature: 295
commSatellite: null
assets: {}
