apiVersion: solarSystem/v1
kind: solarSystems
name: Chertan
description: A solar system named Chertan
position:
  x: -16592356.98363786
  'y': -23089041.42648669
  z: -81993587.37909634
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Chertan
stars:
  - name: Chertan A
    description: ''
    tags: []
    solarMass: 2.8
    age: 1231073191967
    spectralType: A
    hue: 180
    isWhite: true
    radius: 4.03
    temperature: 9480
    satellite:
      axialTilt: 0
      semiMajorAxis: 48.36
      eccentricity: 0
      inclination: 0
      orbitalArc: 34
      showOrbit: false
      parentId: Chertan
  - name: Chertan B
    description: ''
    tags: []
    solarMass: 2.8
    age: 1231073191967
    spectralType: A
    hue: 180
    isWhite: true
    radius: 4.03
    temperature: 9480
    satellite:
      axialTilt: 0
      semiMajorAxis: 48.36
      eccentricity: 0
      inclination: 0
      orbitalArc: 214
      showOrbit: false
      parentId: Chertan
planets:
  - name: Chertan 1
    description: ''
    tags: []
    satellite:
      axialTilt: 10.28
      semiMajorAxis: 506121471.00000036
      eccentricity: 0.01
      inclination: 1.22
      orbitalArc: 26
      showOrbit: true
      parentId: Chertan
    isPlanet:
      age: 7137895067
      classification: H
      radius: 4674
      terranMass: 0.014836094596380174
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 580
    satellites: []
  - name: Chertan 2
    description: ''
    tags: []
    satellite:
      axialTilt: 5.95
      semiMajorAxis: 1289836155.0000005
      eccentricity: 0.02
      inclination: 0.22
      orbitalArc: 155
      showOrbit: true
      parentId: Chertan
    isPlanet:
      age: 156422754
      classification: D
      radius: 266
      terranMass: 0.004076767286996559
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 324
    satellites: []
  - name: Chertan 3
    description: ''
    tags: []
    satellite:
      axialTilt: 15.45
      semiMajorAxis: 1680775592.666668
      eccentricity: 0.01
      inclination: 1.01
      orbitalArc: 34
      showOrbit: true
      parentId: Chertan
    isPlanet:
      age: 8327422236
      classification: K
      radius: 2833
      terranMass: 0.028944358994899097
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 30874
    temperature: 124
    satellites:
      - name: Chertan 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.23
          semiMajorAxis: 51975.33977039738
          eccentricity: 0
          inclination: 1.3
          orbitalArc: 309
          showOrbit: true
          parentId: Chertan 3
        isPlanet:
          age: 9223951960
          classification: L
          radius: 258.9773065078136
          terranMass: 1.3000000430809187
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 26244
        temperature: 170
      - name: Chertan 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 9.91
          semiMajorAxis: 100166.09739266467
          eccentricity: 0
          inclination: 1.81
          orbitalArc: 4
          showOrbit: true
          parentId: Chertan 3
        isPlanet:
          age: 6696627350
          classification: L
          radius: 208.24552472487457
          terranMass: 0.3000000564302788
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 46917
        temperature: 329
  - name: Chertan 4
    description: ''
    tags: []
    satellite:
      axialTilt: 17.41
      semiMajorAxis: 2282225876
      eccentricity: 0
      inclination: 0.93
      orbitalArc: 68
      showOrbit: true
      parentId: Chertan
    isPlanet:
      age: 9089380376
      classification: K
      radius: 2574
      terranMass: 0.01105198503622602
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 37536
    temperature: 249
    satellites: []
commSatellite: null
assets: {}
