apiVersion: solarSystem/v1
kind: solarSystems
name: Albireo
description: A solar system named Albireo
position:
  x: 184316829.78821802
  'y': -106036493.59166797
  z: 77027140.58982863
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Albireo
stars:
  - name: Albireo A
    description: ''
    tags: []
    radius: 58.69
    temperature: 4383
    solarMass: 5.2
    age: 235916614039
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 89
      semiMajorAxis: 704.28
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Albireo
  - name: Albireo B
    description: ''
    tags: []
    radius: 58.69
    temperature: 4383
    solarMass: 5.2
    age: 235916614039
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 269
      semiMajorAxis: 704.28
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Albireo
planets:
  - name: Albireo 1
    description: ''
    tags: []
    isPlanet:
      radius: 412
      age: 178583085
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.002101819862827544
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 267
    satellite:
      semiMajorAxis: 2071184238.3333333
      eccentricity: 0
      inclination: 1.06
      orbitalArc: 183
      axialTilt: 2.46
      parentId: Albireo
      showOrbit: true
    satellites: []
  - name: Albireo 2
    description: ''
    tags: []
    isPlanet:
      radius: 69498
      age: 7167779783
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.784079064999027
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 335
    satellite:
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 0.73
      orbitalArc: 182
      axialTilt: 15.65
      parentId: Albireo
      showOrbit: true
    satellites:
      - name: Albireo 2a
        description: ''
        tags: []
        isPlanet:
          radius: 3903.8434125613294
          age: 9447637427
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 124180
        temperature: 258
        satellite:
          semiMajorAxis: 1460037.4362979373
          eccentricity: 0.01
          inclination: 1.73
          orbitalArc: 152
          axialTilt: 27.62
          parentId: Albireo 2
          showOrbit: true
        satellites: []
commSatellite: null
assets: {}
