apiVersion: solarSystem/v1
kind: solarSystems
name: Ancha
description: A solar system named Ancha
position:
  x: 42399588.40801888
  'y': 13319821.954336531
  z: 87740918.90541019
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Ancha
stars:
  - name: 'Ancha '
    description: ''
    tags: []
    solarMass: 2.39
    age: 1710135129130
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12
    temperature: 4864
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 163
      showOrbit: false
      parentId: Ancha
planets:
  - name: Ancha 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.82
      semiMajorAxis: 58980504
      eccentricity: 0.01
      inclination: 1.65
      orbitalArc: 248
      showOrbit: true
      parentId: Ancha
    isPlanet:
      age: 7593812149
      classification: B
      radius: 2662
      terranMass: 0.002811859353029019
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 415
    satellites: []
  - name: Ancha 2
    description: ''
    tags: []
    satellite:
      axialTilt: 11.39
      semiMajorAxis: 317760072
      eccentricity: 0.01
      inclination: 0.13
      orbitalArc: 271
      showOrbit: true
      parentId: Ancha
    isPlanet:
      age: 403416097
      classification: D
      radius: 172
      terranMass: 0.01234827065106963
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 204
    satellites: []
  - name: Ancha 3
    description: ''
    tags: []
    satellite:
      axialTilt: 33.58
      semiMajorAxis: 737300168.6666657
      eccentricity: 0.02
      inclination: 1.76
      orbitalArc: 249
      showOrbit: true
      parentId: Ancha
    isPlanet:
      age: 664340813
      classification: D
      radius: 481
      terranMass: 0.013295749469004598
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 369
    satellites: []
  - name: Ancha 4
    description: ''
    tags: []
    satellite:
      axialTilt: 24.98
      semiMajorAxis: 978473714
      eccentricity: 0.01
      inclination: 1.02
      orbitalArc: 254
      showOrbit: true
      parentId: Ancha
    isPlanet:
      age: 5846914952
      classification: 'N'
      radius: 5307
      terranMass: 0.0022070995868898693
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 292989593
    temperature: 428
    satellites: []
commSatellite: null
assets: {}
