apiVersion: inventory/v1
kind: inventory
name: Coaxial Servo
plural: Coaxial Servos
description: Mechanical rotors with two degrees of freedom.
volume: 3
assets:
  image: /plugins/Thorium Default/inventory/Coaxial Servo/assets/image.svg
continuous: false
durability: 1
abundance: 1
tags: []
flags:
  repair:
    type:
      - General Engineer
      - Mechanic
      - Electrician
      - Exocomp
