apiVersion: solarSystem/v1
kind: solarSystems
name: Minelauva
description: A solar system named Minelauva
position:
  x: 24974928.713601694
  'y': -6171580.081018118
  z: -100912441.2422001
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Minelauva
stars:
  - name: Minelauva A
    description: ''
    tags: []
    solarMass: 1.19
    age: 85774810607
    spectralType: M
    hue: 0
    isWhite: false
    radius: 67.4
    temperature: 3643
    satellite:
      axialTilt: 0
      semiMajorAxis: 808.8000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 60
      showOrbit: false
      parentId: Minelauva
  - name: Minelauva B
    description: ''
    tags: []
    solarMass: 1.19
    age: 85774810607
    spectralType: M
    hue: 0
    isWhite: false
    radius: 67.4
    temperature: 3643
    satellite:
      axialTilt: 0
      semiMajorAxis: 808.8000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 240
      showOrbit: false
      parentId: Minelauva
planets:
  - name: Minelauva 1
    description: ''
    tags: []
    satellite:
      axialTilt: 20.98
      semiMajorAxis: 1650338085.3333333
      eccentricity: 0.01
      inclination: 1.74
      orbitalArc: 84
      showOrbit: true
      parentId: Minelauva
    isPlanet:
      age: 677531841
      classification: D
      radius: 94
      terranMass: 0.02596342454079188
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 221
    satellites: []
  - name: Minelauva 2
    description: ''
    tags: []
    satellite:
      axialTilt: 17.26
      semiMajorAxis: 2790143357.5555553
      eccentricity: 0
      inclination: 1.23
      orbitalArc: 10
      showOrbit: true
      parentId: Minelauva
    isPlanet:
      age: 1304852226
      classification: A
      radius: 4975
      terranMass: 0.012630880275052807
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAcid.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1483
    satellites: []
  - name: Minelauva 3
    description: ''
    tags: []
    satellite:
      axialTilt: 15.08
      semiMajorAxis: 3249078970.1851845
      eccentricity: 0
      inclination: 0.57
      orbitalArc: 208
      showOrbit: true
      parentId: Minelauva
    isPlanet:
      age: 211901644
      classification: C
      radius: 3076
      terranMass: 0.01767726062843949
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 51
    satellites: []
  - name: Minelauva 4
    description: ''
    tags: []
    satellite:
      axialTilt: 37.94
      semiMajorAxis: 3606079648.432099
      eccentricity: 0.01
      inclination: 1.59
      orbitalArc: 29
      showOrbit: true
      parentId: Minelauva
    isPlanet:
      age: 38532058
      classification: D
      radius: 264
      terranMass: 0.006498670080127367
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 350
    satellites: []
  - name: Minelauva 5
    description: ''
    tags: []
    satellite:
      axialTilt: 27.01
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 0.83
      orbitalArc: 204
      showOrbit: true
      parentId: Minelauva
    isPlanet:
      age: 6797199197
      classification: J
      radius: 49805
      terranMass: 0.11653202033520955
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 329
    satellites:
      - name: Minelauva 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 33.36
          semiMajorAxis: 3027589.866016066
          eccentricity: 0.02
          inclination: 1.4
          orbitalArc: 270
          showOrbit: true
          parentId: Minelauva 5
        isPlanet:
          age: 518424740
          classification: E
          radius: 6469.209115418945
          terranMass: 1.5000000170460361
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1439
commSatellite: null
assets: {}
