apiVersion: solarSystem/v1
kind: solarSystems
name: Beemim
description: A solar system named Beemim
position:
  x: -117894572.16375065
  'y': 87095426.53771414
  z: 52467267.94340859
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Beemim
stars:
  - name: Beemim A
    description: ''
    tags: []
    solarMass: 5.64
    age: 440118157361
    spectralType: K
    hue: 30
    isWhite: false
    radius: 54
    temperature: 3990
    satellite:
      axialTilt: 0
      semiMajorAxis: 648
      eccentricity: 0
      inclination: 0
      orbitalArc: 266
      showOrbit: false
      parentId: Beemim
  - name: Beemim B
    description: ''
    tags: []
    solarMass: 5.64
    age: 440118157361
    spectralType: K
    hue: 30
    isWhite: false
    radius: 54
    temperature: 3990
    satellite:
      axialTilt: 0
      semiMajorAxis: 648
      eccentricity: 0
      inclination: 0
      orbitalArc: 446
      showOrbit: false
      parentId: Beemim
planets:
  - name: Beemim 1
    description: ''
    tags: []
    satellite:
      axialTilt: 25.35
      semiMajorAxis: 2252172698.333333
      eccentricity: 0.01
      inclination: 1.78
      orbitalArc: 194
      showOrbit: true
      parentId: Beemim
    isPlanet:
      age: 5580743928
      classification: M
      radius: 6677
      terranMass: 0.007467278491232377
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial1.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 2176517699
    temperature: 297
    satellites:
      - name: Beemim 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.12
          semiMajorAxis: 619755.1217710901
          eccentricity: 0
          inclination: 1.09
          orbitalArc: 212
          showOrbit: true
          parentId: Beemim 1
        isPlanet:
          age: 6777645713
          classification: O
          radius: 1338.563977907322
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 371567390
        temperature: 302
  - name: Beemim 2
    description: ''
    tags: []
    satellite:
      axialTilt: 14.81
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.01
      orbitalArc: 31
      showOrbit: true
      parentId: Beemim
    isPlanet:
      age: 7886453915
      classification: J
      radius: 47936
      terranMass: 1.4533070001991717
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 282
    satellites: []
commSatellite: null
assets: {}
