apiVersion: solarSystem/v1
kind: solarSystems
name: Maasym
description: A solar system named Maasym
position:
  x: 173322557.45844522
  'y': -85646917.52778576
  z: -22250403.616397984
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Maasym
stars:
  - name: Maasym A
    description: ''
    tags: []
    solarMass: 1.18
    age: 156078836812
    spectralType: K
    hue: 30
    isWhite: false
    radius: 40
    temperature: 4063
    satellite:
      axialTilt: 0
      semiMajorAxis: 480
      eccentricity: 0
      inclination: 0
      orbitalArc: 281
      showOrbit: false
      parentId: Maasym
  - name: Maasym B
    description: ''
    tags: []
    solarMass: 1.18
    age: 156078836812
    spectralType: K
    hue: 30
    isWhite: false
    radius: 40
    temperature: 4063
    satellite:
      axialTilt: 0
      semiMajorAxis: 480
      eccentricity: 0
      inclination: 0
      orbitalArc: 461
      showOrbit: false
      parentId: Maasym
planets:
  - name: Maasym 1
    description: ''
    tags: []
    satellite:
      axialTilt: 35.35
      semiMajorAxis: 1484550145.000001
      eccentricity: 0.01
      inclination: 1.89
      orbitalArc: 149
      showOrbit: true
      parentId: Maasym
    isPlanet:
      age: 7902259200
      classification: H
      radius: 6445
      terranMass: 0.017955333142778966
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 601
    satellites: []
  - name: Maasym 2
    description: ''
    tags: []
    satellite:
      axialTilt: 39.89
      semiMajorAxis: 2432027827.0000005
      eccentricity: 0
      inclination: 1.88
      orbitalArc: 258
      showOrbit: true
      parentId: Maasym
    isPlanet:
      age: 6690436436
      classification: P
      radius: 5167
      terranMass: 0.010855930742890558
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 91030
    temperature: 257
    satellites:
      - name: Maasym 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 9.78
          semiMajorAxis: 156252.15340157787
          eccentricity: 0.01
          inclination: 1.52
          orbitalArc: 206
          showOrbit: true
          parentId: Maasym 2
        isPlanet:
          age: 9856132097
          classification: P
          radius: 622.5185394485175
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 187022
        temperature: 265
  - name: Maasym 3
    description: ''
    tags: []
    satellite:
      axialTilt: 4.55
      semiMajorAxis: 3069155676.0000014
      eccentricity: 0
      inclination: 1.88
      orbitalArc: 183
      showOrbit: true
      parentId: Maasym
    isPlanet:
      age: 319542213
      classification: D
      radius: 223
      terranMass: 0.00019162247496421796
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 270
    satellites: []
  - name: Maasym 4
    description: ''
    tags: []
    satellite:
      axialTilt: 6.91
      semiMajorAxis: 3478437958.0000067
      eccentricity: 0
      inclination: 1.02
      orbitalArc: 344
      showOrbit: true
      parentId: Maasym
    isPlanet:
      age: 832123776
      classification: C
      radius: 964
      terranMass: 0.007747908307973168
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 43
    satellites:
      - name: Maasym 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 23.66
          semiMajorAxis: 29769.813727589884
          eccentricity: 0.01
          inclination: 1.54
          orbitalArc: 56
          showOrbit: true
          parentId: Maasym 4
        isPlanet:
          age: 9124545179
          classification: B
          radius: 98.25021032207883
          terranMass: 2.100000308900827
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 287
  - name: Maasym 5
    description: ''
    tags: []
    satellite:
      axialTilt: 16.18
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 1.81
      orbitalArc: 23
      showOrbit: true
      parentId: Maasym
    isPlanet:
      age: 7047759121
      classification: J
      radius: 59782
      terranMass: 0.1413293278790846
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 327
    satellites: []
commSatellite: null
assets: {}
