apiVersion: solarSystem/v1
kind: solarSystems
name: Secunda Hyadum
description: A solar system named Secunda Hyadum
position:
  x: -71321583.40734738
  'y': -24730895.77569941
  z: 32152412.824823644
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Secunda Hyadum
stars:
  - name: Secunda Hyadum A
    description: ''
    tags: []
    solarMass: 2.75
    age: 1324651806964
    spectralType: K
    hue: 30
    isWhite: false
    radius: 14.9
    temperature: 4819
    satellite:
      axialTilt: 0
      semiMajorAxis: 178.8
      eccentricity: 0
      inclination: 0
      orbitalArc: 214
      showOrbit: false
      parentId: Secunda Hyadum
  - name: Secunda Hyadum B
    description: ''
    tags: []
    solarMass: 2.75
    age: 1324651806964
    spectralType: K
    hue: 30
    isWhite: false
    radius: 14.9
    temperature: 4819
    satellite:
      axialTilt: 0
      semiMajorAxis: 178.8
      eccentricity: 0
      inclination: 0
      orbitalArc: 394
      showOrbit: false
      parentId: Secunda Hyadum
planets:
  - name: Secunda Hyadum 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.78
      semiMajorAxis: 1853844095.333334
      eccentricity: 0.02
      inclination: 1.29
      orbitalArc: 165
      showOrbit: true
      parentId: Secunda Hyadum
    isPlanet:
      age: 1273124710
      classification: E
      radius: 5838
      terranMass: 0.0027439398805029812
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1079
    satellites:
      - name: Secunda Hyadum 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.2
          semiMajorAxis: 100910.52044220781
          eccentricity: 0.01
          inclination: 1.52
          orbitalArc: 96
          showOrbit: true
          parentId: Secunda Hyadum 1
        isPlanet:
          age: 4777729340
          classification: P
          radius: 623.5789657529162
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 24745
        temperature: 266
      - name: Secunda Hyadum 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 23.99
          semiMajorAxis: 233769.53283999852
          eccentricity: 0.02
          inclination: 0.37
          orbitalArc: 100
          showOrbit: true
          parentId: Secunda Hyadum 1
        isPlanet:
          age: 8437810454
          classification: P
          radius: 522.974346398207
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 43248
        temperature: 257
  - name: Secunda Hyadum 2
    description: ''
    tags: []
    satellite:
      axialTilt: 21.44
      semiMajorAxis: 3020656147
      eccentricity: 0.01
      inclination: 0.34
      orbitalArc: 100
      showOrbit: true
      parentId: Secunda Hyadum
    isPlanet:
      age: 9534895783
      classification: J
      radius: 50785
      terranMass: 0.45144454476806445
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 335
    satellites: []
commSatellite: null
assets: {}
