apiVersion: solarSystem/v1
kind: solarSystems
name: Ain
description: A solar system named Ain
position:
  x: -67295654.4593514
  'y': -25401758.764949728
  z: 28351859.804769024
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Ain
stars:
  - name: Ain A
    description: ''
    tags: []
    solarMass: 2.458
    age: 1610036754356
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12.46
    temperature: 4880
    satellite:
      axialTilt: 0
      semiMajorAxis: 149.52
      eccentricity: 0
      inclination: 0
      orbitalArc: 239
      showOrbit: false
      parentId: Ain
  - name: Ain B
    description: ''
    tags: []
    solarMass: 2.458
    age: 1610036754356
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12.46
    temperature: 4880
    satellite:
      axialTilt: 0
      semiMajorAxis: 149.52
      eccentricity: 0
      inclination: 0
      orbitalArc: 419
      showOrbit: false
      parentId: Ain
planets:
  - name: Ain 1
    description: ''
    tags: []
    satellite:
      axialTilt: 35.55
      semiMajorAxis: 1413101128
      eccentricity: 0
      inclination: 0.9
      orbitalArc: 244
      showOrbit: true
      parentId: Ain
    isPlanet:
      age: 128352827
      classification: D
      radius: 443
      terranMass: 0.0038262106052195963
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 306
    satellites: []
commSatellite: null
assets: {}
