apiVersion: solarSystem/v1
kind: solarSystems
name: Sheratan
description: A solar system named Sheratan
position:
  x: -14053880.894365547
  'y': -11135722.035175873
  z: 25712488.74599543
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sheratan
stars:
  - name: Sheratan A
    description: ''
    tags: []
    solarMass: 2.067
    age: 5140088937130
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.985
    temperature: 8759
    satellite:
      axialTilt: 0
      semiMajorAxis: 23.82
      eccentricity: 0
      inclination: 0
      orbitalArc: 67
      showOrbit: false
      parentId: Sheratan
  - name: Sheratan B
    description: ''
    tags: []
    solarMass: 2.067
    age: 5140088937130
    spectralType: A
    hue: 180
    isWhite: true
    radius: 1.985
    temperature: 8759
    satellite:
      axialTilt: 0
      semiMajorAxis: 23.82
      eccentricity: 0
      inclination: 0
      orbitalArc: 247
      showOrbit: false
      parentId: Sheratan
planets:
  - name: Sheratan 1
    description: ''
    tags: []
    satellite:
      axialTilt: 18.6
      semiMajorAxis: 928030612
      eccentricity: 0.02
      inclination: 0.7
      orbitalArc: 211
      showOrbit: true
      parentId: Sheratan
    isPlanet:
      age: 959300164
      classification: C
      radius: 889
      terranMass: 0.022093882286039885
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 33
    satellites:
      - name: Sheratan 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.4
          semiMajorAxis: 85780.1912292313
          eccentricity: 0.01
          inclination: 0.24
          orbitalArc: 314
          showOrbit: true
          parentId: Sheratan 1
        isPlanet:
          age: 5200534346
          classification: P
          radius: 182.12354825739132
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 135480
        temperature: 269
commSatellite: null
assets: {}
