apiVersion: solarSystem/v1
kind: solarSystems
name: Cujam
description: A solar system named Cujam
position:
  x: 116855385.18677661
  'y': -31884398.032812674
  z: -51164677.41455275
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Cujam
stars:
  - name: Cujam A
    description: ''
    tags: []
    solarMass: 2.14
    age: 1110056945130
    spectralType: B
    hue: 200
    isWhite: false
    radius: 3.3
    temperature: 10052
    satellite:
      axialTilt: 0
      semiMajorAxis: 39.599999999999994
      eccentricity: 0
      inclination: 0
      orbitalArc: 271
      showOrbit: false
      parentId: Cujam
  - name: Cujam B
    description: ''
    tags: []
    solarMass: 2.14
    age: 1110056945130
    spectralType: B
    hue: 200
    isWhite: false
    radius: 3.3
    temperature: 10052
    satellite:
      axialTilt: 0
      semiMajorAxis: 39.599999999999994
      eccentricity: 0
      inclination: 0
      orbitalArc: 451
      showOrbit: false
      parentId: Cujam
planets: []
commSatellite: null
assets: {}
