apiVersion: solarSystem/v1
kind: solarSystems
name: Adhara
description: A solar system named Adhara
position:
  x: -191644128.1546518
  'y': 109676901.77506141
  z: -50121245.09103227
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Adhara
stars:
  - name: Adhara A
    description: ''
    tags: []
    solarMass: 13.1
    age: 26210840726
    spectralType: B
    hue: 200
    isWhite: false
    radius: 10.7
    temperature: 22400
    satellite:
      axialTilt: 0
      semiMajorAxis: 128.39999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 213
      showOrbit: false
      parentId: Adhara
  - name: Adhara B
    description: ''
    tags: []
    solarMass: 13.1
    age: 26210840726
    spectralType: B
    hue: 200
    isWhite: false
    radius: 10.7
    temperature: 22400
    satellite:
      axialTilt: 0
      semiMajorAxis: 128.39999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 393
      showOrbit: false
      parentId: Adhara
planets:
  - name: Adhara 1
    description: ''
    tags: []
    satellite:
      axialTilt: 27.88
      semiMajorAxis: 2572626881.333333
      eccentricity: 0.02
      inclination: 1.27
      orbitalArc: 9
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 798931547
      classification: D
      radius: 129
      terranMass: 0.0061565695334652665
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 397
    satellites: []
  - name: Adhara 2
    description: ''
    tags: []
    satellite:
      axialTilt: 26.96
      semiMajorAxis: 3187932673.111112
      eccentricity: 0.02
      inclination: 0.92
      orbitalArc: 41
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 6255533555
      classification: J
      radius: 32998
      terranMass: 1.2509427465861533
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 314
    satellites:
      - name: Adhara 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.1
          semiMajorAxis: 2228752.4099284853
          eccentricity: 0.01
          inclination: 0.36
          orbitalArc: 330
          showOrbit: true
          parentId: Adhara 2
        isPlanet:
          age: 8513226041
          classification: P
          radius: 5244.123317478789
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 191780
        temperature: 264
  - name: Adhara 3
    description: ''
    tags: []
    satellite:
      axialTilt: 38.28
      semiMajorAxis: 3827126830.9629636
      eccentricity: 0
      inclination: 1.18
      orbitalArc: 167
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 626289066
      classification: D
      radius: 352
      terranMass: 0.005299412646706017
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 269
    satellites: []
  - name: Adhara 4
    description: ''
    tags: []
    satellite:
      axialTilt: 8.65
      semiMajorAxis: 6697803228.641975
      eccentricity: 0
      inclination: 1.66
      orbitalArc: 160
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 982792666
      classification: C
      radius: 2830
      terranMass: 0.004800501294501007
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 40
    satellites:
      - name: Adhara 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.37
          semiMajorAxis: 173753.7392181621
          eccentricity: 0.01
          inclination: 0.59
          orbitalArc: 0
          showOrbit: true
          parentId: Adhara 4
        isPlanet:
          age: 6263744061
          classification: K
          radius: 684.0698394415831
          terranMass: 2.300000036779617
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 26597
        temperature: 236
  - name: Adhara 5
    description: ''
    tags: []
    satellite:
      axialTilt: 16.35
      semiMajorAxis: 9429418001.09465
      eccentricity: 0.01
      inclination: 1.32
      orbitalArc: 241
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 9243685790
      classification: M
      radius: 7007
      terranMass: 0.006474686865456098
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 8925283335
    temperature: 300
    satellites: []
  - name: Adhara 6
    description: ''
    tags: []
    satellite:
      axialTilt: 9.69
      semiMajorAxis: 11317197160.792864
      eccentricity: 0
      inclination: 0.7
      orbitalArc: 11
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 3573841508
      classification: P
      radius: 5159
      terranMass: 0.004867464771346997
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 56208
    temperature: 257
    satellites:
      - name: Adhara 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 1.27
          semiMajorAxis: 268363.4793553876
          eccentricity: 0.02
          inclination: 1.78
          orbitalArc: 67
          showOrbit: true
          parentId: Adhara 6
        isPlanet:
          age: 350525927
          classification: D
          radius: 938.3338438999567
          terranMass: 0.5699997618751012
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 172
  - name: Adhara 7
    description: ''
    tags: []
    satellite:
      axialTilt: 20.62
      semiMajorAxis: 12514184774.792866
      eccentricity: 0.01
      inclination: 0.04
      orbitalArc: 90
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 544739108
      classification: A
      radius: 4912
      terranMass: 0.03148694000262409
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 1689
    satellites:
      - name: Adhara 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.13
          semiMajorAxis: 58413.816709280654
          eccentricity: 0.01
          inclination: 1.44
          orbitalArc: 136
          showOrbit: true
          parentId: Adhara 7
        isPlanet:
          age: 57156124
          classification: A
          radius: 281.236105479029
          terranMass: 1.700000412767738
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1578
      - name: Adhara 7b
        description: ''
        tags: []
        satellite:
          axialTilt: 21.83
          semiMajorAxis: 126759.75495529213
          eccentricity: 0.01
          inclination: 1.75
          orbitalArc: 247
          showOrbit: true
          parentId: Adhara 7
        isPlanet:
          age: 9494146129
          classification: P
          radius: 352.85605254547113
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 26031
        temperature: 263
      - name: Adhara 7c
        description: ''
        tags: []
        satellite:
          axialTilt: 34.72
          semiMajorAxis: 204585.54212027488
          eccentricity: 0.02
          inclination: 0.28
          orbitalArc: 306
          showOrbit: true
          parentId: Adhara 7
        isPlanet:
          age: 984357602
          classification: D
          radius: 422.6974010749481
          terranMass: 0.7899998726255675
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 253
  - name: Adhara 8
    description: ''
    tags: []
    satellite:
      axialTilt: 0.69
      semiMajorAxis: 13387824719
      eccentricity: 0
      inclination: 0.85
      orbitalArc: 179
      showOrbit: true
      parentId: Adhara
    isPlanet:
      age: 7386145787
      classification: H
      radius: 7241
      terranMass: 0.03164479480664731
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 675
    satellites: []
commSatellite: null
assets: {}
