apiVersion: solarSystem/v1
kind: solarSystems
name: Nahn
description: A solar system named Nahn
position:
  x: -122232420.43668464
  'y': -73043485.78078626
  z: -132646403.8194086
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Nahn
stars:
  - name: Nahn A
    description: ''
    tags: []
    radius: 16.3
    temperature: 5025
    solarMass: 3.4
    age: 1157520598823
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 124
      semiMajorAxis: 195.60000000000002
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Nahn
  - name: Nahn B
    description: ''
    tags: []
    radius: 16.3
    temperature: 5025
    solarMass: 3.4
    age: 1157520598823
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 304
      semiMajorAxis: 195.60000000000002
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Nahn
planets:
  - name: Nahn 1
    description: ''
    tags: []
    isPlanet:
      radius: 5867
      age: 7421285352
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.007416322465268039
      textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
      classification: 'N'
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
    population: 372898820
    temperature: 396
    satellite:
      semiMajorAxis: 974873077.0000008
      eccentricity: 0.01
      inclination: 0.64
      orbitalArc: 161
      axialTilt: 16.06
      parentId: Nahn
      showOrbit: true
    satellites: []
  - name: Nahn 2
    description: ''
    tags: []
    isPlanet:
      radius: 6290
      age: 9320011868
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.007382313458920063
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      classification: P
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
    population: 21064
    temperature: 256
    satellite:
      semiMajorAxis: 1641324896.0000007
      eccentricity: 0.01
      inclination: 1.89
      orbitalArc: 202
      axialTilt: 39.43
      parentId: Nahn
      showOrbit: true
    satellites: []
  - name: Nahn 3
    description: ''
    tags: []
    isPlanet:
      radius: 182
      age: 838011850
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
      terranMass: 0.006236235924225496
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 206
    satellite:
      semiMajorAxis: 2031294645.0000057
      eccentricity: 0.01
      inclination: 0.96
      orbitalArc: 184
      axialTilt: 33.6
      parentId: Nahn
      showOrbit: true
    satellites: []
  - name: Nahn 4
    description: ''
    tags: []
    isPlanet:
      radius: 5677
      age: 1460755029
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
      terranMass: 0.014240951444952389
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
      classification: E
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 1181
    satellite:
      semiMajorAxis: 2417888582.000025
      eccentricity: 0.01
      inclination: 0.23
      orbitalArc: 175
      axialTilt: 2.35
      parentId: Nahn
      showOrbit: true
    satellites:
      - name: Nahn 4a
        description: ''
        tags: []
        isPlanet:
          radius: 616.7061296088984
          age: 3493828856
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 197741
        temperature: 270
        satellite:
          semiMajorAxis: 117574.44221491957
          eccentricity: 0.01
          inclination: 1.09
          orbitalArc: 163
          axialTilt: 34.59
          parentId: Nahn 4
          showOrbit: true
        satellites: []
      - name: Nahn 4b
        description: ''
        tags: []
        isPlanet:
          radius: 726.0183427274853
          age: 6974272787
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.7000001410763578
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          classification: H
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
        population: 0
        temperature: 571
        satellite:
          semiMajorAxis: 324530.19919918594
          eccentricity: 0.01
          inclination: 1.58
          orbitalArc: 167
          axialTilt: 7.8
          parentId: Nahn 4
          showOrbit: true
        satellites: []
  - name: Nahn 5
    description: ''
    tags: []
    isPlanet:
      radius: 360
      age: 553506768
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.004534232854075945
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 161
    satellite:
      semiMajorAxis: 2826250872
      eccentricity: 0.01
      inclination: 1.03
      orbitalArc: 279
      axialTilt: 15.39
      parentId: Nahn
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
