apiVersion: solarSystem/v1
kind: solarSystems
name: Alderamin
description: A solar system named Alderamin
position:
  x: 7683540.321674287
  'y': -22877826.695797727
  z: 9042471.983028226
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alderamin
stars:
  - name: Alderamin A
    description: ''
    tags: []
    solarMass: 2
    age: 4805194496827
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.175
    temperature: 8440
    satellite:
      axialTilt: 0
      semiMajorAxis: 26.099999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 216
      showOrbit: false
      parentId: Alderamin
  - name: Alderamin B
    description: ''
    tags: []
    solarMass: 2
    age: 4805194496827
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.175
    temperature: 8440
    satellite:
      axialTilt: 0
      semiMajorAxis: 26.099999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 396
      showOrbit: false
      parentId: Alderamin
planets:
  - name: Alderamin 1
    description: ''
    tags: []
    satellite:
      axialTilt: 4.92
      semiMajorAxis: 459275257.99999934
      eccentricity: 0.01
      inclination: 1.24
      orbitalArc: 103
      showOrbit: true
      parentId: Alderamin
    isPlanet:
      age: 8209329453
      classification: L
      radius: 2669
      terranMass: 0.01372260568880034
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 32575
    temperature: 186
    satellites:
      - name: Alderamin 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.65
          semiMajorAxis: 141442.44934275997
          eccentricity: 0.02
          inclination: 0.93
          orbitalArc: 277
          showOrbit: true
          parentId: Alderamin 1
        isPlanet:
          age: 5626355572
          classification: P
          radius: 342.47566426818395
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 116038
        temperature: 260
  - name: Alderamin 2
    description: ''
    tags: []
    satellite:
      axialTilt: 38.68
      semiMajorAxis: 764486960
      eccentricity: 0.01
      inclination: 1.39
      orbitalArc: 50
      showOrbit: true
      parentId: Alderamin
    isPlanet:
      age: 4008517494
      classification: O
      radius: 5722
      terranMass: 0.00994121409776649
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 253935248
    temperature: 295
    satellites:
      - name: Alderamin 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 12.21
          semiMajorAxis: 447967.6242468203
          eccentricity: 0
          inclination: 0.84
          orbitalArc: 227
          showOrbit: true
          parentId: Alderamin 2
        isPlanet:
          age: 5472039554
          classification: P
          radius: 1178.8621690705797
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 139105
        temperature: 270
commSatellite: null
assets: {}
