apiVersion: solarSystem/v1
kind: solarSystems
name: Sham
description: A solar system named Sham
position:
  x: 173132477.94620204
  'y': -62133006.01362167
  z: 80821797.92282228
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sham
stars:
  - name: Sham A
    description: ''
    tags: []
    solarMass: 4.11
    age: 664486530708
    spectralType: G
    hue: 45
    isWhite: false
    radius: 21
    temperature: 5333
    satellite:
      axialTilt: 0
      semiMajorAxis: 252
      eccentricity: 0
      inclination: 0
      orbitalArc: 165
      showOrbit: false
      parentId: Sham
  - name: Sham B
    description: ''
    tags: []
    solarMass: 4.11
    age: 664486530708
    spectralType: G
    hue: 45
    isWhite: false
    radius: 21
    temperature: 5333
    satellite:
      axialTilt: 0
      semiMajorAxis: 252
      eccentricity: 0
      inclination: 0
      orbitalArc: 345
      showOrbit: false
      parentId: Sham
planets:
  - name: Sham 1
    description: ''
    tags: []
    satellite:
      axialTilt: 12.5
      semiMajorAxis: 1415658363
      eccentricity: 0.02
      inclination: 0.73
      orbitalArc: 35
      showOrbit: true
      parentId: Sham
    isPlanet:
      age: 8954235296
      classification: 'N'
      radius: 5937
      terranMass: 0.02207681027464029
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 68200011
    temperature: 676
    satellites:
      - name: Sham 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.79
          semiMajorAxis: 131800.16923554015
          eccentricity: 0
          inclination: 1.25
          orbitalArc: 182
          showOrbit: true
          parentId: Sham 1
        isPlanet:
          age: 3994648407
          classification: 'N'
          radius: 587.8775265627838
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 442048285
        temperature: 618
      - name: Sham 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 39.9
          semiMajorAxis: 500103.8413339942
          eccentricity: 0.01
          inclination: 1.14
          orbitalArc: 187
          showOrbit: true
          parentId: Sham 1
        isPlanet:
          age: 620518122
          classification: D
          radius: 847.4028668987688
          terranMass: 0.8299999051141669
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 155
      - name: Sham 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 7.09
          semiMajorAxis: 699805.4823762396
          eccentricity: 0.02
          inclination: 1.1
          orbitalArc: 243
          showOrbit: true
          parentId: Sham 1
        isPlanet:
          age: 1895994685
          classification: F
          radius: 1460.9717794911057
          terranMass: 0.7000001535539776
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 717
  - name: Sham 2
    description: ''
    tags: []
    satellite:
      axialTilt: 33
      semiMajorAxis: 2976067962
      eccentricity: 0.02
      inclination: 0.77
      orbitalArc: 314
      showOrbit: true
      parentId: Sham
    isPlanet:
      age: 9310022792
      classification: K
      radius: 3058
      terranMass: 0.01588261698787948
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 46586
    temperature: 119
    satellites:
      - name: Sham 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 7.64
          semiMajorAxis: 321710.61293431587
          eccentricity: 0.01
          inclination: 0.03
          orbitalArc: 231
          showOrbit: true
          parentId: Sham 2
        isPlanet:
          age: 7532466756
          classification: O
          radius: 659.2430592916309
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 602856614
        temperature: 300
commSatellite: null
assets: {}
