apiVersion: solarSystem/v1
kind: solarSystems
name: Alchiba
description: A solar system named Alchiba
position:
  x: 853909.5645914868
  'y': 10715078.79096118
  z: -23249684.524278987
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alchiba
stars:
  - name: Alchiba A
    description: ''
    tags: []
    solarMass: 1.34
    age: 16100217842103
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.42
    temperature: 6985
    satellite:
      axialTilt: 0
      semiMajorAxis: 17.04
      eccentricity: 0
      inclination: 0
      orbitalArc: 113
      showOrbit: false
      parentId: Alchiba
  - name: Alchiba B
    description: ''
    tags: []
    solarMass: 1.34
    age: 16100217842103
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.42
    temperature: 6985
    satellite:
      axialTilt: 0
      semiMajorAxis: 17.04
      eccentricity: 0
      inclination: 0
      orbitalArc: 293
      showOrbit: false
      parentId: Alchiba
planets:
  - name: Alchiba 1
    description: ''
    tags: []
    satellite:
      axialTilt: 30.6
      semiMajorAxis: 316356051.33333385
      eccentricity: 0.01
      inclination: 1.05
      orbitalArc: 259
      showOrbit: true
      parentId: Alchiba
    isPlanet:
      age: 593012317
      classification: D
      radius: 109
      terranMass: 0.0041228715415777125
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 371
    satellites: []
  - name: Alchiba 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.89
      semiMajorAxis: 866894516
      eccentricity: 0.01
      inclination: 1.91
      orbitalArc: 344
      showOrbit: true
      parentId: Alchiba
    isPlanet:
      age: 5103792188
      classification: J
      radius: 34383
      terranMass: 0.03729201571603585
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 315
    satellites: []
commSatellite: null
assets: {}
