apiVersion: solarSystem/v1
kind: solarSystems
name: Taiyi
description: A solar system named Taiyi
position:
  x: 5025644.46501475
  'y': -45875562.03020126
  z: -20354982.74709465
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Taiyi
stars:
  - name: Taiyi A
    description: ''
    tags: []
    solarMass: 1.56
    age: 15480924971644
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.5
    temperature: 7129
    satellite:
      axialTilt: 0
      semiMajorAxis: 18
      eccentricity: 0
      inclination: 0
      orbitalArc: 48
      showOrbit: false
      parentId: Taiyi
  - name: Taiyi B
    description: ''
    tags: []
    solarMass: 1.56
    age: 15480924971644
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.5
    temperature: 7129
    satellite:
      axialTilt: 0
      semiMajorAxis: 18
      eccentricity: 0
      inclination: 0
      orbitalArc: 228
      showOrbit: false
      parentId: Taiyi
planets:
  - name: Taiyi 1
    description: ''
    tags: []
    satellite:
      axialTilt: 36.19
      semiMajorAxis: 169130405
      eccentricity: 0.02
      inclination: 1.98
      orbitalArc: 200
      showOrbit: true
      parentId: Taiyi
    isPlanet:
      age: 8368143478
      classification: H
      radius: 6728
      terranMass: 0.0056591649577962255
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 626
    satellites: []
  - name: Taiyi 2
    description: ''
    tags: []
    satellite:
      axialTilt: 12.3
      semiMajorAxis: 238708728.00000075
      eccentricity: 0.02
      inclination: 1.04
      orbitalArc: 75
      showOrbit: true
      parentId: Taiyi
    isPlanet:
      age: 1623207722
      classification: A
      radius: 3637
      terranMass: 0.024056199587765354
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1491
    satellites: []
  - name: Taiyi 3
    description: ''
    tags: []
    satellite:
      axialTilt: 12.43
      semiMajorAxis: 297142014.0000178
      eccentricity: 0.02
      inclination: 1.33
      orbitalArc: 170
      showOrbit: true
      parentId: Taiyi
    isPlanet:
      age: 788512904
      classification: A
      radius: 2361
      terranMass: 0.01632972473493473
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 1537
    satellites:
      - name: Taiyi 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 33.24
          semiMajorAxis: 172786.16112953454
          eccentricity: 0
          inclination: 0.57
          orbitalArc: 162
          showOrbit: true
          parentId: Taiyi 3
        isPlanet:
          age: 9958614710
          classification: K
          radius: 362.99613682675323
          terranMass: 2.100000007396242
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 12177
        temperature: 218
  - name: Taiyi 4
    description: ''
    tags: []
    satellite:
      axialTilt: 0.99
      semiMajorAxis: 364589782.0002538
      eccentricity: 0.01
      inclination: 0.8
      orbitalArc: 92
      showOrbit: true
      parentId: Taiyi
    isPlanet:
      age: 3052333995
      classification: P
      radius: 5269
      terranMass: 0.009161973814866966
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 59610
    temperature: 261
    satellites: []
  - name: Taiyi 5
    description: ''
    tags: []
    satellite:
      axialTilt: 2.28
      semiMajorAxis: 498530235
      eccentricity: 0.01
      inclination: 1.16
      orbitalArc: 182
      showOrbit: true
      parentId: Taiyi
    isPlanet:
      age: 7698828711
      classification: P
      radius: 7382
      terranMass: 0.028778643078701257
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 96401
    temperature: 257
    satellites:
      - name: Taiyi 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 29.95
          semiMajorAxis: 179276.84637262954
          eccentricity: 0.01
          inclination: 1.65
          orbitalArc: 286
          showOrbit: true
          parentId: Taiyi 5
        isPlanet:
          age: 844344959
          classification: D
          radius: 714.1499706218135
          terranMass: 1.109999719311838
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 156
      - name: Taiyi 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 28.98
          semiMajorAxis: 375374.6809569591
          eccentricity: 0
          inclination: 0.62
          orbitalArc: 239
          showOrbit: true
          parentId: Taiyi 5
        isPlanet:
          age: 6400882436
          classification: K
          radius: 1020.0398939047801
          terranMass: 0.7000000110834325
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 47863
        temperature: 285
commSatellite: null
assets: {}
