apiVersion: solarSystem/v1
kind: solarSystems
name: Ukdah
description: A solar system named Ukdah
position:
  x: -79396751.08332227
  'y': 2758868.9291713513
  z: -113238846.17389485
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Ukdah
stars:
  - name: Ukdah A
    description: ''
    tags: []
    solarMass: 1.92
    age: 381403078563
    spectralType: K
    hue: 30
    isWhite: false
    radius: 30
    temperature: 4238
    satellite:
      axialTilt: 0
      semiMajorAxis: 360
      eccentricity: 0
      inclination: 0
      orbitalArc: 100
      showOrbit: false
      parentId: Ukdah
  - name: Ukdah B
    description: ''
    tags: []
    solarMass: 1.92
    age: 381403078563
    spectralType: K
    hue: 30
    isWhite: false
    radius: 30
    temperature: 4238
    satellite:
      axialTilt: 0
      semiMajorAxis: 360
      eccentricity: 0
      inclination: 0
      orbitalArc: 280
      showOrbit: false
      parentId: Ukdah
planets:
  - name: Ukdah 1
    description: ''
    tags: []
    satellite:
      axialTilt: 5.77
      semiMajorAxis: 2461422918
      eccentricity: 0.01
      inclination: 0.48
      orbitalArc: 325
      showOrbit: true
      parentId: Ukdah
    isPlanet:
      age: 7864465101
      classification: K
      radius: 4498
      terranMass: 0.029301196995891104
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 25913
    temperature: 205
    satellites: []
  - name: Ukdah 2
    description: ''
    tags: []
    satellite:
      axialTilt: 5.17
      semiMajorAxis: 3395963881.3333316
      eccentricity: 0.02
      inclination: 1.49
      orbitalArc: 28
      showOrbit: true
      parentId: Ukdah
    isPlanet:
      age: 941507864
      classification: D
      radius: 279
      terranMass: 0.0055257487756995025
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 398
    satellites: []
  - name: Ukdah 3
    description: ''
    tags: []
    satellite:
      axialTilt: 18.07
      semiMajorAxis: 3964230869
      eccentricity: 0.01
      inclination: 0.61
      orbitalArc: 196
      showOrbit: true
      parentId: Ukdah
    isPlanet:
      age: 9867935628
      classification: J
      radius: 67303
      terranMass: 1.6645393579580212
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 184
    satellites:
      - name: Ukdah 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.17
          semiMajorAxis: 3797264.230700581
          eccentricity: 0.01
          inclination: 0.13
          orbitalArc: 276
          showOrbit: true
          parentId: Ukdah 3
        isPlanet:
          age: 9123739711
          classification: K
          radius: 13094.014588622693
          terranMass: 0.900000048340558
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 6511
        temperature: 150
commSatellite: null
assets: {}
