apiVersion: solarSystem/v1
kind: solarSystems
name: Terebellum
description: A solar system named Terebellum
position:
  x: 31519506.18678996
  'y': 17803789.0865985
  z: 17442676.369272046
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Terebellum
stars:
  - name: Terebellum A
    description: ''
    tags: []
    solarMass: 1.52
    age: 11638960658106
    spectralType: G
    hue: 45
    isWhite: false
    radius: 2.87
    temperature: 5499
    satellite:
      axialTilt: 0
      semiMajorAxis: 34.44
      eccentricity: 0
      inclination: 0
      orbitalArc: 307
      showOrbit: false
      parentId: Terebellum
  - name: Terebellum B
    description: ''
    tags: []
    solarMass: 1.52
    age: 11638960658106
    spectralType: G
    hue: 45
    isWhite: false
    radius: 2.87
    temperature: 5499
    satellite:
      axialTilt: 0
      semiMajorAxis: 34.44
      eccentricity: 0
      inclination: 0
      orbitalArc: 487
      showOrbit: false
      parentId: Terebellum
planets:
  - name: Terebellum 1
    description: ''
    tags: []
    satellite:
      axialTilt: 36.52
      semiMajorAxis: 256886331
      eccentricity: 0.02
      inclination: 0.75
      orbitalArc: 342
      showOrbit: true
      parentId: Terebellum
    isPlanet:
      age: 8111858014
      classification: H
      radius: 4587
      terranMass: 0.014502806985848044
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 792
    satellites:
      - name: Terebellum 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 23.14
          semiMajorAxis: 263758.3404291273
          eccentricity: 0.01
          inclination: 0.08
          orbitalArc: 350
          showOrbit: true
          parentId: Terebellum 1
        isPlanet:
          age: 404428151
          classification: C
          radius: 786.6313818916169
          terranMass: 0.30000010363000695
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 52
      - name: Terebellum 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 14.29
          semiMajorAxis: 315150.4961563316
          eccentricity: 0.01
          inclination: 1.52
          orbitalArc: 312
          showOrbit: true
          parentId: Terebellum 1
        isPlanet:
          age: 4203328873
          classification: P
          radius: 915.8173860682564
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 126390
        temperature: 268
      - name: Terebellum 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 36.24
          semiMajorAxis: 409715.8084060323
          eccentricity: 0.01
          inclination: 1.1
          orbitalArc: 6
          showOrbit: true
          parentId: Terebellum 1
        isPlanet:
          age: 3298176145
          classification: P
          radius: 898.4995798377901
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 177858
        temperature: 259
commSatellite: null
assets: {}
