apiVersion: solarSystem/v1
kind: solarSystems
name: Fuyue
description: A solar system named Fuyue
position:
  x: 52760517.72358397
  'y': 39859480.841629006
  z: -2336324.3792366385
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Fuyue
stars:
  - name: 'Fuyue '
    description: ''
    tags: []
    solarMass: 1.2
    age: 608350219114
    spectralType: K
    hue: 30
    isWhite: false
    radius: 16.4
    temperature: 4535
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 277
      showOrbit: false
      parentId: Fuyue
planets:
  - name: Fuyue 1
    description: ''
    tags: []
    satellite:
      axialTilt: 31.4
      semiMajorAxis: 484139122.6666673
      eccentricity: 0.01
      inclination: 1.28
      orbitalArc: 304
      showOrbit: true
      parentId: Fuyue
    isPlanet:
      age: 258686269
      classification: D
      radius: 447
      terranMass: 0.028693468087055
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 155
    satellites: []
  - name: Fuyue 2
    description: ''
    tags: []
    satellite:
      axialTilt: 28.62
      semiMajorAxis: 1480671180.2222235
      eccentricity: 0
      inclination: 0.91
      orbitalArc: 67
      showOrbit: true
      parentId: Fuyue
    isPlanet:
      age: 3115679129
      classification: G
      radius: 6429
      terranMass: 0.0014484473187356367
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 507
    satellites:
      - name: Fuyue 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.28
          semiMajorAxis: 671753.9998515811
          eccentricity: 0
          inclination: 1.84
          orbitalArc: 275
          showOrbit: true
          parentId: Fuyue 2
        isPlanet:
          age: 6840923787
          classification: O
          radius: 1351.6177059387949
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 251605557
        temperature: 292
  - name: Fuyue 3
    description: ''
    tags: []
    satellite:
      axialTilt: 12.43
      semiMajorAxis: 2420401277
      eccentricity: 0
      inclination: 0.56
      orbitalArc: 230
      showOrbit: true
      parentId: Fuyue
    isPlanet:
      age: 6328281298
      classification: J
      radius: 39340
      terranMass: 0.17538556996043436
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 268
    satellites:
      - name: Fuyue 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 1.75
          semiMajorAxis: 2092345.1320783792
          eccentricity: 0.01
          inclination: 1.37
          orbitalArc: 341
          showOrbit: true
          parentId: Fuyue 3
        isPlanet:
          age: 872695307
          classification: C
          radius: 6663.519528912036
          terranMass: 1.300000061391653
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 39
commSatellite: null
assets: {}
