apiVersion: solarSystem/v1
kind: solarSystems
name: Baten Kaitos
description: A solar system named Baten Kaitos
position:
  x: -56832640.412040085
  'y': 22174436.897133797
  z: 107496295.99409825
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Baten Kaitos
stars:
  - name: Baten Kaitos A
    description: ''
    tags: []
    solarMass: 2.34
    age: 490302330354
    spectralType: K
    hue: 30
    isWhite: false
    radius: 25
    temperature: 4581
    satellite:
      axialTilt: 0
      semiMajorAxis: 300
      eccentricity: 0
      inclination: 0
      orbitalArc: 139
      showOrbit: false
      parentId: Baten Kaitos
  - name: Baten Kaitos B
    description: ''
    tags: []
    solarMass: 2.34
    age: 490302330354
    spectralType: K
    hue: 30
    isWhite: false
    radius: 25
    temperature: 4581
    satellite:
      axialTilt: 0
      semiMajorAxis: 300
      eccentricity: 0
      inclination: 0
      orbitalArc: 319
      showOrbit: false
      parentId: Baten Kaitos
planets:
  - name: Baten Kaitos 1
    description: ''
    tags: []
    satellite:
      axialTilt: 15.67
      semiMajorAxis: 1191416915.0000005
      eccentricity: 0
      inclination: 1.82
      orbitalArc: 51
      showOrbit: true
      parentId: Baten Kaitos
    isPlanet:
      age: 741307940
      classification: D
      radius: 239
      terranMass: 0.003965761480359351
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 361
    satellites: []
  - name: Baten Kaitos 2
    description: ''
    tags: []
    satellite:
      axialTilt: 20.55
      semiMajorAxis: 3500278250
      eccentricity: 0.02
      inclination: 1.11
      orbitalArc: 187
      showOrbit: true
      parentId: Baten Kaitos
    isPlanet:
      age: 2249153626
      classification: F
      radius: 5216
      terranMass: 0.0012636459031167935
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 625
    satellites:
      - name: Baten Kaitos 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 0.01
          semiMajorAxis: 351225.51291037357
          eccentricity: 0.02
          inclination: 0.05
          orbitalArc: 224
          showOrbit: true
          parentId: Baten Kaitos 2
        isPlanet:
          age: 527371884
          classification: C
          radius: 895.9834513019733
          terranMass: 0.8000001187914599
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 36
commSatellite: null
assets: {}
