apiVersion: solarSystem/v1
kind: solarSystems
name: Chamukuy
description: A solar system named Chamukuy
position:
  x: -73203215.99507049
  'y': -22582016.964019038
  z: 30823549.622556623
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Chamukuy
stars:
  - name: Chamukuy A
    description: ''
    tags: []
    solarMass: 2.86
    age: 2301715031110
    spectralType: A
    hue: 180
    isWhite: true
    radius: 4.4
    temperature: 7800
    satellite:
      axialTilt: 0
      semiMajorAxis: 52.800000000000004
      eccentricity: 0
      inclination: 0
      orbitalArc: 122
      showOrbit: false
      parentId: Chamukuy
  - name: Chamukuy B
    description: ''
    tags: []
    solarMass: 2.86
    age: 2301715031110
    spectralType: A
    hue: 180
    isWhite: true
    radius: 4.4
    temperature: 7800
    satellite:
      axialTilt: 0
      semiMajorAxis: 52.800000000000004
      eccentricity: 0
      inclination: 0
      orbitalArc: 302
      showOrbit: false
      parentId: Chamukuy
planets:
  - name: Chamukuy 1
    description: ''
    tags: []
    satellite:
      axialTilt: 37.43
      semiMajorAxis: 378002854.3333324
      eccentricity: 0.02
      inclination: 0.27
      orbitalArc: 170
      showOrbit: true
      parentId: Chamukuy
    isPlanet:
      age: 167389336
      classification: D
      radius: 122
      terranMass: 0.0030636388849048343
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 387
    satellites: []
  - name: Chamukuy 2
    description: ''
    tags: []
    satellite:
      axialTilt: 12.36
      semiMajorAxis: 777135963.6666652
      eccentricity: 0.02
      inclination: 1.03
      orbitalArc: 274
      showOrbit: true
      parentId: Chamukuy
    isPlanet:
      age: 1881891457
      classification: F
      radius: 5762
      terranMass: 0.018404193380750795
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 609
    satellites: []
  - name: Chamukuy 3
    description: ''
    tags: []
    satellite:
      axialTilt: 28.85
      semiMajorAxis: 1176044207
      eccentricity: 0.01
      inclination: 0.49
      orbitalArc: 323
      showOrbit: true
      parentId: Chamukuy
    isPlanet:
      age: 7939792807
      classification: K
      radius: 4420
      terranMass: 0.02606196927173193
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 14696
    temperature: 155
    satellites: []
commSatellite: null
assets: {}
