apiVersion: solarSystem/v1
kind: solarSystems
name: Alkaid
description: A solar system named Alkaid
position:
  x: 16110111.209332723
  'y': -41438202.41751766
  z: -31775162.848100435
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alkaid
stars:
  - name: Alkaid A
    description: ''
    tags: []
    solarMass: 6.1
    age: 521839834177
    spectralType: B
    hue: 200
    isWhite: false
    radius: 3.4
    temperature: 15540
    satellite:
      axialTilt: 0
      semiMajorAxis: 40.8
      eccentricity: 0
      inclination: 0
      orbitalArc: 310
      showOrbit: false
      parentId: Alkaid
  - name: Alkaid B
    description: ''
    tags: []
    solarMass: 6.1
    age: 521839834177
    spectralType: B
    hue: 200
    isWhite: false
    radius: 3.4
    temperature: 15540
    satellite:
      axialTilt: 0
      semiMajorAxis: 40.8
      eccentricity: 0
      inclination: 0
      orbitalArc: 490
      showOrbit: false
      parentId: Alkaid
planets:
  - name: Alkaid 1
    description: ''
    tags: []
    satellite:
      axialTilt: 34.98
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.96
      orbitalArc: 342
      showOrbit: true
      parentId: Alkaid
    isPlanet:
      age: 956814143
      classification: D
      radius: 481
      terranMass: 0.0017471565498824908
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 265
    satellites: []
commSatellite: null
assets: {}
