apiVersion: solarSystem/v1
kind: solarSystems
name: Haedus
description: A solar system named Haedus
position:
  x: -93508711.5979145
  'y': -84243815.99709721
  z: 22227387.568125848
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Haedus
stars:
  - name: 'Haedus '
    description: ''
    tags: []
    solarMass: 5.6
    age: 201051809653
    spectralType: B
    hue: 200
    isWhite: false
    radius: 3.64
    temperature: 18660
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 28
      showOrbit: false
      parentId: Haedus
planets:
  - name: Haedus 1
    description: ''
    tags: []
    satellite:
      axialTilt: 37.62
      semiMajorAxis: 618129903
      eccentricity: 0.01
      inclination: 1
      orbitalArc: 31
      showOrbit: true
      parentId: Haedus
    isPlanet:
      age: 119859255
      classification: D
      radius: 190
      terranMass: 0.0014769381214187246
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 263
    satellites: []
commSatellite: null
assets: {}
