apiVersion: solarSystem/v1
kind: solarSystems
name: Nusakan
description: A solar system named Nusakan
position:
  x: 40534374.74653712
  'y': -28653930.712995913
  z: -31717702.17327423
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Nusakan
stars:
  - name: Nusakan A
    description: ''
    tags: []
    solarMass: 2.09
    age: 4297268680564
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.63
    temperature: 7980
    satellite:
      axialTilt: 0
      semiMajorAxis: 31.56
      eccentricity: 0
      inclination: 0
      orbitalArc: 205
      showOrbit: false
      parentId: Nusakan
  - name: Nusakan B
    description: ''
    tags: []
    solarMass: 2.09
    age: 4297268680564
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.63
    temperature: 7980
    satellite:
      axialTilt: 0
      semiMajorAxis: 31.56
      eccentricity: 0
      inclination: 0
      orbitalArc: 385
      showOrbit: false
      parentId: Nusakan
planets:
  - name: Nusakan 1
    description: ''
    tags: []
    satellite:
      axialTilt: 4.47
      semiMajorAxis: 568005552.6666667
      eccentricity: 0.01
      inclination: 0.34
      orbitalArc: 137
      showOrbit: true
      parentId: Nusakan
    isPlanet:
      age: 6622202116
      classification: K
      radius: 2905
      terranMass: 0.010234224518736392
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 1528
    temperature: 278
    satellites:
      - name: Nusakan 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 14.82
          semiMajorAxis: 54965.75289879786
          eccentricity: 0.01
          inclination: 1.54
          orbitalArc: 19
          showOrbit: true
          parentId: Nusakan 1
        isPlanet:
          age: 3512722827
          classification: P
          radius: 145.79775304720917
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 140447
        temperature: 256
  - name: Nusakan 2
    description: ''
    tags: []
    satellite:
      axialTilt: 4.7
      semiMajorAxis: 1398901172.2222219
      eccentricity: 0.01
      inclination: 1.26
      orbitalArc: 62
      showOrbit: true
      parentId: Nusakan
    isPlanet:
      age: 526586965
      classification: E
      radius: 7223
      terranMass: 0.022019529900229734
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 1240
    satellites:
      - name: Nusakan 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 9.76
          semiMajorAxis: 509295.3571996562
          eccentricity: 0.01
          inclination: 0.21
          orbitalArc: 298
          showOrbit: true
          parentId: Nusakan 2
        isPlanet:
          age: 9041129719
          classification: P
          radius: 1157.4894481810368
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 83714
        temperature: 256
  - name: Nusakan 3
    description: ''
    tags: []
    satellite:
      axialTilt: 17.73
      semiMajorAxis: 2646990784.2222214
      eccentricity: 0.02
      inclination: 0.14
      orbitalArc: 145
      showOrbit: true
      parentId: Nusakan
    isPlanet:
      age: 840529144
      classification: C
      radius: 1639
      terranMass: 0.02521424127108418
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 46
    satellites:
      - name: Nusakan 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.43
          semiMajorAxis: 183693.75560991955
          eccentricity: 0
          inclination: 1.75
          orbitalArc: 332
          showOrbit: true
          parentId: Nusakan 3
        isPlanet:
          age: 5924144213
          classification: K
          radius: 370.3503137296765
          terranMass: 2.1000000166414017
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 47629
        temperature: 173
  - name: Nusakan 4
    description: ''
    tags: []
    satellite:
      axialTilt: 33.03
      semiMajorAxis: 3790787454
      eccentricity: 0.02
      inclination: 1.06
      orbitalArc: 96
      showOrbit: true
      parentId: Nusakan
    isPlanet:
      age: 7549228660
      classification: J
      radius: 31846
      terranMass: 1.2139989722319877
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 156
    satellites:
      - name: Nusakan 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 27.29
          semiMajorAxis: 3023827.209970367
          eccentricity: 0.02
          inclination: 1.72
          orbitalArc: 357
          showOrbit: true
          parentId: Nusakan 4
        isPlanet:
          age: 2492049832
          classification: F
          radius: 6502.854214990037
          terranMass: 0.9000000380559777
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 654
commSatellite: null
assets: {}
