apiVersion: solarSystem/v1
kind: solarSystems
name: Zubenelgenubi
description: A solar system named Zubenelgenubi
position:
  x: 25376303.553547177
  'y': 10755369.466183444
  z: -27481131.714063708
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Zubenelgenubi
stars:
  - name: Zubenelgenubi A
    description: ''
    tags: []
    solarMass: 1.36
    age: 19776020158149
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.4
    temperature: 6707
    satellite:
      axialTilt: 0
      semiMajorAxis: 16.799999999999997
      eccentricity: 0
      inclination: 0
      orbitalArc: 200
      showOrbit: false
      parentId: Zubenelgenubi
  - name: Zubenelgenubi B
    description: ''
    tags: []
    solarMass: 1.36
    age: 19776020158149
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.4
    temperature: 6707
    satellite:
      axialTilt: 0
      semiMajorAxis: 16.799999999999997
      eccentricity: 0
      inclination: 0
      orbitalArc: 380
      showOrbit: false
      parentId: Zubenelgenubi
planets:
  - name: Zubenelgenubi 1
    description: ''
    tags: []
    satellite:
      axialTilt: 36.93
      semiMajorAxis: 129917252
      eccentricity: 0.01
      inclination: 0.09
      orbitalArc: 132
      showOrbit: true
      parentId: Zubenelgenubi
    isPlanet:
      age: 5207591871
      classification: L
      radius: 4385
      terranMass: 0.03305974463934301
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 46295
    temperature: 287
    satellites:
      - name: Zubenelgenubi 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 20.24
          semiMajorAxis: 265967.08014662925
          eccentricity: 0.01
          inclination: 0.26
          orbitalArc: 41
          showOrbit: true
          parentId: Zubenelgenubi 1
        isPlanet:
          age: 4390022873
          classification: K
          radius: 753.4478191122641
          terranMass: 1.5000000044656638
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 32404
        temperature: 282
  - name: Zubenelgenubi 2
    description: ''
    tags: []
    satellite:
      axialTilt: 23.38
      semiMajorAxis: 256713301.99999887
      eccentricity: 0.01
      inclination: 1.56
      orbitalArc: 306
      showOrbit: true
      parentId: Zubenelgenubi
    isPlanet:
      age: 4600417344
      classification: L
      radius: 3551
      terranMass: 0.0007518534743822036
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 7958
    temperature: 195
    satellites:
      - name: Zubenelgenubi 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.99
          semiMajorAxis: 245032.61181065658
          eccentricity: 0.01
          inclination: 0.68
          orbitalArc: 188
          showOrbit: true
          parentId: Zubenelgenubi 2
        isPlanet:
          age: 1816768064
          classification: A
          radius: 621.9101822605497
          terranMass: 1.8000000380812478
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1486
  - name: Zubenelgenubi 3
    description: ''
    tags: []
    satellite:
      axialTilt: 16.73
      semiMajorAxis: 1604238398.6666658
      eccentricity: 0.01
      inclination: 0.27
      orbitalArc: 114
      showOrbit: true
      parentId: Zubenelgenubi
    isPlanet:
      age: 8369503855
      classification: K
      radius: 2844
      terranMass: 0.01542378969796089
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 22413
    temperature: 286
    satellites:
      - name: Zubenelgenubi 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 20.64
          semiMajorAxis: 115654.91095426433
          eccentricity: 0
          inclination: 1.4
          orbitalArc: 245
          showOrbit: true
          parentId: Zubenelgenubi 3
        isPlanet:
          age: 9134969542
          classification: M
          radius: 160.57661944524773
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial3.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 4739262003
        temperature: 299
      - name: Zubenelgenubi 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 14.97
          semiMajorAxis: 279587.83166387485
          eccentricity: 0
          inclination: 1.82
          orbitalArc: 182
          showOrbit: true
          parentId: Zubenelgenubi 3
        isPlanet:
          age: 865640012
          classification: D
          radius: 629.7023235672857
          terranMass: 0.09999973267077132
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 206
  - name: Zubenelgenubi 4
    description: ''
    tags: []
    satellite:
      axialTilt: 26.82
      semiMajorAxis: 3260832163
      eccentricity: 0
      inclination: 1.57
      orbitalArc: 120
      showOrbit: true
      parentId: Zubenelgenubi
    isPlanet:
      age: 9398019920
      classification: J
      radius: 69287
      terranMass: 0.15953517894715424
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 305
    satellites:
      - name: Zubenelgenubi 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 29.72
          semiMajorAxis: 2247485.9438259127
          eccentricity: 0
          inclination: 0.29
          orbitalArc: 129
          showOrbit: true
          parentId: Zubenelgenubi 4
        isPlanet:
          age: 408947738
          classification: D
          radius: 7135.4478642500935
          terranMass: 0.10999993970238296
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 228
      - name: Zubenelgenubi 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 34.07
          semiMajorAxis: 3203490.1650734846
          eccentricity: 0.01
          inclination: 0.9
          orbitalArc: 47
          showOrbit: true
          parentId: Zubenelgenubi 4
        isPlanet:
          age: 873747285
          classification: C
          radius: 7652.355505168323
          terranMass: 1.1000000070657134
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 43
      - name: Zubenelgenubi 4c
        description: ''
        tags: []
        satellite:
          axialTilt: 19.4
          semiMajorAxis: 5109740.759928582
          eccentricity: 0.01
          inclination: 0.77
          orbitalArc: 263
          showOrbit: true
          parentId: Zubenelgenubi 4
        isPlanet:
          age: 986615335
          classification: D
          radius: 11994.696619550663
          terranMass: 0.7299997819340034
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 301
commSatellite: null
assets: {}
