apiVersion: solarSystem/v1
kind: solarSystems
name: Kaus Borealis
description: A solar system named Kaus Borealis
position:
  x: 36871247.68417239
  'y': 17656203.969915
  z: 4522430.575515044
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Kaus Borealis
stars:
  - name: Kaus Borealis A
    description: ''
    tags: []
    solarMass: 1.79
    age: 1582736031820
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.234
    temperature: 4768
    satellite:
      axialTilt: 0
      semiMajorAxis: 134.808
      eccentricity: 0
      inclination: 0
      orbitalArc: 220
      showOrbit: false
      parentId: Kaus Borealis
  - name: Kaus Borealis B
    description: ''
    tags: []
    solarMass: 1.79
    age: 1582736031820
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.234
    temperature: 4768
    satellite:
      axialTilt: 0
      semiMajorAxis: 134.808
      eccentricity: 0
      inclination: 0
      orbitalArc: 400
      showOrbit: false
      parentId: Kaus Borealis
planets:
  - name: Kaus Borealis 1
    description: ''
    tags: []
    satellite:
      axialTilt: 2.82
      semiMajorAxis: 674783570.0000005
      eccentricity: 0.01
      inclination: 1.44
      orbitalArc: 47
      showOrbit: true
      parentId: Kaus Borealis
    isPlanet:
      age: 1685473746
      classification: E
      radius: 5158
      terranMass: 0.015036845776108079
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 1433
    satellites: []
  - name: Kaus Borealis 2
    description: ''
    tags: []
    satellite:
      axialTilt: 8.59
      semiMajorAxis: 1807946064.000001
      eccentricity: 0.01
      inclination: 0.01
      orbitalArc: 196
      showOrbit: true
      parentId: Kaus Borealis
    isPlanet:
      age: 608391644
      classification: C
      radius: 3822
      terranMass: 0.0053297895451543025
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 47
    satellites:
      - name: Kaus Borealis 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 4.62
          semiMajorAxis: 189473.50739600186
          eccentricity: 0
          inclination: 1.82
          orbitalArc: 242
          showOrbit: true
          parentId: Kaus Borealis 2
        isPlanet:
          age: 4945703933
          classification: M
          radius: 588.4270416024902
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial1.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 47026434
        temperature: 298
  - name: Kaus Borealis 3
    description: ''
    tags: []
    satellite:
      axialTilt: 38.16
      semiMajorAxis: 2429317355
      eccentricity: 0.01
      inclination: 1.59
      orbitalArc: 233
      showOrbit: true
      parentId: Kaus Borealis
    isPlanet:
      age: 877902786
      classification: C
      radius: 1313
      terranMass: 0.00035284886651881336
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 41
    satellites: []
commSatellite: null
assets: {}
