apiVersion: solarSystem/v1
kind: solarSystems
name: Alterf
description: A solar system named Alterf
position:
  x: -96037924.86776105
  'y': -67523387.23729178
  z: -127123725.05163077
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alterf
stars:
  - name: Alterf A
    description: ''
    tags: []
    solarMass: 1.29
    age: 124010020187
    spectralType: K
    hue: 30
    isWhite: false
    radius: 44.93
    temperature: 4152
    satellite:
      axialTilt: 0
      semiMajorAxis: 539.16
      eccentricity: 0
      inclination: 0
      orbitalArc: 129
      showOrbit: false
      parentId: Alterf
  - name: Alterf B
    description: ''
    tags: []
    solarMass: 1.29
    age: 124010020187
    spectralType: K
    hue: 30
    isWhite: false
    radius: 44.93
    temperature: 4152
    satellite:
      axialTilt: 0
      semiMajorAxis: 539.16
      eccentricity: 0
      inclination: 0
      orbitalArc: 309
      showOrbit: false
      parentId: Alterf
planets:
  - name: Alterf 1
    description: ''
    tags: []
    satellite:
      axialTilt: 24.66
      semiMajorAxis: 2543573660.333333
      eccentricity: 0.02
      inclination: 1.53
      orbitalArc: 278
      showOrbit: true
      parentId: Alterf
    isPlanet:
      age: 4006651706
      classification: B
      radius: 1553
      terranMass: 0.00663554118101128
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 547
    satellites: []
  - name: Alterf 2
    description: ''
    tags: []
    satellite:
      axialTilt: 18.67
      semiMajorAxis: 3305100528.777778
      eccentricity: 0.01
      inclination: 1.26
      orbitalArc: 276
      showOrbit: true
      parentId: Alterf
    isPlanet:
      age: 694002100
      classification: C
      radius: 1264
      terranMass: 0.010440129380649062
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 41
    satellites:
      - name: Alterf 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.27
          semiMajorAxis: 31431.426277981533
          eccentricity: 0.02
          inclination: 0.18
          orbitalArc: 94
          showOrbit: true
          parentId: Alterf 2
        isPlanet:
          age: 531058770
          classification: D
          radius: 124.44625206264814
          terranMass: 0.5899998380354827
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 150
      - name: Alterf 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 26.99
          semiMajorAxis: 50221.99032530943
          eccentricity: 0.02
          inclination: 0.32
          orbitalArc: 105
          showOrbit: true
          parentId: Alterf 2
        isPlanet:
          age: 3277657688
          classification: P
          radius: 195.41630476774097
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 20843
        temperature: 268
  - name: Alterf 3
    description: ''
    tags: []
    satellite:
      axialTilt: 39.72
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.49
      orbitalArc: 36
      showOrbit: true
      parentId: Alterf
    isPlanet:
      age: 307577220
      classification: A
      radius: 3407
      terranMass: 0.025815237897697026
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 1749
    satellites:
      - name: Alterf 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.74
          semiMajorAxis: 82146.85785308786
          eccentricity: 0.01
          inclination: 1.69
          orbitalArc: 49
          showOrbit: true
          parentId: Alterf 3
        isPlanet:
          age: 6027426644
          classification: M
          radius: 172.9407533749218
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 8889323462
        temperature: 289
commSatellite: null
assets: {}
