apiVersion: solarSystem/v1
kind: solarSystems
name: Rigel
description: A solar system named Rigel
position:
  x: -438919855.47185534
  'y': 64527517.08995609
  z: 88227027.75301363
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Rigel
stars:
  - name: Rigel A
    description: ''
    tags: []
    solarMass: 21
    age: 10317718112
    spectralType: B
    hue: 200
    isWhite: false
    radius: 74
    temperature: 12100
    satellite:
      axialTilt: 0
      semiMajorAxis: 888
      eccentricity: 0
      inclination: 0
      orbitalArc: 193
      showOrbit: false
      parentId: Rigel
  - name: Rigel B
    description: ''
    tags: []
    solarMass: 21
    age: 10317718112
    spectralType: B
    hue: 200
    isWhite: false
    radius: 74
    temperature: 12100
    satellite:
      axialTilt: 0
      semiMajorAxis: 888
      eccentricity: 0
      inclination: 0
      orbitalArc: 373
      showOrbit: false
      parentId: Rigel
planets:
  - name: Rigel 1
    description: ''
    tags: []
    satellite:
      axialTilt: 29.59
      semiMajorAxis: 1600861452.3333333
      eccentricity: 0
      inclination: 1.18
      orbitalArc: 191
      showOrbit: true
      parentId: Rigel
    isPlanet:
      age: 947737261
      classification: D
      radius: 98
      terranMass: 0.004975440605130111
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 387
    satellites: []
  - name: Rigel 2
    description: ''
    tags: []
    satellite:
      axialTilt: 1.86
      semiMajorAxis: 2714261288.8888884
      eccentricity: 0.01
      inclination: 1.64
      orbitalArc: 16
      showOrbit: true
      parentId: Rigel
    isPlanet:
      age: 264069224
      classification: D
      radius: 169
      terranMass: 0.018439471687185405
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 342
    satellites: []
  - name: Rigel 3
    description: ''
    tags: []
    satellite:
      axialTilt: 5.72
      semiMajorAxis: 16536266484.925926
      eccentricity: 0.02
      inclination: 1.59
      orbitalArc: 106
      showOrbit: true
      parentId: Rigel
    isPlanet:
      age: 37424551
      classification: D
      radius: 346
      terranMass: 0.0041704744872202585
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 280
    satellites: []
  - name: Rigel 4
    description: ''
    tags: []
    satellite:
      axialTilt: 30.27
      semiMajorAxis: 32568576156
      eccentricity: 0.02
      inclination: 1.23
      orbitalArc: 350
      showOrbit: true
      parentId: Rigel
    isPlanet:
      age: 9893860517
      classification: K
      radius: 3186
      terranMass: 0.015536216488260306
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 41795
    temperature: 166
    satellites: []
commSatellite: null
assets: {}
