apiVersion: solarSystem/v1
kind: solarSystems
name: Adhil
description: A solar system named Adhil
position:
  x: -27892196.322500695
  'y': -80807756.94968581
  z: 74264698.88154756
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Adhil
stars:
  - name: 'Adhil '
    description: ''
    tags: []
    solarMass: 2.5
    age: 2623071644293
    spectralType: K
    hue: 30
    isWhite: false
    radius: 10
    temperature: 4842
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 327
      showOrbit: false
      parentId: Adhil
planets:
  - name: Adhil 1
    description: ''
    tags: []
    satellite:
      axialTilt: 29.13
      semiMajorAxis: 464761339
      eccentricity: 0.01
      inclination: 1.5
      orbitalArc: 240
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 7787129505
      classification: H
      radius: 4467
      terranMass: 0.03216913917128241
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 547
    satellites:
      - name: Adhil 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 16.67
          semiMajorAxis: 229657.179776952
          eccentricity: 0
          inclination: 1.77
          orbitalArc: 355
          showOrbit: true
          parentId: Adhil 1
        isPlanet:
          age: 662347133
          classification: D
          radius: 504.74105445483957
          terranMass: 0.10999984957145979
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 383
  - name: Adhil 2
    description: ''
    tags: []
    satellite:
      axialTilt: 31.85
      semiMajorAxis: 715008445
      eccentricity: 0
      inclination: 1.9
      orbitalArc: 89
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 6775520619
      classification: P
      radius: 5784
      terranMass: 0.002301155385747821
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 145022
    temperature: 257
    satellites: []
  - name: Adhil 3
    description: ''
    tags: []
    satellite:
      axialTilt: 17.61
      semiMajorAxis: 1056079633.3333313
      eccentricity: 0.01
      inclination: 0.04
      orbitalArc: 193
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 738756209
      classification: C
      radius: 4514
      terranMass: 0.019539461863303204
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 51
    satellites: []
  - name: Adhil 4
    description: ''
    tags: []
    satellite:
      axialTilt: 36.7
      semiMajorAxis: 1498074893.222216
      eccentricity: 0.01
      inclination: 1.9
      orbitalArc: 243
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 9008751124
      classification: J
      radius: 42957
      terranMass: 0.2620324363762123
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 259
    satellites:
      - name: Adhil 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.71
          semiMajorAxis: 1803777.7781297513
          eccentricity: 0.01
          inclination: 0.79
          orbitalArc: 336
          showOrbit: true
          parentId: Adhil 4
        isPlanet:
          age: 862145026
          classification: D
          radius: 3862.479182290688
          terranMass: 0.5899999599964698
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 166
  - name: Adhil 5
    description: ''
    tags: []
    satellite:
      axialTilt: 38.22
      semiMajorAxis: 1704289575.6295865
      eccentricity: 0.02
      inclination: 1.55
      orbitalArc: 178
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 9553568935
      classification: J
      radius: 59624
      terranMass: 0.03637547206747706
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 318
    satellites:
      - name: Adhil 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 15.79
          semiMajorAxis: 3397386.8801757307
          eccentricity: 0.02
          inclination: 1.56
          orbitalArc: 88
          showOrbit: true
          parentId: Adhil 5
        isPlanet:
          age: 6872830174
          classification: P
          radius: 12220.81611574004
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 195790
        temperature: 263
  - name: Adhil 6
    description: ''
    tags: []
    satellite:
      axialTilt: 37.85
      semiMajorAxis: 1918574977.1479301
      eccentricity: 0.02
      inclination: 1.66
      orbitalArc: 293
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 5579887315
      classification: J
      radius: 31886
      terranMass: 1.3796666979649261
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 246
    satellites: []
  - name: Adhil 7
    description: ''
    tags: []
    satellite:
      axialTilt: 7.08
      semiMajorAxis: 2194204994.011837
      eccentricity: 0.01
      inclination: 1.41
      orbitalArc: 333
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 2045650790
      classification: J
      radius: 54288
      terranMass: 0.2275474375294399
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 236
    satellites: []
  - name: Adhil 8
    description: ''
    tags: []
    satellite:
      axialTilt: 31.99
      semiMajorAxis: 3229964032.6942863
      eccentricity: 0
      inclination: 0.42
      orbitalArc: 319
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 776955681
      classification: D
      radius: 434
      terranMass: 0.021317106814092594
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 212
    satellites: []
  - name: Adhil 9
    description: ''
    tags: []
    satellite:
      axialTilt: 37.02
      semiMajorAxis: 3777342435
      eccentricity: 0.01
      inclination: 1.05
      orbitalArc: 223
      showOrbit: true
      parentId: Adhil
    isPlanet:
      age: 828128082
      classification: D
      radius: 69
      terranMass: 0.011894594288554144
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 325
    satellites: []
commSatellite: null
assets: {}
