apiVersion: solarSystem/v1
kind: solarSystems
name: Grumium
description: A solar system named Grumium
position:
  x: 32180235.793312818
  'y': -49332568.14670695
  z: -908876.7175482954
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Grumium
stars:
  - name: Grumium A
    description: ''
    tags: []
    solarMass: 1.45
    age: 1594377810023
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.56
    temperature: 4451
    satellite:
      axialTilt: 0
      semiMajorAxis: 138.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 260
      showOrbit: false
      parentId: Grumium
  - name: Grumium B
    description: ''
    tags: []
    solarMass: 1.45
    age: 1594377810023
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.56
    temperature: 4451
    satellite:
      axialTilt: 0
      semiMajorAxis: 138.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 440
      showOrbit: false
      parentId: Grumium
planets:
  - name: Grumium 1
    description: ''
    tags: []
    satellite:
      axialTilt: 37.25
      semiMajorAxis: 441526678.6666664
      eccentricity: 0
      inclination: 1.44
      orbitalArc: 347
      showOrbit: true
      parentId: Grumium
    isPlanet:
      age: 6480150155
      classification: P
      radius: 6991
      terranMass: 0.00646538726030043
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 87405
    temperature: 265
    satellites: []
  - name: Grumium 2
    description: ''
    tags: []
    satellite:
      axialTilt: 9.71
      semiMajorAxis: 601050008.9999986
      eccentricity: 0.02
      inclination: 0.57
      orbitalArc: 161
      showOrbit: true
      parentId: Grumium
    isPlanet:
      age: 6933253608
      classification: P
      radius: 5466
      terranMass: 0.007863252569307397
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 165002
    temperature: 270
    satellites: []
  - name: Grumium 3
    description: ''
    tags: []
    satellite:
      axialTilt: 31.95
      semiMajorAxis: 785457628.6666566
      eccentricity: 0.02
      inclination: 1.9
      orbitalArc: 57
      showOrbit: true
      parentId: Grumium
    isPlanet:
      age: 3938612632
      classification: 'N'
      radius: 7277
      terranMass: 0.01813940812266418
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 563361376
    temperature: 701
    satellites: []
  - name: Grumium 4
    description: ''
    tags: []
    satellite:
      axialTilt: 8.13
      semiMajorAxis: 1001538856
      eccentricity: 0.02
      inclination: 1.97
      orbitalArc: 50
      showOrbit: true
      parentId: Grumium
    isPlanet:
      age: 8666525148
      classification: P
      radius: 6587
      terranMass: 0.00664515256745395
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 29512
    temperature: 261
    satellites:
      - name: Grumium 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.86
          semiMajorAxis: 86481.1902483522
          eccentricity: 0
          inclination: 1.32
          orbitalArc: 274
          showOrbit: true
          parentId: Grumium 4
        isPlanet:
          age: 6455965519
          classification: P
          radius: 828.304518251739
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 74106
        temperature: 267
      - name: Grumium 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 31.73
          semiMajorAxis: 252200.99433801963
          eccentricity: 0.01
          inclination: 1.56
          orbitalArc: 113
          showOrbit: true
          parentId: Grumium 4
        isPlanet:
          age: 6458964927
          classification: B
          radius: 927.2095380074252
          terranMass: 0.7000004742163547
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 231
commSatellite: null
assets: {}
