apiVersion: solarSystem/v1
kind: solarSystems
name: Izar
description: A solar system named Izar
position:
  x: 62679836.74026925
  'y': -48595682.16970053
  z: -71480801.7294787
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Izar
stars:
  - name: Izar A
    description: ''
    tags: []
    solarMass: 4.6
    age: 366875207469
    spectralType: K
    hue: 30
    isWhite: false
    radius: 37.61
    temperature: 4755
    satellite:
      axialTilt: 0
      semiMajorAxis: 451.32
      eccentricity: 0
      inclination: 0
      orbitalArc: 49
      showOrbit: false
      parentId: Izar
  - name: Izar B
    description: ''
    tags: []
    solarMass: 4.6
    age: 366875207469
    spectralType: K
    hue: 30
    isWhite: false
    radius: 37.61
    temperature: 4755
    satellite:
      axialTilt: 0
      semiMajorAxis: 451.32
      eccentricity: 0
      inclination: 0
      orbitalArc: 229
      showOrbit: false
      parentId: Izar
planets:
  - name: Izar 1
    description: ''
    tags: []
    satellite:
      axialTilt: 23.03
      semiMajorAxis: 2060722346.3333342
      eccentricity: 0
      inclination: 0.81
      orbitalArc: 316
      showOrbit: true
      parentId: Izar
    isPlanet:
      age: 6939435549
      classification: O
      radius: 5141
      terranMass: 0.022704367674934764
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 496557138
    temperature: 302
    satellites:
      - name: Izar 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 32.69
          semiMajorAxis: 338815.0478129842
          eccentricity: 0.02
          inclination: 0.25
          orbitalArc: 306
          showOrbit: true
          parentId: Izar 1
        isPlanet:
          age: 6494890753
          classification: P
          radius: 898.7136546763506
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 63650
        temperature: 257
  - name: Izar 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.26
      semiMajorAxis: 3021951305.222223
      eccentricity: 0.01
      inclination: 0.97
      orbitalArc: 248
      showOrbit: true
      parentId: Izar
    isPlanet:
      age: 777687371
      classification: E
      radius: 5699
      terranMass: 0.04093443068033787
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 1335
    satellites: []
  - name: Izar 3
    description: ''
    tags: []
    satellite:
      axialTilt: 21.67
      semiMajorAxis: 3379826070.407412
      eccentricity: 0.01
      inclination: 0.68
      orbitalArc: 19
      showOrbit: true
      parentId: Izar
    isPlanet:
      age: 1870704383
      classification: A
      radius: 816
      terranMass: 0.022932828888185118
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 1760
    satellites:
      - name: Izar 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 20.03
          semiMajorAxis: 52983.775404039436
          eccentricity: 0.02
          inclination: 0.05
          orbitalArc: 18
          showOrbit: true
          parentId: Izar 3
        isPlanet:
          age: 6486879657
          classification: L
          radius: 82.7350987558102
          terranMass: 0.10000015530383824
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 40011
        temperature: 245
      - name: Izar 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 17.34
          semiMajorAxis: 82715.07216003981
          eccentricity: 0.02
          inclination: 1.98
          orbitalArc: 100
          showOrbit: true
          parentId: Izar 3
        isPlanet:
          age: 3425173913
          classification: G
          radius: 194.1668360564315
          terranMass: 1.5
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 503
  - name: Izar 4
    description: ''
    tags: []
    satellite:
      axialTilt: 19.44
      semiMajorAxis: 3723501330.0494137
      eccentricity: 0.02
      inclination: 0.32
      orbitalArc: 20
      showOrbit: true
      parentId: Izar
    isPlanet:
      age: 8350529144
      classification: O
      radius: 5817
      terranMass: 0.014019001357145375
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 569600353
    temperature: 300
    satellites:
      - name: Izar 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.03
          semiMajorAxis: 76573.4115244518
          eccentricity: 0.01
          inclination: 1.45
          orbitalArc: 226
          showOrbit: true
          parentId: Izar 4
        isPlanet:
          age: 8010074201
          classification: P
          radius: 386.2448063004518
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 29541
        temperature: 257
      - name: Izar 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 37.22
          semiMajorAxis: 120161.50984591604
          eccentricity: 0
          inclination: 0.91
          orbitalArc: 71
          showOrbit: true
          parentId: Izar 4
        isPlanet:
          age: 5230376629
          classification: P
          radius: 299.65463801974073
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 36496
        temperature: 262
  - name: Izar 5
    description: ''
    tags: []
    satellite:
      axialTilt: 38.21
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 1.78
      orbitalArc: 70
      showOrbit: true
      parentId: Izar
    isPlanet:
      age: 608777153
      classification: C
      radius: 3766
      terranMass: 0.013271728671444164
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 33
    satellites: []
commSatellite: null
assets: {}
