apiVersion: solarSystem/v1
kind: solarSystems
name: Hassaleh
description: A solar system named Hassaleh
position:
  x: -207633368.9065423
  'y': -140990594.65495688
  z: 58564843.648056686
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Hassaleh
stars:
  - name: Hassaleh A
    description: ''
    tags: []
    solarMass: 7.1
    age: 95018974218
    spectralType: K
    hue: 30
    isWhite: false
    radius: 126
    temperature: 4059
    satellite:
      axialTilt: 0
      semiMajorAxis: 1512
      eccentricity: 0
      inclination: 0
      orbitalArc: 288
      showOrbit: false
      parentId: Hassaleh
  - name: Hassaleh B
    description: ''
    tags: []
    solarMass: 7.1
    age: 95018974218
    spectralType: K
    hue: 30
    isWhite: false
    radius: 126
    temperature: 4059
    satellite:
      axialTilt: 0
      semiMajorAxis: 1512
      eccentricity: 0
      inclination: 0
      orbitalArc: 468
      showOrbit: false
      parentId: Hassaleh
planets:
  - name: Hassaleh 1
    description: ''
    tags: []
    satellite:
      axialTilt: 13.71
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 1.64
      orbitalArc: 170
      showOrbit: true
      parentId: Hassaleh
    isPlanet:
      age: 4924941926
      classification: J
      radius: 37990
      terranMass: 0.20453462993133223
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 248
    satellites: []
commSatellite: null
assets: {}
