apiVersion: solarSystem/v1
kind: solarSystems
name: Tejat
description: A solar system named Tejat
position:
  x: -111191123.37946065
  'y': -46320014.96648977
  z: -11176973.998257848
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tejat
stars:
  - name: Tejat A
    description: ''
    tags: []
    radius: 107.7
    temperature: 3643
    solarMass: 1.9
    age: 53635803847
    spectralType: M
    hue: 0
    isWhite: false
    satellite:
      orbitalArc: 49
      semiMajorAxis: 1292.4
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Tejat
  - name: Tejat B
    description: ''
    tags: []
    radius: 107.7
    temperature: 3643
    solarMass: 1.9
    age: 53635803847
    spectralType: M
    hue: 0
    isWhite: false
    satellite:
      orbitalArc: 229
      semiMajorAxis: 1292.4
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Tejat
planets:
  - name: Tejat 1
    description: ''
    tags: []
    isPlanet:
      radius: 141
      age: 764688829
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
      terranMass: 0.0021523001488641933
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 381
    satellite:
      semiMajorAxis: 1655638857.0000002
      eccentricity: 0.02
      inclination: 0.89
      orbitalArc: 36
      axialTilt: 0.42
      parentId: Tejat
      showOrbit: true
    satellites: []
  - name: Tejat 2
    description: ''
    tags: []
    isPlanet:
      radius: 4300
      age: 8034820901
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
      terranMass: 0.010400476192913385
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      classification: H
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
    population: 0
    temperature: 770
    satellite:
      semiMajorAxis: 2690742263.0000014
      eccentricity: 0.01
      inclination: 0.44
      orbitalArc: 10
      axialTilt: 1.18
      parentId: Tejat
      showOrbit: true
    satellites:
      - name: Tejat 2a
        description: ''
        tags: []
        isPlanet:
          radius: 614.5397590402373
          age: 680523859
          ringMapAsset: null
          terranMass: 1.1999999008780546
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: D
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 243
        satellite:
          semiMajorAxis: 154864.0192781398
          eccentricity: 0.01
          inclination: 1.96
          orbitalArc: 113
          axialTilt: 2.62
          parentId: Tejat 2
          showOrbit: true
        satellites: []
  - name: Tejat 3
    description: ''
    tags: []
    isPlanet:
      radius: 2000
      age: 259699205
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
      terranMass: 0.0017546776408428754
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      classification: C
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 38
    satellite:
      semiMajorAxis: 3210221324.0000014
      eccentricity: 0.01
      inclination: 0.5
      orbitalArc: 105
      axialTilt: 17.76
      parentId: Tejat
      showOrbit: true
    satellites:
      - name: Tejat 3a
        description: ''
        tags: []
        isPlanet:
          radius: 213.26087562210412
          age: 3138816059
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 92368
        temperature: 260
        satellite:
          semiMajorAxis: 51503.04411324323
          eccentricity: 0.02
          inclination: 0.59
          orbitalArc: 312
          axialTilt: 14.62
          parentId: Tejat 3
          showOrbit: true
        satellites: []
      - name: Tejat 3b
        description: ''
        tags: []
        isPlanet:
          radius: 275.1832098642325
          age: 210203118
          ringMapAsset: null
          terranMass: 1.2999999080528954
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          classification: D
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 146
        satellite:
          semiMajorAxis: 81179.04690994858
          eccentricity: 0.01
          inclination: 0.2
          orbitalArc: 271
          axialTilt: 27.33
          parentId: Tejat 3
          showOrbit: true
        satellites: []
  - name: Tejat 4
    description: ''
    tags: []
    isPlanet:
      radius: 172
      age: 945581395
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.006666889950122608
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 299
    satellite:
      semiMajorAxis: 3665092754.6666718
      eccentricity: 0.02
      inclination: 1.35
      orbitalArc: 145
      axialTilt: 26.83
      parentId: Tejat
      showOrbit: true
    satellites: []
  - name: Tejat 5
    description: ''
    tags: []
    isPlanet:
      radius: 7124
      age: 3920004555
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
      terranMass: 0.005518651122231653
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
      classification: G
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
    population: 0
    temperature: 454
    satellite:
      semiMajorAxis: 3949532265.6666903
      eccentricity: 0
      inclination: 1.5
      orbitalArc: 130
      axialTilt: 0.62
      parentId: Tejat
      showOrbit: true
    satellites: []
  - name: Tejat 6
    description: ''
    tags: []
    isPlanet:
      radius: 3504
      age: 6883962458
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
      terranMass: 0.03550113339444828
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      classification: L
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
    population: 35876
    temperature: 279
    satellite:
      semiMajorAxis: 4195588459.777843
      eccentricity: 0
      inclination: 1.03
      orbitalArc: 130
      axialTilt: 39.6
      parentId: Tejat
      showOrbit: true
    satellites:
      - name: Tejat 6a
        description: ''
        tags: []
        isPlanet:
          radius: 187.47427725518924
          age: 7125519262
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
          classification: M
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
        population: 254314936
        temperature: 296
        satellite:
          semiMajorAxis: 105222.3788736338
          eccentricity: 0
          inclination: 0.99
          orbitalArc: 85
          axialTilt: 5.62
          parentId: Tejat 6
          showOrbit: true
        satellites: []
      - name: Tejat 6b
        description: ''
        tags: []
        isPlanet:
          radius: 684.8567370517313
          age: 8006609745
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 129712
        temperature: 267
        satellite:
          semiMajorAxis: 302021.8210398135
          eccentricity: 0
          inclination: 0.9
          orbitalArc: 180
          axialTilt: 38.46
          parentId: Tejat 6
          showOrbit: true
        satellites: []
  - name: Tejat 7
    description: ''
    tags: []
    isPlanet:
      radius: 5630
      age: 4887246912
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
      terranMass: 0.0048771786718576175
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      classification: O
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
    population: 372568558
    temperature: 300
    satellite:
      semiMajorAxis: 4394115621
      eccentricity: 0.02
      inclination: 0.41
      orbitalArc: 35
      axialTilt: 13.71
      parentId: Tejat
      showOrbit: true
    satellites:
      - name: Tejat 7a
        description: ''
        tags: []
        isPlanet:
          radius: 1055.8666013775783
          age: 900408304
          ringMapAsset: null
          terranMass: 0.9000000130087041
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          classification: C
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 40
        satellite:
          semiMajorAxis: 312305.5990711361
          eccentricity: 0.01
          inclination: 0.48
          orbitalArc: 2
          axialTilt: 5.27
          parentId: Tejat 7
          showOrbit: true
        satellites: []
      - name: Tejat 7b
        description: ''
        tags: []
        isPlanet:
          radius: 1223.0876347018843
          age: 4299345102
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 48623
        temperature: 257
        satellite:
          semiMajorAxis: 528373.858191214
          eccentricity: 0.02
          inclination: 0.09
          orbitalArc: 255
          axialTilt: 37.14
          parentId: Tejat 7
          showOrbit: true
        satellites: []
commSatellite: null
assets: {}
