apiVersion: solarSystem/v1
kind: solarSystems
name: Mebsuta
description: A solar system named Mebsuta
position:
  x: -392657972.1374098
  'y': -187631346.40283608
  z: -76204263.95521463
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Mebsuta
stars:
  - name: Mebsuta A
    description: ''
    tags: []
    radius: 130
    temperature: 4591
    solarMass: 5.29
    age: 40635824949
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 42
      semiMajorAxis: 1560
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Mebsuta
  - name: Mebsuta B
    description: ''
    tags: []
    radius: 130
    temperature: 4591
    solarMass: 5.29
    age: 40635824949
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 222
      semiMajorAxis: 1560
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Mebsuta
planets:
  - name: Mebsuta 1
    description: ''
    tags: []
    isPlanet:
      radius: 5126
      age: 4059853446
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
      terranMass: 0.01457946855002594
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      classification: H
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
    population: 0
    temperature: 851
    satellite:
      semiMajorAxis: 3438913726.0000005
      eccentricity: 0
      inclination: 1.02
      orbitalArc: 143
      axialTilt: 11.82
      parentId: Mebsuta
      showOrbit: true
    satellites: []
  - name: Mebsuta 2
    description: ''
    tags: []
    isPlanet:
      radius: 5776
      age: 3479271565
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.0047551805496344295
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      classification: P
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
    population: 158377
    temperature: 268
    satellite:
      semiMajorAxis: 5861755148
      eccentricity: 0.01
      inclination: 1.03
      orbitalArc: 267
      axialTilt: 34.88
      parentId: Mebsuta
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
