apiVersion: solarSystem/v1
kind: solarSystems
name: Guniibuu
description: A solar system named Guniibuu
position:
  x: 8997251.75019929
  'y': 4592138.3668537615
  z: -1775323.8723133001
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Guniibuu
stars:
  - name: Guniibuu A
    description: ''
    tags: []
    solarMass: 0.75
    age: 90633402371430
    spectralType: K
    hue: 30
    isWhite: false
    radius: 0.817
    temperature: 5171
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.803999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 174
      showOrbit: false
      parentId: Guniibuu
  - name: Guniibuu B
    description: ''
    tags: []
    solarMass: 0.75
    age: 90633402371430
    spectralType: K
    hue: 30
    isWhite: false
    radius: 0.817
    temperature: 5171
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.803999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 354
      showOrbit: false
      parentId: Guniibuu
planets:
  - name: Guniibuu 1
    description: ''
    tags: []
    satellite:
      axialTilt: 26.48
      semiMajorAxis: 1003812001.333334
      eccentricity: 0
      inclination: 0.21
      orbitalArc: 216
      showOrbit: true
      parentId: Guniibuu
    isPlanet:
      age: 5413313517
      classification: M
      radius: 5352
      terranMass: 0.0074391834635611585
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial3.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 2293685939
    temperature: 288
    satellites:
      - name: Guniibuu 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 16.52
          semiMajorAxis: 102930.35660399272
          eccentricity: 0.02
          inclination: 1.79
          orbitalArc: 56
          showOrbit: true
          parentId: Guniibuu 1
        isPlanet:
          age: 403256602
          classification: D
          radius: 386.9562278345591
          terranMass: 0.4199997616380393
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 221
  - name: Guniibuu 2
    description: ''
    tags: []
    satellite:
      axialTilt: 14.79
      semiMajorAxis: 2497714069
      eccentricity: 0.01
      inclination: 0.91
      orbitalArc: 140
      showOrbit: true
      parentId: Guniibuu
    isPlanet:
      age: 7679039058
      classification: J
      radius: 59161
      terranMass: 0.2164142502370324
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 167
    satellites:
      - name: Guniibuu 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 35.87
          semiMajorAxis: 2017597.2268305137
          eccentricity: 0
          inclination: 1.88
          orbitalArc: 0
          showOrbit: true
          parentId: Guniibuu 2
        isPlanet:
          age: 6257585483
          classification: K
          radius: 10877.834305755396
          terranMass: 0.10000000359490394
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 16422
        temperature: 257
      - name: Guniibuu 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 0.39
          semiMajorAxis: 2870065.1163337966
          eccentricity: 0.01
          inclination: 0.46
          orbitalArc: 187
          showOrbit: true
          parentId: Guniibuu 2
        isPlanet:
          age: 3549060223
          classification: P
          radius: 7763.605367977324
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 46937
        temperature: 263
      - name: Guniibuu 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 18.95
          semiMajorAxis: 3885227.4442428336
          eccentricity: 0.02
          inclination: 0.35
          orbitalArc: 180
          showOrbit: true
          parentId: Guniibuu 2
        isPlanet:
          age: 3009771009
          classification: P
          radius: 14661.235638652202
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 34647
        temperature: 259
commSatellite: null
assets: {}
