apiVersion: solarSystem/v1
kind: solarSystems
name: Nekkar
description: A solar system named Nekkar
position:
  x: 64273119.38228746
  'y': -76684318.89575893
  z: -63190771.80541298
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Nekkar
stars:
  - name: Nekkar A
    description: ''
    tags: []
    solarMass: 3.23
    age: 878643247104
    spectralType: K
    hue: 30
    isWhite: false
    radius: 18.44
    temperature: 4997
    satellite:
      axialTilt: 0
      semiMajorAxis: 221.28000000000003
      eccentricity: 0
      inclination: 0
      orbitalArc: 348
      showOrbit: false
      parentId: Nekkar
  - name: Nekkar B
    description: ''
    tags: []
    solarMass: 3.23
    age: 878643247104
    spectralType: K
    hue: 30
    isWhite: false
    radius: 18.44
    temperature: 4997
    satellite:
      axialTilt: 0
      semiMajorAxis: 221.28000000000003
      eccentricity: 0
      inclination: 0
      orbitalArc: 528
      showOrbit: false
      parentId: Nekkar
planets:
  - name: Nekkar 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.23
      semiMajorAxis: 1037824178.6666666
      eccentricity: 0
      inclination: 0.57
      orbitalArc: 19
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 4144371191
      classification: O
      radius: 5287
      terranMass: 0.023000719766249116
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 165546004
    temperature: 291
    satellites: []
  - name: Nekkar 2
    description: ''
    tags: []
    satellite:
      axialTilt: 36.66
      semiMajorAxis: 1914524313.2222223
      eccentricity: 0.01
      inclination: 0.26
      orbitalArc: 2
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 398082806
      classification: C
      radius: 1651
      terranMass: 0.0014260119694977742
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 46
    satellites: []
  - name: Nekkar 3
    description: ''
    tags: []
    satellite:
      axialTilt: 38.43
      semiMajorAxis: 2218981317.8888903
      eccentricity: 0.02
      inclination: 0.7
      orbitalArc: 77
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 3641089506
      classification: G
      radius: 5683
      terranMass: 0.01145034011894612
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 413
    satellites:
      - name: Nekkar 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 11.41
          semiMajorAxis: 385525.97349438554
          eccentricity: 0.02
          inclination: 1.91
          orbitalArc: 354
          showOrbit: true
          parentId: Nekkar 3
        isPlanet:
          age: 8967371882
          classification: P
          radius: 1111.0258602143676
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 162276
        temperature: 263
  - name: Nekkar 4
    description: ''
    tags: []
    satellite:
      axialTilt: 3.97
      semiMajorAxis: 2487179133.9259305
      eccentricity: 0
      inclination: 0.15
      orbitalArc: 307
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 484153320
      classification: D
      radius: 387
      terranMass: 0.009123875634148234
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 266
    satellites: []
  - name: Nekkar 5
    description: ''
    tags: []
    satellite:
      axialTilt: 20.36
      semiMajorAxis: 2844577046.8765497
      eccentricity: 0.02
      inclination: 0.25
      orbitalArc: 86
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 8938840579
      classification: L
      radius: 4885
      terranMass: 0.0008358055984296574
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 40356
    temperature: 292
    satellites:
      - name: Nekkar 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 19.69
          semiMajorAxis: 193723.1098653168
          eccentricity: 0
          inclination: 1.84
          orbitalArc: 99
          showOrbit: true
          parentId: Nekkar 5
        isPlanet:
          age: 5105502567
          classification: P
          radius: 490.83646080179295
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 120648
        temperature: 260
      - name: Nekkar 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 11.4
          semiMajorAxis: 263486.98142622365
          eccentricity: 0.02
          inclination: 1.43
          orbitalArc: 13
          showOrbit: true
          parentId: Nekkar 5
        isPlanet:
          age: 9114710642
          classification: K
          radius: 1094.663689535324
          terranMass: 1.10000003140348
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 2712
        temperature: 272
      - name: Nekkar 5c
        description: ''
        tags: []
        satellite:
          axialTilt: 36.38
          semiMajorAxis: 337188.8026970153
          eccentricity: 0
          inclination: 0.9
          orbitalArc: 312
          showOrbit: true
          parentId: Nekkar 5
        isPlanet:
          age: 6704079820
          classification: P
          radius: 800.923521845642
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 184306
        temperature: 257
  - name: Nekkar 6
    description: ''
    tags: []
    satellite:
      axialTilt: 5.71
      semiMajorAxis: 3196950513.045281
      eccentricity: 0.01
      inclination: 0.11
      orbitalArc: 93
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 8249629350
      classification: L
      radius: 3453
      terranMass: 0.043498438238502586
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 7325
    temperature: 251
    satellites:
      - name: Nekkar 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 19.71
          semiMajorAxis: 163141.35705195507
          eccentricity: 0.01
          inclination: 1.24
          orbitalArc: 188
          showOrbit: true
          parentId: Nekkar 6
        isPlanet:
          age: 4728517339
          classification: L
          radius: 477.02151184782184
          terranMass: 0.10000011867658457
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 8197
        temperature: 270
  - name: Nekkar 7
    description: ''
    tags: []
    satellite:
      axialTilt: 9.24
      semiMajorAxis: 3607921583
      eccentricity: 0
      inclination: 0.15
      orbitalArc: 85
      showOrbit: true
      parentId: Nekkar
    isPlanet:
      age: 1612497456
      classification: A
      radius: 4175
      terranMass: 0.016957786714860493
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1522
    satellites:
      - name: Nekkar 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.29
          semiMajorAxis: 122280.12119331563
          eccentricity: 0.01
          inclination: 0.4
          orbitalArc: 253
          showOrbit: true
          parentId: Nekkar 7
        isPlanet:
          age: 1010043520
          classification: E
          radius: 542.6392728105162
          terranMass: 1.100000008931671
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 888
      - name: Nekkar 7b
        description: ''
        tags: []
        satellite:
          axialTilt: 24.2
          semiMajorAxis: 259664.28616462322
          eccentricity: 0.01
          inclination: 0.13
          orbitalArc: 281
          showOrbit: true
          parentId: Nekkar 7
        isPlanet:
          age: 7266437474
          classification: P
          radius: 486.6215348652032
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 161643
        temperature: 263
      - name: Nekkar 7c
        description: ''
        tags: []
        satellite:
          axialTilt: 14.19
          semiMajorAxis: 349501.25257643964
          eccentricity: 0.01
          inclination: 1.17
          orbitalArc: 31
          showOrbit: true
          parentId: Nekkar 7
        isPlanet:
          age: 9726100927
          classification: P
          radius: 914.9247449645017
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 172858
        temperature: 255
commSatellite: null
assets: {}
