apiVersion: solarSystem/v1
kind: solarSystems
name: Scheat
description: A solar system named Scheat
position:
  x: 22090042.519583847
  'y': -48528423.24287579
  z: 88228061.81271859
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Scheat
stars:
  - name: Scheat A
    description: ''
    tags: []
    solarMass: 1.7
    age: 48804775615
    spectralType: M
    hue: 0
    isWhite: false
    radius: 109
    temperature: 3606
    satellite:
      axialTilt: 0
      semiMajorAxis: 1308
      eccentricity: 0
      inclination: 0
      orbitalArc: 148
      showOrbit: false
      parentId: Scheat
  - name: Scheat B
    description: ''
    tags: []
    solarMass: 1.7
    age: 48804775615
    spectralType: M
    hue: 0
    isWhite: false
    radius: 109
    temperature: 3606
    satellite:
      axialTilt: 0
      semiMajorAxis: 1308
      eccentricity: 0
      inclination: 0
      orbitalArc: 328
      showOrbit: false
      parentId: Scheat
planets:
  - name: Scheat 1
    description: ''
    tags: []
    satellite:
      axialTilt: 16.56
      semiMajorAxis: 2341880705.0000005
      eccentricity: 0.01
      inclination: 0.88
      orbitalArc: 201
      showOrbit: true
      parentId: Scheat
    isPlanet:
      age: 176553719
      classification: D
      radius: 389
      terranMass: 0.00822471178726655
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 383
    satellites: []
  - name: Scheat 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.01
      semiMajorAxis: 3279986163.9999995
      eccentricity: 0.01
      inclination: 0.32
      orbitalArc: 310
      showOrbit: true
      parentId: Scheat
    isPlanet:
      age: 4226705189
      classification: K
      radius: 4942
      terranMass: 0.0062579214966380905
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: null
    population: 26397
    temperature: 269
    satellites:
      - name: Scheat 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 12.45
          semiMajorAxis: 251762.7590796394
          eccentricity: 0.01
          inclination: 0.87
          orbitalArc: 177
          showOrbit: true
          parentId: Scheat 2
        isPlanet:
          age: 604291163
          classification: C
          radius: 518.0303684766243
          terranMass: 1.5000001780207701
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 39
  - name: Scheat 3
    description: ''
    tags: []
    satellite:
      axialTilt: 15.39
      semiMajorAxis: 4422903414
      eccentricity: 0
      inclination: 1.94
      orbitalArc: 139
      showOrbit: true
      parentId: Scheat
    isPlanet:
      age: 4194716823
      classification: P
      radius: 5971
      terranMass: 0.0027783435083176813
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 141653
    temperature: 256
    satellites:
      - name: Scheat 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.04
          semiMajorAxis: 341039.7669548004
          eccentricity: 0.01
          inclination: 0.33
          orbitalArc: 147
          showOrbit: true
          parentId: Scheat 3
        isPlanet:
          age: 188861540
          classification: D
          radius: 761.2494798098223
          terranMass: 0.0499998296425963
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 157
commSatellite: null
assets: {}
