apiVersion: solarSystem/v1
kind: solarSystems
name: Larawag
description: A solar system named Larawag
position:
  x: 26114219.937973026
  'y': 18669472.569399327
  z: -8213302.980045165
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Larawag
stars:
  - name: 'Larawag '
    description: ''
    tags: []
    solarMass: 1.31
    age: 1129112712385
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12.65
    temperature: 4522
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 208
      showOrbit: false
      parentId: Larawag
planets:
  - name: Larawag 1
    description: ''
    tags: []
    satellite:
      axialTilt: 38.31
      semiMajorAxis: 523383987.3333333
      eccentricity: 0.01
      inclination: 0.56
      orbitalArc: 75
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 4817558982
      classification: O
      radius: 6982
      terranMass: 0.0035182818830987164
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 173124739
    temperature: 291
    satellites: []
  - name: Larawag 2
    description: ''
    tags: []
    satellite:
      axialTilt: 21.03
      semiMajorAxis: 904470449.8888886
      eccentricity: 0
      inclination: 1.18
      orbitalArc: 14
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 9551767749
      classification: P
      radius: 6932
      terranMass: 0.020115723071530398
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 45006
    temperature: 263
    satellites: []
  - name: Larawag 3
    description: ''
    tags: []
    satellite:
      axialTilt: 1.96
      semiMajorAxis: 1298180846.6296287
      eccentricity: 0.02
      inclination: 0.09
      orbitalArc: 96
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 810063306
      classification: E
      radius: 5009
      terranMass: 0.03274382519822245
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1252
    satellites: []
  - name: Larawag 4
    description: ''
    tags: []
    satellite:
      axialTilt: 4.17
      semiMajorAxis: 2128966071.6296287
      eccentricity: 0.02
      inclination: 0.46
      orbitalArc: 75
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 3121457991
      classification: G
      radius: 7286
      terranMass: 0.0016689500548338866
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 567
    satellites:
      - name: Larawag 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 1.52
          semiMajorAxis: 183607.27325349837
          eccentricity: 0.01
          inclination: 1.12
          orbitalArc: 356
          showOrbit: true
          parentId: Larawag 4
        isPlanet:
          age: 173620795
          classification: D
          radius: 381.6273902651685
          terranMass: 0.4999997538380867
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 337
      - name: Larawag 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 19.16
          semiMajorAxis: 368201.99467715976
          eccentricity: 0
          inclination: 0.79
          orbitalArc: 282
          showOrbit: true
          parentId: Larawag 4
        isPlanet:
          age: 397983892
          classification: D
          radius: 840.3328129123507
          terranMass: 0.9899997303399186
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 282
      - name: Larawag 4c
        description: ''
        tags: []
        satellite:
          axialTilt: 37.66
          semiMajorAxis: 492607.7385476007
          eccentricity: 0.01
          inclination: 0.97
          orbitalArc: 69
          showOrbit: true
          parentId: Larawag 4
        isPlanet:
          age: 322661507
          classification: D
          radius: 1539.399182961252
          terranMass: 1.3299996935090859
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 200
  - name: Larawag 5
    description: ''
    tags: []
    satellite:
      axialTilt: 15.97
      semiMajorAxis: 3158231264.5061707
      eccentricity: 0
      inclination: 0.82
      orbitalArc: 177
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 9421945797
      classification: J
      radius: 58952
      terranMass: 0.8264740254023284
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 253
    satellites: []
  - name: Larawag 6
    description: ''
    tags: []
    satellite:
      axialTilt: 27.79
      semiMajorAxis: 3979469875
      eccentricity: 0.02
      inclination: 0.47
      orbitalArc: 317
      showOrbit: true
      parentId: Larawag
    isPlanet:
      age: 278742282
      classification: D
      radius: 298
      terranMass: 0.0014481525141669493
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 258
    satellites: []
commSatellite: null
assets: {}
