apiVersion: solarSystem/v1
kind: solarSystems
name: Kaus Media
description: A solar system named Kaus Media
position:
  x: 158120273.66604543
  'y': 91041068.39397751
  z: 14525059.824468886
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Kaus Media
stars:
  - name: Kaus Media A
    description: ''
    tags: []
    solarMass: 3.21
    age: 100502089350
    spectralType: K
    hue: 30
    isWhite: false
    radius: 76.83
    temperature: 4203
    satellite:
      axialTilt: 0
      semiMajorAxis: 921.96
      eccentricity: 0
      inclination: 0
      orbitalArc: 60
      showOrbit: false
      parentId: Kaus Media
  - name: Kaus Media B
    description: ''
    tags: []
    solarMass: 3.21
    age: 100502089350
    spectralType: K
    hue: 30
    isWhite: false
    radius: 76.83
    temperature: 4203
    satellite:
      axialTilt: 0
      semiMajorAxis: 921.96
      eccentricity: 0
      inclination: 0
      orbitalArc: 240
      showOrbit: false
      parentId: Kaus Media
planets:
  - name: Kaus Media 1
    description: ''
    tags: []
    satellite:
      axialTilt: 19.14
      semiMajorAxis: 1540895263.3333333
      eccentricity: 0.01
      inclination: 0.08
      orbitalArc: 66
      showOrbit: true
      parentId: Kaus Media
    isPlanet:
      age: 164224960
      classification: C
      radius: 1670
      terranMass: 0.0024597729952990826
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 42
    satellites:
      - name: Kaus Media 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.64
          semiMajorAxis: 62205.7603374722
          eccentricity: 0.01
          inclination: 0.36
          orbitalArc: 231
          showOrbit: true
          parentId: Kaus Media 1
        isPlanet:
          age: 8319855457
          classification: 'N'
          radius: 328.7429468087486
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 438620206
        temperature: 464
      - name: Kaus Media 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 27.03
          semiMajorAxis: 119582.92503130191
          eccentricity: 0.02
          inclination: 0.94
          orbitalArc: 5
          showOrbit: true
          parentId: Kaus Media 1
        isPlanet:
          age: 425919613
          classification: D
          radius: 276.96602535258654
          terranMass: 0.579999796296472
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 311
      - name: Kaus Media 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 19.7
          semiMajorAxis: 164757.80561909542
          eccentricity: 0
          inclination: 0.3
          orbitalArc: 196
          showOrbit: true
          parentId: Kaus Media 1
        isPlanet:
          age: 98749867
          classification: D
          radius: 407.81635054231543
          terranMass: 0.2899999588704054
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 197
  - name: Kaus Media 2
    description: ''
    tags: []
    satellite:
      axialTilt: 2.37
      semiMajorAxis: 3038608260.6666675
      eccentricity: 0.01
      inclination: 1.28
      orbitalArc: 225
      showOrbit: true
      parentId: Kaus Media
    isPlanet:
      age: 4736794717
      classification: J
      radius: 28911
      terranMass: 0.5758075622424501
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 300
    satellites:
      - name: Kaus Media 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.3
          semiMajorAxis: 1991476.5667199478
          eccentricity: 0.02
          inclination: 0.72
          orbitalArc: 342
          showOrbit: true
          parentId: Kaus Media 2
        isPlanet:
          age: 5145434465
          classification: K
          radius: 5282.431211458747
          terranMass: 0.3000000518320557
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 39198
        temperature: 185
  - name: Kaus Media 3
    description: ''
    tags: []
    satellite:
      axialTilt: 11.31
      semiMajorAxis: 3653704257.6666665
      eccentricity: 0.01
      inclination: 0.51
      orbitalArc: 119
      showOrbit: true
      parentId: Kaus Media
    isPlanet:
      age: 5465266991
      classification: M
      radius: 6790
      terranMass: 0.0008753145726805819
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial3.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 2697019087
    temperature: 291
    satellites: []
  - name: Kaus Media 4
    description: ''
    tags: []
    satellite:
      axialTilt: 39.57
      semiMajorAxis: 3868029561.555555
      eccentricity: 0.02
      inclination: 0.07
      orbitalArc: 142
      showOrbit: true
      parentId: Kaus Media
    isPlanet:
      age: 3464092578
      classification: O
      radius: 6201
      terranMass: 0.018817253274916963
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 569279826
    temperature: 290
    satellites:
      - name: Kaus Media 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 21.32
          semiMajorAxis: 365619.508173261
          eccentricity: 0
          inclination: 0.14
          orbitalArc: 322
          showOrbit: true
          parentId: Kaus Media 4
        isPlanet:
          age: 9568990916
          classification: P
          radius: 902.7642177117556
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 50370
        temperature: 258
  - name: Kaus Media 5
    description: ''
    tags: []
    satellite:
      axialTilt: 3.08
      semiMajorAxis: 4233677566
      eccentricity: 0.01
      inclination: 0.25
      orbitalArc: 234
      showOrbit: true
      parentId: Kaus Media
    isPlanet:
      age: 7196910640
      classification: P
      radius: 5517
      terranMass: 0.017133060748370614
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 147916
    temperature: 261
    satellites:
      - name: Kaus Media 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.1
          semiMajorAxis: 180775.4003510091
          eccentricity: 0.02
          inclination: 0.15
          orbitalArc: 180
          showOrbit: true
          parentId: Kaus Media 5
        isPlanet:
          age: 4927610566
          classification: H
          radius: 999.9533608827749
          terranMass: 1.3000001326880533
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 894
      - name: Kaus Media 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 31.8
          semiMajorAxis: 504735.7011980469
          eccentricity: 0.01
          inclination: 1.99
          orbitalArc: 191
          showOrbit: true
          parentId: Kaus Media 5
        isPlanet:
          age: 9550219079
          classification: M
          radius: 1258.69252169089
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 2227202892
        temperature: 297
commSatellite: null
assets: {}
