apiVersion: solarSystem/v1
kind: solarSystems
name: Mirach
description: A solar system named Mirach
position:
  x: -25233636.360695865
  'y': -60346382.775393195
  z: 80358344.59044246
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Mirach
stars:
  - name: Mirach A
    description: ''
    tags: []
    solarMass: 2.49
    age: 96043058494
    spectralType: K
    hue: 30
    isWhite: false
    radius: 86.4
    temperature: 3762
    satellite:
      axialTilt: 0
      semiMajorAxis: 1036.8000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 344
      showOrbit: false
      parentId: Mirach
  - name: Mirach B
    description: ''
    tags: []
    solarMass: 2.49
    age: 96043058494
    spectralType: K
    hue: 30
    isWhite: false
    radius: 86.4
    temperature: 3762
    satellite:
      axialTilt: 0
      semiMajorAxis: 1036.8000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 524
      showOrbit: false
      parentId: Mirach
planets:
  - name: Mirach 1
    description: ''
    tags: []
    satellite:
      axialTilt: 18.18
      semiMajorAxis: 3937851946
      eccentricity: 0.01
      inclination: 0.06
      orbitalArc: 136
      showOrbit: true
      parentId: Mirach
    isPlanet:
      age: 7616624498
      classification: P
      radius: 6642
      terranMass: 0.0044159444391066085
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 128776
    temperature: 263
    satellites: []
commSatellite: null
assets: {}
