apiVersion: solarSystem/v1
kind: solarSystems
name: Menkib
description: A solar system named Menkib
position:
  x: -442211860.8161685
  'y': -369117078.0839245
  z: 257980813.09331432
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Menkib
stars:
  - name: Menkib A
    description: ''
    tags: []
    solarMass: 26
    age: 5098170829
    spectralType: O
    hue: 220
    isWhite: false
    radius: 14
    temperature: 35000
    satellite:
      axialTilt: 0
      semiMajorAxis: 168
      eccentricity: 0
      inclination: 0
      orbitalArc: 343
      showOrbit: false
      parentId: Menkib
  - name: Menkib B
    description: ''
    tags: []
    solarMass: 26
    age: 5098170829
    spectralType: O
    hue: 220
    isWhite: false
    radius: 14
    temperature: 35000
    satellite:
      axialTilt: 0
      semiMajorAxis: 168
      eccentricity: 0
      inclination: 0
      orbitalArc: 523
      showOrbit: false
      parentId: Menkib
planets: []
commSatellite: null
assets: {}
