apiVersion: solarSystem/v1
kind: solarSystems
name: Acrux
description: A solar system named Acrux
position:
  x: 8897855.142093446
  'y': 151454973.30117622
  z: -76323599.6125744
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Acrux
stars:
  - name: Acrux A
    description: ''
    tags: []
    solarMass: 17.8
    age: 27922429683
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.29
    temperature: 28840
    satellite:
      axialTilt: 0
      semiMajorAxis: 87.48
      eccentricity: 0
      inclination: 0
      orbitalArc: 319
      showOrbit: false
      parentId: Acrux
  - name: Acrux B
    description: ''
    tags: []
    solarMass: 17.8
    age: 27922429683
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.29
    temperature: 28840
    satellite:
      axialTilt: 0
      semiMajorAxis: 87.48
      eccentricity: 0
      inclination: 0
      orbitalArc: 499
      showOrbit: false
      parentId: Acrux
planets:
  - name: Acrux 1
    description: ''
    tags: []
    satellite:
      axialTilt: 15.68
      semiMajorAxis: 2334769157.666666
      eccentricity: 0.02
      inclination: 0.97
      orbitalArc: 185
      showOrbit: true
      parentId: Acrux
    isPlanet:
      age: 74175446
      classification: C
      radius: 2628
      terranMass: 0.008295167935738989
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 35
    satellites: []
  - name: Acrux 2
    description: ''
    tags: []
    satellite:
      axialTilt: 16.19
      semiMajorAxis: 4548686550.111111
      eccentricity: 0.01
      inclination: 1.3
      orbitalArc: 210
      showOrbit: true
      parentId: Acrux
    isPlanet:
      age: 895694807
      classification: C
      radius: 503
      terranMass: 0.004227861677383323
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 38
    satellites: []
  - name: Acrux 3
    description: ''
    tags: []
    satellite:
      axialTilt: 34.93
      semiMajorAxis: 7021066498.074074
      eccentricity: 0.01
      inclination: 0.39
      orbitalArc: 2
      showOrbit: true
      parentId: Acrux
    isPlanet:
      age: 9789651251
      classification: L
      radius: 5809
      terranMass: 0.02621895831280327
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 26909
    temperature: 158
    satellites:
      - name: Acrux 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.4
          semiMajorAxis: 127547.12825050541
          eccentricity: 0.01
          inclination: 1.02
          orbitalArc: 275
          showOrbit: true
          parentId: Acrux 3
        isPlanet:
          age: 5364757938
          classification: P
          radius: 300.1108900011892
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 47906
        temperature: 265
  - name: Acrux 4
    description: ''
    tags: []
    satellite:
      axialTilt: 28.96
      semiMajorAxis: 11298179031
      eccentricity: 0.01
      inclination: 1.93
      orbitalArc: 155
      showOrbit: true
      parentId: Acrux
    isPlanet:
      age: 6605211938
      classification: P
      radius: 6979
      terranMass: 0.022499895764049118
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 81776
    temperature: 255
    satellites: []
commSatellite: null
assets: {}
