apiVersion: solarSystem/v1
kind: solarSystems
name: Fulu
description: A solar system named Fulu
position:
  x: -29369391.933763325
  'y': -250722644.72193548
  z: 180476764.0169757
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Fulu
stars:
  - name: Fulu A
    description: ''
    tags: []
    solarMass: 8.96
    age: 64992581047
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.1
    temperature: 21500
    satellite:
      axialTilt: 0
      semiMajorAxis: 73.19999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 11
      showOrbit: false
      parentId: Fulu
  - name: Fulu B
    description: ''
    tags: []
    solarMass: 8.96
    age: 64992581047
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.1
    temperature: 21500
    satellite:
      axialTilt: 0
      semiMajorAxis: 73.19999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 191
      showOrbit: false
      parentId: Fulu
planets:
  - name: Fulu 1
    description: ''
    tags: []
    satellite:
      axialTilt: 24.25
      semiMajorAxis: 5377319709
      eccentricity: 0.01
      inclination: 1.88
      orbitalArc: 261
      showOrbit: true
      parentId: Fulu
    isPlanet:
      age: 3099585678
      classification: G
      radius: 5641
      terranMass: 0.005842948756959044
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 511
    satellites:
      - name: Fulu 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 3.82
          semiMajorAxis: 140865.64142585755
          eccentricity: 0
          inclination: 1.97
          orbitalArc: 222
          showOrbit: true
          parentId: Fulu 1
        isPlanet:
          age: 8710230466
          classification: 'N'
          radius: 560.8388114765959
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 295599035
        temperature: 615
      - name: Fulu 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 14.28
          semiMajorAxis: 233124.6147502437
          eccentricity: 0.01
          inclination: 0.07
          orbitalArc: 54
          showOrbit: true
          parentId: Fulu 1
        isPlanet:
          age: 3464222647
          classification: O
          radius: 873.1258979409877
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 453182024
        temperature: 300
commSatellite: null
assets: {}
