apiVersion: solarSystem/v1
kind: solarSystems
name: Alnasl
description: A solar system named Alnasl
position:
  x: 43525446.26117945
  'y': 25569053.787968688
  z: 1103284.9218333126
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alnasl
stars:
  - name: Alnasl A
    description: ''
    tags: []
    radius: 12.07
    temperature: 4864
    solarMass: 1.98
    age: 1400379257845
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 72
      semiMajorAxis: 144.84
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Alnasl
  - name: Alnasl B
    description: ''
    tags: []
    radius: 12.07
    temperature: 4864
    solarMass: 1.98
    age: 1400379257845
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 252
      semiMajorAxis: 144.84
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Alnasl
planets:
  - name: Alnasl 1
    description: ''
    tags: []
    isPlanet:
      radius: 5207
      age: 6187360040
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.0068989129549824725
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      classification: L
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
    population: 45471
    temperature: 328
    satellite:
      semiMajorAxis: 1309426697
      eccentricity: 0
      inclination: 1.96
      orbitalArc: 30
      axialTilt: 39.75
      parentId: Alnasl
      showOrbit: true
    satellites:
      - name: Alnasl 1a
        description: ''
        tags: []
        isPlanet:
          radius: 373.9603879245721
          age: 415515854
          ringMapAsset: null
          terranMass: 1.2000001257580255
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          classification: C
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 54
        satellite:
          semiMajorAxis: 51455.727519685905
          eccentricity: 0
          inclination: 0.52
          orbitalArc: 65
          axialTilt: 19.93
          parentId: Alnasl 1
          showOrbit: true
        satellites: []
      - name: Alnasl 1b
        description: ''
        tags: []
        isPlanet:
          radius: 499.4672993372235
          age: 6426193952
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 173953
        temperature: 259
        satellite:
          semiMajorAxis: 144845.5168077948
          eccentricity: 0.01
          inclination: 0.7
          orbitalArc: 355
          axialTilt: 32.39
          parentId: Alnasl 1
          showOrbit: true
        satellites: []
commSatellite: null
assets: {}
