apiVersion: solarSystem/v1
kind: solarSystems
name: Saclateni
description: A solar system named Saclateni
position:
  x: -238121598.87512603
  'y': -214263270.12179607
  z: 61052720.56925752
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Saclateni
stars:
  - name: Saclateni A
    description: ''
    tags: []
    solarMass: 5.8
    age: 62100214964
    spectralType: K
    hue: 30
    isWhite: false
    radius: 148
    temperature: 3960
    satellite:
      axialTilt: 0
      semiMajorAxis: 1776
      eccentricity: 0
      inclination: 0
      orbitalArc: 164
      showOrbit: false
      parentId: Saclateni
  - name: Saclateni B
    description: ''
    tags: []
    solarMass: 5.8
    age: 62100214964
    spectralType: K
    hue: 30
    isWhite: false
    radius: 148
    temperature: 3960
    satellite:
      axialTilt: 0
      semiMajorAxis: 1776
      eccentricity: 0
      inclination: 0
      orbitalArc: 344
      showOrbit: false
      parentId: Saclateni
planets:
  - name: Saclateni 1
    description: ''
    tags: []
    satellite:
      axialTilt: 13.31
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 0.3
      orbitalArc: 62
      showOrbit: true
      parentId: Saclateni
    isPlanet:
      age: 8371450643
      classification: J
      radius: 35699
      terranMass: 0.7356160110143517
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 295
    satellites: []
commSatellite: null
assets: {}
