apiVersion: solarSystem/v1
kind: solarSystems
name: Athebyne
description: A solar system named Athebyne
position:
  x: 21082780.511004236
  'y': -42530210.282717995
  z: -9387603.08358895
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Athebyne
stars:
  - name: Athebyne A
    description: ''
    tags: []
    solarMass: 2.55
    age: 2119939504542
    spectralType: K
    hue: 30
    isWhite: false
    radius: 10.46
    temperature: 5018
    satellite:
      axialTilt: 0
      semiMajorAxis: 125.52000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 276
      showOrbit: false
      parentId: Athebyne
  - name: Athebyne B
    description: ''
    tags: []
    solarMass: 2.55
    age: 2119939504542
    spectralType: K
    hue: 30
    isWhite: false
    radius: 10.46
    temperature: 5018
    satellite:
      axialTilt: 0
      semiMajorAxis: 125.52000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 456
      showOrbit: false
      parentId: Athebyne
planets:
  - name: Athebyne 1
    description: ''
    tags: []
    satellite:
      axialTilt: 34.18
      semiMajorAxis: 1440210046
      eccentricity: 0.01
      inclination: 0.2
      orbitalArc: 139
      showOrbit: true
      parentId: Athebyne
    isPlanet:
      age: 4784790805
      classification: K
      radius: 3532
      terranMass: 0.028949392182460825
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 35233
    temperature: 155
    satellites:
      - name: Athebyne 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 32.03
          semiMajorAxis: 331882.7792318962
          eccentricity: 0.02
          inclination: 0.82
          orbitalArc: 47
          showOrbit: true
          parentId: Athebyne 1
        isPlanet:
          age: 584651028
          classification: D
          radius: 727.8131123506496
          terranMass: 0.3399998978376615
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 260
commSatellite: null
assets: {}
