apiVersion: solarSystem/v1
kind: solarSystems
name: Alrescha
description: A solar system named Alrescha
position:
  x: -40275834.25560927
  'y': -3829437.643296935
  z: 68342685.26149957
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alrescha
stars:
  - name: Alrescha A
    description: ''
    tags: []
    solarMass: 2.55
    age: 2234423033550
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.45
    temperature: 10233
    satellite:
      axialTilt: 0
      semiMajorAxis: 29.400000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 28
      showOrbit: false
      parentId: Alrescha
  - name: Alrescha B
    description: ''
    tags: []
    solarMass: 2.55
    age: 2234423033550
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.45
    temperature: 10233
    satellite:
      axialTilt: 0
      semiMajorAxis: 29.400000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 208
      showOrbit: false
      parentId: Alrescha
planets:
  - name: Alrescha 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.63
      semiMajorAxis: 81422445.00000033
      eccentricity: 0.01
      inclination: 0.07
      orbitalArc: 145
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 6053333311
      classification: H
      radius: 6478
      terranMass: 0.008433700045786873
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 600
    satellites:
      - name: Alrescha 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 23.36
          semiMajorAxis: 132486.42114768212
          eccentricity: 0.02
          inclination: 1.69
          orbitalArc: 3
          showOrbit: true
          parentId: Alrescha 1
        isPlanet:
          age: 274812034
          classification: D
          radius: 347.6955214667123
          terranMass: 0.9899997038237995
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 251
      - name: Alrescha 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 12.23
          semiMajorAxis: 174940.91118768405
          eccentricity: 0.02
          inclination: 0.36
          orbitalArc: 293
          showOrbit: true
          parentId: Alrescha 1
        isPlanet:
          age: 927705102
          classification: D
          radius: 713.9516719685523
          terranMass: 1.0999998764091028
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 386
      - name: Alrescha 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 25.8
          semiMajorAxis: 251585.04538166852
          eccentricity: 0
          inclination: 0.19
          orbitalArc: 294
          showOrbit: true
          parentId: Alrescha 1
        isPlanet:
          age: 9031243004
          classification: K
          radius: 566.632985093848
          terranMass: 1.9000001466127237
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 26640
        temperature: 137
  - name: Alrescha 2
    description: ''
    tags: []
    satellite:
      axialTilt: 29.83
      semiMajorAxis: 187823766.3333411
      eccentricity: 0.01
      inclination: 1.78
      orbitalArc: 279
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 4519010553
      classification: H
      radius: 4829
      terranMass: 0.03870184894982704
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 517
    satellites:
      - name: Alrescha 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.89
          semiMajorAxis: 284140.07733477495
          eccentricity: 0
          inclination: 1.49
          orbitalArc: 252
          showOrbit: true
          parentId: Alrescha 2
        isPlanet:
          age: 41271146
          classification: D
          radius: 582.2542568335552
          terranMass: 0.8999999980353433
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 232
  - name: Alrescha 3
    description: ''
    tags: []
    satellite:
      axialTilt: 4.55
      semiMajorAxis: 437640953.44445485
      eccentricity: 0.01
      inclination: 0
      orbitalArc: 309
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 9895184890
      classification: H
      radius: 4784
      terranMass: 0.009745529662309401
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 862
    satellites: []
  - name: Alrescha 4
    description: ''
    tags: []
    satellite:
      axialTilt: 26.39
      semiMajorAxis: 1126131983.407425
      eccentricity: 0.01
      inclination: 1.2
      orbitalArc: 161
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 675528079
      classification: C
      radius: 4903
      terranMass: 0.0014579695882475105
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 37
    satellites:
      - name: Alrescha 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.5
          semiMajorAxis: 164333.4091511339
          eccentricity: 0.01
          inclination: 0.86
          orbitalArc: 171
          showOrbit: true
          parentId: Alrescha 4
        isPlanet:
          age: 799946543
          classification: D
          radius: 1225.2111655577462
          terranMass: 0.6099996974778856
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 307
      - name: Alrescha 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 5.02
          semiMajorAxis: 442558.4752735318
          eccentricity: 0.01
          inclination: 1.28
          orbitalArc: 153
          showOrbit: true
          parentId: Alrescha 4
        isPlanet:
          age: 547374698
          classification: D
          radius: 1017.3758052265099
          terranMass: 1.1999996331671825
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 343
  - name: Alrescha 5
    description: ''
    tags: []
    satellite:
      axialTilt: 37.99
      semiMajorAxis: 2173274598.2099
      eccentricity: 0.01
      inclination: 1.84
      orbitalArc: 152
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 6227765570
      classification: O
      radius: 6935
      terranMass: 0.0262281862026379
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 438741117
    temperature: 293
    satellites:
      - name: Alrescha 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 13.92
          semiMajorAxis: 458643.66304564674
          eccentricity: 0.02
          inclination: 0.46
          orbitalArc: 340
          showOrbit: true
          parentId: Alrescha 5
        isPlanet:
          age: 6122994472
          classification: P
          radius: 943.7112408346641
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 117504
        temperature: 261
  - name: Alrescha 6
    description: ''
    tags: []
    satellite:
      axialTilt: 24.03
      semiMajorAxis: 2797392012.349832
      eccentricity: 0.02
      inclination: 1.03
      orbitalArc: 139
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 946091855
      classification: C
      radius: 2469
      terranMass: 0.0081705271253164
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 47
    satellites: []
  - name: Alrescha 7
    description: ''
    tags: []
    satellite:
      axialTilt: 24.73
      semiMajorAxis: 3967913610
      eccentricity: 0.02
      inclination: 0.77
      orbitalArc: 129
      showOrbit: true
      parentId: Alrescha
    isPlanet:
      age: 8485025234
      classification: J
      radius: 52759
      terranMass: 0.29428372948180975
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 263
    satellites:
      - name: Alrescha 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 2.74
          semiMajorAxis: 1574517.7061614832
          eccentricity: 0.02
          inclination: 2
          orbitalArc: 142
          showOrbit: true
          parentId: Alrescha 7
        isPlanet:
          age: 6150865950
          classification: O
          radius: 6730.624215632858
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 231408130
        temperature: 290
      - name: Alrescha 7b
        description: ''
        tags: []
        satellite:
          axialTilt: 31.51
          semiMajorAxis: 2684595.155012014
          eccentricity: 0.02
          inclination: 0.5
          orbitalArc: 274
          showOrbit: true
          parentId: Alrescha 7
        isPlanet:
          age: 8493948501
          classification: H
          radius: 11064.510346385387
          terranMass: 0.10000004949242394
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 0
        temperature: 847
      - name: Alrescha 7c
        description: ''
        tags: []
        satellite:
          axialTilt: 14.15
          semiMajorAxis: 4013228.265213211
          eccentricity: 0.02
          inclination: 1.79
          orbitalArc: 347
          showOrbit: true
          parentId: Alrescha 7
        isPlanet:
          age: 7273370561
          classification: P
          radius: 11838.431460805932
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 156995
        temperature: 264
commSatellite: null
assets: {}
