apiVersion: solarSystem/v1
kind: solarSystems
name: Tegmine
description: A solar system named Tegmine
position:
  x: -35035866.14562971
  'y': -13298367.50606352
  z: -22798801.390057515
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tegmine
stars:
  - name: Tegmine A
    description: ''
    tags: []
    solarMass: 1.28
    age: 27946015806880
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.3242
    temperature: 6230
    satellite:
      axialTilt: 0
      semiMajorAxis: 15.8904
      eccentricity: 0
      inclination: 0
      orbitalArc: 183
      showOrbit: false
      parentId: Tegmine
  - name: Tegmine B
    description: ''
    tags: []
    solarMass: 1.28
    age: 27946015806880
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.3242
    temperature: 6230
    satellite:
      axialTilt: 0
      semiMajorAxis: 15.8904
      eccentricity: 0
      inclination: 0
      orbitalArc: 363
      showOrbit: false
      parentId: Tegmine
planets: []
commSatellite: null
assets: {}
