apiVersion: solarSystem/v1
kind: solarSystems
name: Procyon
description: A solar system named Procyon
position:
  x: -5447773.5413190555
  'y': -548906.4064390024
  z: -2520166.807470653
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Procyon
stars:
  - name: Procyon A
    description: ''
    tags: []
    solarMass: 1.478
    age: 10881166941555
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.043
    temperature: 6582
    satellite:
      axialTilt: 0
      semiMajorAxis: 24.516000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 93
      showOrbit: false
      parentId: Procyon
  - name: Procyon B
    description: ''
    tags: []
    solarMass: 1.478
    age: 10881166941555
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.043
    temperature: 6582
    satellite:
      axialTilt: 0
      semiMajorAxis: 24.516000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 273
      showOrbit: false
      parentId: Procyon
planets:
  - name: Procyon 1
    description: ''
    tags: []
    satellite:
      axialTilt: 22.37
      semiMajorAxis: 44504303
      eccentricity: 0.01
      inclination: 0.8
      orbitalArc: 174
      showOrbit: true
      parentId: Procyon
    isPlanet:
      age: 7282177632
      classification: H
      radius: 5996
      terranMass: 0.008318533302910304
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 551
    satellites:
      - name: Procyon 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 27.55
          semiMajorAxis: 519481.69596586097
          eccentricity: 0.01
          inclination: 1.11
          orbitalArc: 236
          showOrbit: true
          parentId: Procyon 1
        isPlanet:
          age: 8904556840
          classification: P
          radius: 1332.0043486304128
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 60695
        temperature: 259
  - name: Procyon 2
    description: ''
    tags: []
    satellite:
      axialTilt: 3.03
      semiMajorAxis: 197524001
      eccentricity: 0.01
      inclination: 1.57
      orbitalArc: 87
      showOrbit: true
      parentId: Procyon
    isPlanet:
      age: 5505675545
      classification: H
      radius: 6897
      terranMass: 0.032915903783353094
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 783
    satellites:
      - name: Procyon 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 5.97
          semiMajorAxis: 580581.5428566327
          eccentricity: 0
          inclination: 1.21
          orbitalArc: 237
          showOrbit: true
          parentId: Procyon 2
        isPlanet:
          age: 6918824736
          classification: H
          radius: 1372.5331982426305
          terranMass: 0.300000034939332
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 0
        temperature: 866
  - name: Procyon 3
    description: ''
    tags: []
    satellite:
      axialTilt: 31.38
      semiMajorAxis: 295901813
      eccentricity: 0
      inclination: 1.23
      orbitalArc: 79
      showOrbit: true
      parentId: Procyon
    isPlanet:
      age: 81321605
      classification: D
      radius: 303
      terranMass: 0.0007267918360113831
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 292
    satellites: []
commSatellite: null
assets: {}
