apiVersion: solarSystem/v1
kind: solarSystems
name: Sheliak
description: A solar system named Sheliak
position:
  x: 411685581.53095675
  'y': -277674900.5512959
  z: 91419110.20079952
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sheliak
stars:
  - name: Sheliak A
    description: ''
    tags: []
    solarMass: 2.97
    age: 23693651374
    spectralType: B
    hue: 200
    isWhite: false
    radius: 15.2
    temperature: 13300
    satellite:
      axialTilt: 0
      semiMajorAxis: 182.39999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 308
      showOrbit: false
      parentId: Sheliak
  - name: Sheliak B
    description: ''
    tags: []
    solarMass: 2.97
    age: 23693651374
    spectralType: B
    hue: 200
    isWhite: false
    radius: 15.2
    temperature: 13300
    satellite:
      axialTilt: 0
      semiMajorAxis: 182.39999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 488
      showOrbit: false
      parentId: Sheliak
planets:
  - name: Sheliak 1
    description: ''
    tags: []
    satellite:
      axialTilt: 26.14
      semiMajorAxis: 3881256627
      eccentricity: 0.01
      inclination: 0.02
      orbitalArc: 303
      showOrbit: true
      parentId: Sheliak
    isPlanet:
      age: 7683383020
      classification: J
      radius: 49737
      terranMass: 1.8111620081859088
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 254
    satellites:
      - name: Sheliak 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 21.03
          semiMajorAxis: 2456240.8966446556
          eccentricity: 0.02
          inclination: 1.15
          orbitalArc: 179
          showOrbit: true
          parentId: Sheliak 1
        isPlanet:
          age: 2368795206
          classification: F
          radius: 3927.9013932529724
          terranMass: 1.1000001350507231
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 751
      - name: Sheliak 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 36.99
          semiMajorAxis: 4419159.7436523475
          eccentricity: 0.02
          inclination: 1.46
          orbitalArc: 338
          showOrbit: true
          parentId: Sheliak 1
        isPlanet:
          age: 5309989616
          classification: P
          radius: 11660.052094069519
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 163828
        temperature: 264
  - name: Sheliak 2
    description: ''
    tags: []
    satellite:
      axialTilt: 3.23
      semiMajorAxis: 5937839877
      eccentricity: 0.01
      inclination: 1.56
      orbitalArc: 342
      showOrbit: true
      parentId: Sheliak
    isPlanet:
      age: 8767576125
      classification: P
      radius: 7024
      terranMass: 0.020294723349575588
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 103449
    temperature: 267
    satellites:
      - name: Sheliak 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.22
          semiMajorAxis: 508434.68024363415
          eccentricity: 0.02
          inclination: 0.93
          orbitalArc: 335
          showOrbit: true
          parentId: Sheliak 2
        isPlanet:
          age: 8459311558
          classification: P
          radius: 1219.267818330058
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 168372
        temperature: 262
commSatellite: null
assets: {}
