apiVersion: solarSystem/v1
kind: solarSystems
name: Achernar
description: A solar system named Achernar
position:
  x: -16362004.30675978
  'y': 61477904.51101589
  z: 36022160.83515239
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Achernar
stars:
  - name: Achernar A
    description: ''
    tags: []
    solarMass: 6
    age: 148694912910
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.78
    temperature: 15000
    satellite:
      axialTilt: 0
      semiMajorAxis: 81.36
      eccentricity: 0
      inclination: 0
      orbitalArc: 161
      showOrbit: false
      parentId: Achernar
  - name: Achernar B
    description: ''
    tags: []
    solarMass: 6
    age: 148694912910
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.78
    temperature: 15000
    satellite:
      axialTilt: 0
      semiMajorAxis: 81.36
      eccentricity: 0
      inclination: 0
      orbitalArc: 341
      showOrbit: false
      parentId: Achernar
planets:
  - name: Achernar 1
    description: ''
    tags: []
    satellite:
      axialTilt: 2.81
      semiMajorAxis: 1818937204.3333333
      eccentricity: 0.02
      inclination: 1.65
      orbitalArc: 221
      showOrbit: true
      parentId: Achernar
    isPlanet:
      age: 4732884087
      classification: H
      radius: 7325
      terranMass: 0.004209606544506633
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 752
    satellites:
      - name: Achernar 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 26.45
          semiMajorAxis: 480861.2501826582
          eccentricity: 0
          inclination: 1.42
          orbitalArc: 249
          showOrbit: true
          parentId: Achernar 1
        isPlanet:
          age: 372519592
          classification: C
          radius: 1054.5202854882855
          terranMass: 1.3000000980525432
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 48
  - name: Achernar 2
    description: ''
    tags: []
    satellite:
      axialTilt: 6.25
      semiMajorAxis: 2813433577.1111107
      eccentricity: 0.01
      inclination: 0.35
      orbitalArc: 51
      showOrbit: true
      parentId: Achernar
    isPlanet:
      age: 371544500
      classification: D
      radius: 304
      terranMass: 0.0019780142148695516
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 362
    satellites: []
  - name: Achernar 3
    description: ''
    tags: []
    satellite:
      axialTilt: 38.75
      semiMajorAxis: 4019670035
      eccentricity: 0.01
      inclination: 0.76
      orbitalArc: 139
      showOrbit: true
      parentId: Achernar
    isPlanet:
      age: 4698047583
      classification: L
      radius: 4312
      terranMass: 0.0023276695912963765
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 21935
    temperature: 256
    satellites: []
commSatellite: null
assets: {}
