apiVersion: solarSystem/v1
kind: solarSystems
name: Okab
description: A solar system named Okab
position:
  x: 75947194.86113589
  'y': -19533853.62308244
  z: 22284122.639149234
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Okab
stars:
  - name: Okab A
    description: ''
    tags: []
    solarMass: 2.53
    age: 3369485225569
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.762
    temperature: 8680
    satellite:
      axialTilt: 0
      semiMajorAxis: 33.144
      eccentricity: 0
      inclination: 0
      orbitalArc: 264
      showOrbit: false
      parentId: Okab
  - name: Okab B
    description: ''
    tags: []
    solarMass: 2.53
    age: 3369485225569
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.762
    temperature: 8680
    satellite:
      axialTilt: 0
      semiMajorAxis: 33.144
      eccentricity: 0
      inclination: 0
      orbitalArc: 444
      showOrbit: false
      parentId: Okab
planets:
  - name: Okab 1
    description: ''
    tags: []
    satellite:
      axialTilt: 13.73
      semiMajorAxis: 391258943
      eccentricity: 0.01
      inclination: 0.43
      orbitalArc: 17
      showOrbit: true
      parentId: Okab
    isPlanet:
      age: 9031813302
      classification: H
      radius: 4935
      terranMass: 0.024463552322343728
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 650
    satellites: []
  - name: Okab 2
    description: ''
    tags: []
    satellite:
      axialTilt: 33.62
      semiMajorAxis: 719709058
      eccentricity: 0
      inclination: 1.31
      orbitalArc: 77
      showOrbit: true
      parentId: Okab
    isPlanet:
      age: 3687755392
      classification: P
      radius: 6217
      terranMass: 0.007109772879539471
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 29228
    temperature: 258
    satellites:
      - name: Okab 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 20.42
          semiMajorAxis: 234816.52979713172
          eccentricity: 0.01
          inclination: 0.48
          orbitalArc: 96
          showOrbit: true
          parentId: Okab 2
        isPlanet:
          age: 4990521772
          classification: K
          radius: 645.8022716393816
          terranMass: 2.3000000673299574
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 11768
        temperature: 183
      - name: Okab 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 22.07
          semiMajorAxis: 453024.7899289581
          eccentricity: 0.02
          inclination: 0.93
          orbitalArc: 97
          showOrbit: true
          parentId: Okab 2
        isPlanet:
          age: 7456650724
          classification: P
          radius: 1268.9770026021235
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 110003
        temperature: 262
  - name: Okab 3
    description: ''
    tags: []
    satellite:
      axialTilt: 12.13
      semiMajorAxis: 999781796
      eccentricity: 0.01
      inclination: 1.22
      orbitalArc: 353
      showOrbit: true
      parentId: Okab
    isPlanet:
      age: 6326879998
      classification: K
      radius: 3361
      terranMass: 0.003146339386958997
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 31058
    temperature: 118
    satellites: []
commSatellite: null
assets: {}
