apiVersion: solarSystem/v1
kind: solarSystems
name: Regulus
description: A solar system named Regulus
position:
  x: -19096972.046368122
  'y': -8648361.270616341
  z: -36057192.841866106
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Regulus
stars:
  - name: Regulus A
    description: ''
    tags: []
    solarMass: 4.15
    age: 918975458530
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.21
    temperature: 11010
    satellite:
      axialTilt: 0
      semiMajorAxis: 50.519999999999996
      eccentricity: 0
      inclination: 0
      orbitalArc: 318
      showOrbit: false
      parentId: Regulus
  - name: Regulus B
    description: ''
    tags: []
    solarMass: 4.15
    age: 918975458530
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.21
    temperature: 11010
    satellite:
      axialTilt: 0
      semiMajorAxis: 50.519999999999996
      eccentricity: 0
      inclination: 0
      orbitalArc: 498
      showOrbit: false
      parentId: Regulus
planets:
  - name: Regulus 1
    description: ''
    tags: []
    satellite:
      axialTilt: 1.87
      semiMajorAxis: 1610578404.0000002
      eccentricity: 0
      inclination: 0.53
      orbitalArc: 285
      showOrbit: true
      parentId: Regulus
    isPlanet:
      age: 608484894
      classification: D
      radius: 420
      terranMass: 0.0032946620878470515
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 297
    satellites: []
  - name: Regulus 2
    description: ''
    tags: []
    satellite:
      axialTilt: 36.8
      semiMajorAxis: 2566252918.3333335
      eccentricity: 0.01
      inclination: 1.24
      orbitalArc: 125
      showOrbit: true
      parentId: Regulus
    isPlanet:
      age: 594850688
      classification: E
      radius: 6396
      terranMass: 0.0011249534583193824
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 1252
    satellites: []
  - name: Regulus 3
    description: ''
    tags: []
    satellite:
      axialTilt: 27.06
      semiMajorAxis: 2941852996.6666684
      eccentricity: 0
      inclination: 1
      orbitalArc: 9
      showOrbit: true
      parentId: Regulus
    isPlanet:
      age: 1216292925
      classification: E
      radius: 6678
      terranMass: 0.02598102827474725
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Volcanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 1090
    satellites:
      - name: Regulus 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 36.29
          semiMajorAxis: 466034.61179685785
          eccentricity: 0.01
          inclination: 0.8
          orbitalArc: 331
          showOrbit: true
          parentId: Regulus 3
        isPlanet:
          age: 8259951659
          classification: P
          radius: 1002.2249716061459
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 116821
        temperature: 269
  - name: Regulus 4
    description: ''
    tags: []
    satellite:
      axialTilt: 32.97
      semiMajorAxis: 3187822821.4444456
      eccentricity: 0.01
      inclination: 0.94
      orbitalArc: 43
      showOrbit: true
      parentId: Regulus
    isPlanet:
      age: 656443982
      classification: E
      radius: 5023
      terranMass: 0.01086205794268339
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Volcanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 1231
    satellites: []
  - name: Regulus 5
    description: ''
    tags: []
    satellite:
      axialTilt: 34.89
      semiMajorAxis: 3516726577
      eccentricity: 0.01
      inclination: 0.14
      orbitalArc: 51
      showOrbit: true
      parentId: Regulus
    isPlanet:
      age: 424399089
      classification: C
      radius: 4617
      terranMass: 0.0068265510010531855
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 47
    satellites:
      - name: Regulus 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 36.2
          semiMajorAxis: 236264.6384298223
          eccentricity: 0.01
          inclination: 1.05
          orbitalArc: 273
          showOrbit: true
          parentId: Regulus 5
        isPlanet:
          age: 423104688
          classification: D
          radius: 557.2279208250526
          terranMass: 0.769999674241632
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 302
commSatellite: null
assets: {}
