apiVersion: solarSystem/v1
kind: solarSystems
name: Shaula
description: A solar system named Shaula
position:
  x: 237517817.0488767
  'y': 180856024.10362676
  z: -27472645.624415725
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Shaula
stars:
  - name: Shaula A
    description: ''
    tags: []
    solarMass: 10.4
    age: 19827923962
    spectralType: B
    hue: 200
    isWhite: false
    radius: 8.8
    temperature: 25000
    satellite:
      axialTilt: 0
      semiMajorAxis: 105.60000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 235
      showOrbit: false
      parentId: Shaula
  - name: Shaula B
    description: ''
    tags: []
    solarMass: 10.4
    age: 19827923962
    spectralType: B
    hue: 200
    isWhite: false
    radius: 8.8
    temperature: 25000
    satellite:
      axialTilt: 0
      semiMajorAxis: 105.60000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 415
      showOrbit: false
      parentId: Shaula
planets:
  - name: Shaula 1
    description: ''
    tags: []
    satellite:
      axialTilt: 26.53
      semiMajorAxis: 11387361506
      eccentricity: 0.01
      inclination: 1.09
      orbitalArc: 181
      showOrbit: true
      parentId: Shaula
    isPlanet:
      age: 146339941
      classification: C
      radius: 4640
      terranMass: 0.007017747939082548
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 38
    satellites:
      - name: Shaula 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.98
          semiMajorAxis: 144794.72327158842
          eccentricity: 0
          inclination: 1.65
          orbitalArc: 119
          showOrbit: true
          parentId: Shaula 1
        isPlanet:
          age: 232695165
          classification: C
          radius: 284.0641378546283
          terranMass: 1.4000000929825909
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 36
      - name: Shaula 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 10.32
          semiMajorAxis: 256311.0692781211
          eccentricity: 0.01
          inclination: 0.39
          orbitalArc: 103
          showOrbit: true
          parentId: Shaula 1
        isPlanet:
          age: 4074427793
          classification: O
          radius: 773.9622565242374
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 47065972
        temperature: 295
      - name: Shaula 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 24.25
          semiMajorAxis: 336773.4657704135
          eccentricity: 0.02
          inclination: 1.91
          orbitalArc: 12
          showOrbit: true
          parentId: Shaula 1
        isPlanet:
          age: 483554611
          classification: E
          radius: 973.3337160994611
          terranMass: 0.5000000033102986
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1212
commSatellite: null
assets: {}
