apiVersion: solarSystem/v1
kind: solarSystems
name: Kang
description: A solar system named Kang
position:
  x: 72307752.92911741
  'y': 23920352.235269863
  z: -110397130.24948767
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Kang
stars:
  - name: Kang A
    description: ''
    tags: []
    solarMass: 1.46
    age: 405414382294
    spectralType: K
    hue: 30
    isWhite: false
    radius: 25.41
    temperature: 4235
    satellite:
      axialTilt: 0
      semiMajorAxis: 304.92
      eccentricity: 0
      inclination: 0
      orbitalArc: 171
      showOrbit: false
      parentId: Kang
  - name: Kang B
    description: ''
    tags: []
    solarMass: 1.46
    age: 405414382294
    spectralType: K
    hue: 30
    isWhite: false
    radius: 25.41
    temperature: 4235
    satellite:
      axialTilt: 0
      semiMajorAxis: 304.92
      eccentricity: 0
      inclination: 0
      orbitalArc: 351
      showOrbit: false
      parentId: Kang
planets:
  - name: Kang 1
    description: ''
    tags: []
    satellite:
      axialTilt: 23.78
      semiMajorAxis: 1038207813.333334
      eccentricity: 0.01
      inclination: 1.12
      orbitalArc: 216
      showOrbit: true
      parentId: Kang
    isPlanet:
      age: 489103448
      classification: D
      radius: 487
      terranMass: 0.017209343806211277
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 168
    satellites: []
  - name: Kang 2
    description: ''
    tags: []
    satellite:
      axialTilt: 27.1
      semiMajorAxis: 2216640756.111111
      eccentricity: 0.02
      inclination: 1.42
      orbitalArc: 2
      showOrbit: true
      parentId: Kang
    isPlanet:
      age: 8988890993
      classification: P
      radius: 5010
      terranMass: 0.006904945388530601
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 130703
    temperature: 257
    satellites:
      - name: Kang 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 15.51
          semiMajorAxis: 156800.8585507719
          eccentricity: 0.02
          inclination: 0.18
          orbitalArc: 121
          showOrbit: true
          parentId: Kang 2
        isPlanet:
          age: 4219574136
          classification: K
          radius: 517.0361328510419
          terranMass: 0.10000007001389646
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 19678
        temperature: 145
      - name: Kang 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 22.51
          semiMajorAxis: 257249.3067360191
          eccentricity: 0.02
          inclination: 0.51
          orbitalArc: 69
          showOrbit: true
          parentId: Kang 2
        isPlanet:
          age: 9751192326
          classification: P
          radius: 1028.9972269440764
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 57605
        temperature: 264
  - name: Kang 3
    description: ''
    tags: []
    satellite:
      axialTilt: 1.77
      semiMajorAxis: 3679085608
      eccentricity: 0
      inclination: 0.46
      orbitalArc: 53
      showOrbit: true
      parentId: Kang
    isPlanet:
      age: 124090101
      classification: D
      radius: 463
      terranMass: 0.004067385996344727
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 187
    satellites: []
commSatellite: null
assets: {}
