apiVersion: solarSystem/v1
kind: solarSystems
name: Dubhe
description: A solar system named Dubhe
position:
  x: -7442795.471926421
  'y': -56988088.12235291
  z: -29701131.419668358
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Dubhe
stars:
  - name: Dubhe A
    description: ''
    tags: []
    solarMass: 3.7
    age: 533717495776
    spectralType: K
    hue: 30
    isWhite: false
    radius: 27.33
    temperature: 4810
    satellite:
      axialTilt: 0
      semiMajorAxis: 327.96
      eccentricity: 0
      inclination: 0
      orbitalArc: 86
      showOrbit: false
      parentId: Dubhe
  - name: Dubhe B
    description: ''
    tags: []
    solarMass: 3.7
    age: 533717495776
    spectralType: K
    hue: 30
    isWhite: false
    radius: 27.33
    temperature: 4810
    satellite:
      axialTilt: 0
      semiMajorAxis: 327.96
      eccentricity: 0
      inclination: 0
      orbitalArc: 266
      showOrbit: false
      parentId: Dubhe
planets:
  - name: Dubhe 1
    description: ''
    tags: []
    satellite:
      axialTilt: 12.57
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 0.72
      orbitalArc: 63
      showOrbit: true
      parentId: Dubhe
    isPlanet:
      age: 669681880
      classification: D
      radius: 187
      terranMass: 0.002259793727451432
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 263
    satellites: []
commSatellite: null
assets: {}
