apiVersion: solarSystem/v1
kind: solarSystems
name: Arkab Prior
description: A solar system named Arkab Prior
position:
  x: 108891877.61359863
  'y': 114198242.75329125
  z: 41058984.4931097
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Arkab Prior
stars:
  - name: Arkab Prior A
    description: ''
    tags: []
    solarMass: 3.67
    age: 1387986800268
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.73
    temperature: 11960
    satellite:
      axialTilt: 0
      semiMajorAxis: 32.76
      eccentricity: 0
      inclination: 0
      orbitalArc: 21
      showOrbit: false
      parentId: Arkab Prior
  - name: Arkab Prior B
    description: ''
    tags: []
    solarMass: 3.67
    age: 1387986800268
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.73
    temperature: 11960
    satellite:
      axialTilt: 0
      semiMajorAxis: 32.76
      eccentricity: 0
      inclination: 0
      orbitalArc: 201
      showOrbit: false
      parentId: Arkab Prior
planets:
  - name: Arkab Prior 1
    description: ''
    tags: []
    satellite:
      axialTilt: 17.64
      semiMajorAxis: 1793137138
      eccentricity: 0
      inclination: 0.75
      orbitalArc: 80
      showOrbit: true
      parentId: Arkab Prior
    isPlanet:
      age: 8316655804
      classification: J
      radius: 38351
      terranMass: 0.6229555951775879
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 229
    satellites:
      - name: Arkab Prior 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 24.16
          semiMajorAxis: 1707084.1856309795
          eccentricity: 0.02
          inclination: 1.31
          orbitalArc: 94
          showOrbit: true
          parentId: Arkab Prior 1
        isPlanet:
          age: 908870950
          classification: D
          radius: 6515.588494774731
          terranMass: 0.9199999395270042
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 252
  - name: Arkab Prior 2
    description: ''
    tags: []
    satellite:
      axialTilt: 33.48
      semiMajorAxis: 3874182708
      eccentricity: 0.01
      inclination: 1.48
      orbitalArc: 270
      showOrbit: true
      parentId: Arkab Prior
    isPlanet:
      age: 2287317969
      classification: I
      radius: 3526670
      terranMass: 12.171102182454455
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_jupiter.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 164
    satellites:
      - name: Arkab Prior 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.8
          semiMajorAxis: 187064607.40056628
          eccentricity: 0
          inclination: 0.95
          orbitalArc: 93
          showOrbit: true
          parentId: Arkab Prior 2
        isPlanet:
          age: 7527602387
          classification: P
          radius: 580945.9857160443
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 185198
        temperature: 256
commSatellite: null
assets: {}
