apiVersion: ships/v1
kind: ships
name: Alotech Frigate
nameTemplate: '{~Alpha,Bravo,Charlie,Delta,Echo} {~1,2,3,4,5,6,7,8,9,10}'
description: Exploration vessels
category: Cruiser
tags: []
assets:
  logo: /plugins/Thorium Default/ships/Alotech Frigate/assets/logo.svg
  model: /plugins/Thorium Default/ships/Alotech Frigate/assets/model.glb
  vanity: /plugins/Thorium Default/ships/Alotech Frigate/assets/vanity.png
  topView: /plugins/Thorium Default/ships/Alotech Frigate/assets/top.png
  sideView: /plugins/Thorium Default/ships/Alotech Frigate/assets/side.png
mass: 700000000
length: 350
shipSystems: []
theme:
  pluginId: Thorium Default
  themeId: Default
decks: []
deckEdges: []
cargoContainers: 4
cargoContainerVolume: 4000
