apiVersion: solarSystem/v1
kind: solarSystems
name: Diphda
description: A solar system named Diphda
position:
  x: -9079065.154309317
  'y': 15591709.280001182
  z: 47158534.74311232
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Diphda
stars:
  - name: Diphda A
    description: ''
    tags: []
    solarMass: 3.5
    age: 1247101746995
    spectralType: K
    hue: 30
    isWhite: false
    radius: 17.52
    temperature: 4792
    satellite:
      axialTilt: 0
      semiMajorAxis: 210.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 339
      showOrbit: false
      parentId: Diphda
  - name: Diphda B
    description: ''
    tags: []
    solarMass: 3.5
    age: 1247101746995
    spectralType: K
    hue: 30
    isWhite: false
    radius: 17.52
    temperature: 4792
    satellite:
      axialTilt: 0
      semiMajorAxis: 210.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 519
      showOrbit: false
      parentId: Diphda
planets:
  - name: Diphda 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.67
      semiMajorAxis: 1581665066.666667
      eccentricity: 0.01
      inclination: 1.85
      orbitalArc: 262
      showOrbit: true
      parentId: Diphda
    isPlanet:
      age: 8990834286
      classification: L
      radius: 4684
      terranMass: 0.013171078463357558
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 11150
    temperature: 219
    satellites:
      - name: Diphda 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 17.57
          semiMajorAxis: 320055.7858679377
          eccentricity: 0.01
          inclination: 1.03
          orbitalArc: 56
          showOrbit: true
          parentId: Diphda 1
        isPlanet:
          age: 112701144
          classification: D
          radius: 1119.0761743634187
          terranMass: 0.9599999488710489
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 344
  - name: Diphda 2
    description: ''
    tags: []
    satellite:
      axialTilt: 20.99
      semiMajorAxis: 2928035250.111111
      eccentricity: 0.02
      inclination: 0.96
      orbitalArc: 98
      showOrbit: true
      parentId: Diphda
    isPlanet:
      age: 5484390417
      classification: 'N'
      radius: 7323
      terranMass: 0.0016154838106863863
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 93108000
    temperature: 626
    satellites: []
  - name: Diphda 3
    description: ''
    tags: []
    satellite:
      axialTilt: 14.49
      semiMajorAxis: 3899759119
      eccentricity: 0.02
      inclination: 1.82
      orbitalArc: 169
      showOrbit: true
      parentId: Diphda
    isPlanet:
      age: 659155152
      classification: D
      radius: 435
      terranMass: 0.00037418310127854126
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 175
    satellites: []
commSatellite: null
assets: {}
