apiVersion: solarSystem/v1
kind: solarSystems
name: Arkab Posterior
description: A solar system named Arkab Posterior
position:
  x: 46748949.6592605
  'y': 49661467.91950316
  z: 17762685.779061846
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Arkab Posterior
stars:
  - name: Arkab Posterior A
    description: ''
    tags: []
    solarMass: 1.43
    age: 3350660225949
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.17
    temperature: 7035
    satellite:
      axialTilt: 0
      semiMajorAxis: 38.04
      eccentricity: 0
      inclination: 0
      orbitalArc: 197
      showOrbit: false
      parentId: Arkab Posterior
  - name: Arkab Posterior B
    description: ''
    tags: []
    solarMass: 1.43
    age: 3350660225949
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.17
    temperature: 7035
    satellite:
      axialTilt: 0
      semiMajorAxis: 38.04
      eccentricity: 0
      inclination: 0
      orbitalArc: 377
      showOrbit: false
      parentId: Arkab Posterior
planets:
  - name: Arkab Posterior 1
    description: ''
    tags: []
    satellite:
      axialTilt: 26.78
      semiMajorAxis: 438960886
      eccentricity: 0.01
      inclination: 1.47
      orbitalArc: 208
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 9152476995
      classification: 'N'
      radius: 7372
      terranMass: 0.005052030188392854
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 235354243
    temperature: 395
    satellites:
      - name: Arkab Posterior 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.13
          semiMajorAxis: 197748.42757928002
          eccentricity: 0.01
          inclination: 1.12
          orbitalArc: 87
          showOrbit: true
          parentId: Arkab Posterior 1
        isPlanet:
          age: 6275891438
          classification: K
          radius: 754.7649907606108
          terranMass: 0.5000001109694633
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 25742
        temperature: 231
  - name: Arkab Posterior 2
    description: ''
    tags: []
    satellite:
      axialTilt: 24.52
      semiMajorAxis: 635459054
      eccentricity: 0
      inclination: 0.88
      orbitalArc: 253
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 266676469
      classification: D
      radius: 406
      terranMass: 0.003933941635419086
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 279
    satellites: []
  - name: Arkab Posterior 3
    description: ''
    tags: []
    satellite:
      axialTilt: 19.05
      semiMajorAxis: 1589770434.3333323
      eccentricity: 0
      inclination: 1.07
      orbitalArc: 86
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 7778995736
      classification: 'N'
      radius: 7463
      terranMass: 0.005530264928944005
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 517426673
    temperature: 575
    satellites:
      - name: Arkab Posterior 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 5.32
          semiMajorAxis: 196443.33902050857
          eccentricity: 0.01
          inclination: 0.08
          orbitalArc: 153
          showOrbit: true
          parentId: Arkab Posterior 3
        isPlanet:
          age: 7718855313
          classification: H
          radius: 1185.9444820465276
          terranMass: 2.3000001112149446
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 0
        temperature: 736
      - name: Arkab Posterior 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 22.5
          semiMajorAxis: 348496.83889633266
          eccentricity: 0
          inclination: 0.28
          orbitalArc: 338
          showOrbit: true
          parentId: Arkab Posterior 3
        isPlanet:
          age: 7194653064
          classification: P
          radius: 1116.977047744656
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 91504
        temperature: 261
  - name: Arkab Posterior 4
    description: ''
    tags: []
    satellite:
      axialTilt: 7.38
      semiMajorAxis: 2262818413.8888865
      eccentricity: 0.01
      inclination: 0.49
      orbitalArc: 26
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 7247137927
      classification: J
      radius: 41222
      terranMass: 0.9953300250753131
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 129
    satellites:
      - name: Arkab Posterior 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 35.44
          semiMajorAxis: 2105565.644301708
          eccentricity: 0
          inclination: 1.34
          orbitalArc: 299
          showOrbit: true
          parentId: Arkab Posterior 4
        isPlanet:
          age: 4442956860
          classification: P
          radius: 3111.218747084662
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 68755
        temperature: 267
      - name: Arkab Posterior 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 38.35
          semiMajorAxis: 3207351.835910857
          eccentricity: 0.01
          inclination: 1.67
          orbitalArc: 169
          showOrbit: true
          parentId: Arkab Posterior 4
        isPlanet:
          age: 4198623386
          classification: P
          radius: 8161.200600282079
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 63195
        temperature: 265
  - name: Arkab Posterior 5
    description: ''
    tags: []
    satellite:
      axialTilt: 24.01
      semiMajorAxis: 3040335606.4814763
      eccentricity: 0.01
      inclination: 1.73
      orbitalArc: 316
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 4974037271
      classification: J
      radius: 50359
      terranMass: 1.6208512399661943
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 213
    satellites:
      - name: Arkab Posterior 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.06
          semiMajorAxis: 2281574.768880073
          eccentricity: 0.01
          inclination: 1.88
          orbitalArc: 21
          showOrbit: true
          parentId: Arkab Posterior 5
        isPlanet:
          age: 4976846111
          classification: K
          radius: 8609.11688082243
          terranMass: 1.3000000234528284
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 29901
        temperature: 267
      - name: Arkab Posterior 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 21.33
          semiMajorAxis: 4572712.970758692
          eccentricity: 0.02
          inclination: 1.39
          orbitalArc: 64
          showOrbit: true
          parentId: Arkab Posterior 5
        isPlanet:
          age: 756852619
          classification: E
          radius: 9145.425941517386
          terranMass: 0.5000001063208387
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1355
  - name: Arkab Posterior 6
    description: ''
    tags: []
    satellite:
      axialTilt: 17.2
      semiMajorAxis: 3849747088
      eccentricity: 0
      inclination: 1.21
      orbitalArc: 222
      showOrbit: true
      parentId: Arkab Posterior
    isPlanet:
      age: 3128729382
      classification: J
      radius: 34718
      terranMass: 0.18526022934477318
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 183
    satellites:
      - name: Arkab Posterior 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 23.87
          semiMajorAxis: 997695.074408585
          eccentricity: 0.01
          inclination: 0.67
          orbitalArc: 25
          showOrbit: true
          parentId: Arkab Posterior 6
        isPlanet:
          age: 198604760
          classification: D
          radius: 3680.3426726719
          terranMass: 1.1399997368911066
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 265
      - name: Arkab Posterior 6b
        description: ''
        tags: []
        satellite:
          axialTilt: 8.96
          semiMajorAxis: 1742398.4222534292
          eccentricity: 0.01
          inclination: 1.86
          orbitalArc: 61
          showOrbit: true
          parentId: Arkab Posterior 6
        isPlanet:
          age: 6487471773
          classification: H
          radius: 3942.0778784014237
          terranMass: 1.9000000695368109
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 712
commSatellite: null
assets: {}
