apiVersion: solarSystem/v1
kind: solarSystems
name: Paikauhale
description: A solar system named Paikauhale
position:
  x: 211624406.55670792
  'y': 121650523.50476621
  z: -81359457.39662327
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Paikauhale
stars:
  - name: Paikauhale A
    description: ''
    tags: []
    solarMass: 15
    age: 30247173533
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.42
    temperature: 28862
    satellite:
      axialTilt: 0
      semiMajorAxis: 77.03999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 166
      showOrbit: false
      parentId: Paikauhale
  - name: Paikauhale B
    description: ''
    tags: []
    solarMass: 15
    age: 30247173533
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.42
    temperature: 28862
    satellite:
      axialTilt: 0
      semiMajorAxis: 77.03999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 346
      showOrbit: false
      parentId: Paikauhale
planets:
  - name: Paikauhale 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.91
      semiMajorAxis: 3502896149.6666665
      eccentricity: 0.01
      inclination: 1.45
      orbitalArc: 59
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 8272789775
      classification: J
      radius: 54162
      terranMass: 0.130333608005972
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 281
    satellites: []
  - name: Paikauhale 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.41
      semiMajorAxis: 5138911891.111111
      eccentricity: 0.02
      inclination: 1.08
      orbitalArc: 236
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 67924694
      classification: D
      radius: 273
      terranMass: 0.004778635704869422
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 360
    satellites: []
  - name: Paikauhale 3
    description: ''
    tags: []
    satellite:
      axialTilt: 24.68
      semiMajorAxis: 8402945374.740741
      eccentricity: 0
      inclination: 0.72
      orbitalArc: 270
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 305828348
      classification: C
      radius: 2557
      terranMass: 0.004522424644367745
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 50
    satellites:
      - name: Paikauhale 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.43
          semiMajorAxis: 60904.2457086815
          eccentricity: 0
          inclination: 1.15
          orbitalArc: 142
          showOrbit: true
          parentId: Paikauhale 3
        isPlanet:
          age: 341314469
          classification: D
          radius: 306.80714099003404
          terranMass: 1.049999795710381
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 176
      - name: Paikauhale 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 34.77
          semiMajorAxis: 111102.80255417117
          eccentricity: 0
          inclination: 1.79
          orbitalArc: 130
          showOrbit: true
          parentId: Paikauhale 3
        isPlanet:
          age: 758521104
          classification: C
          radius: 241.003910095816
          terranMass: 0.6000001429200362
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 37
  - name: Paikauhale 4
    description: ''
    tags: []
    satellite:
      axialTilt: 27.17
      semiMajorAxis: 10321558494.740742
      eccentricity: 0.02
      inclination: 0.69
      orbitalArc: 358
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 9924865082
      classification: L
      radius: 7298
      terranMass: 0.0066982768911660814
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 3900
    temperature: 196
    satellites:
      - name: Paikauhale 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 33.35
          semiMajorAxis: 348409.6332278624
          eccentricity: 0.02
          inclination: 0.44
          orbitalArc: 71
          showOrbit: true
          parentId: Paikauhale 4
        isPlanet:
          age: 50909103
          classification: D
          radius: 1069.0211415257122
          terranMass: 0.5599997145319742
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 349
      - name: Paikauhale 4b
        description: ''
        tags: []
        satellite:
          axialTilt: 27.22
          semiMajorAxis: 777237.5403228864
          eccentricity: 0.01
          inclination: 1.96
          orbitalArc: 94
          showOrbit: true
          parentId: Paikauhale 4
        isPlanet:
          age: 4924031642
          classification: 'N'
          radius: 1697.0251972115425
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 275404694
        temperature: 556
  - name: Paikauhale 5
    description: ''
    tags: []
    satellite:
      axialTilt: 6.84
      semiMajorAxis: 11582992427.23457
      eccentricity: 0.02
      inclination: 1.83
      orbitalArc: 195
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 1684162246
      classification: E
      radius: 7216
      terranMass: 0.008516791355512667
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 1181
    satellites: []
  - name: Paikauhale 6
    description: ''
    tags: []
    satellite:
      axialTilt: 24.56
      semiMajorAxis: 12994578499.057611
      eccentricity: 0
      inclination: 1.11
      orbitalArc: 57
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 7193213397
      classification: L
      radius: 5114
      terranMass: 0.020026676030310882
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 20988
    temperature: 282
    satellites:
      - name: Paikauhale 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.54
          semiMajorAxis: 536348.2162714484
          eccentricity: 0.02
          inclination: 1.98
          orbitalArc: 114
          showOrbit: true
          parentId: Paikauhale 6
        isPlanet:
          age: 4419345903
          classification: K
          radius: 1178.7872885086779
          terranMass: 1.9000000030940702
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 9283
        temperature: 124
  - name: Paikauhale 7
    description: ''
    tags: []
    satellite:
      axialTilt: 5.51
      semiMajorAxis: 14405317051
      eccentricity: 0
      inclination: 1.64
      orbitalArc: 37
      showOrbit: true
      parentId: Paikauhale
    isPlanet:
      age: 2422924131
      classification: F
      radius: 7084
      terranMass: 0.013325158414935527
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 631
    satellites: []
commSatellite: null
assets: {}
