apiVersion: solarSystem/v1
kind: solarSystems
name: Atlas
description: A solar system named Atlas
position:
  x: -132101312.25521943
  'y': -92395648.9251726
  z: 159197131.18499655
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Atlas
stars:
  - name: Atlas A
    description: ''
    tags: []
    solarMass: 4.74
    age: 131873754090
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.9
    temperature: 13500
    satellite:
      axialTilt: 0
      semiMajorAxis: 94.80000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 5
      showOrbit: false
      parentId: Atlas
  - name: Atlas B
    description: ''
    tags: []
    solarMass: 4.74
    age: 131873754090
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.9
    temperature: 13500
    satellite:
      axialTilt: 0
      semiMajorAxis: 94.80000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 185
      showOrbit: false
      parentId: Atlas
planets:
  - name: Atlas 1
    description: ''
    tags: []
    satellite:
      axialTilt: 12.41
      semiMajorAxis: 1271431332
      eccentricity: 0.01
      inclination: 1.35
      orbitalArc: 138
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 862649844
      classification: D
      radius: 464
      terranMass: 0.0009786079648922753
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 148
    satellites: []
  - name: Atlas 2
    description: ''
    tags: []
    satellite:
      axialTilt: 1.82
      semiMajorAxis: 2811686144.3333335
      eccentricity: 0
      inclination: 0.9
      orbitalArc: 103
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 4112525426
      classification: B
      radius: 3766
      terranMass: 0.010867561863502578
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 477
    satellites:
      - name: Atlas 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 0.75
          semiMajorAxis: 182108.09445187112
          eccentricity: 0.01
          inclination: 0.47
          orbitalArc: 213
          showOrbit: true
          parentId: Atlas 2
        isPlanet:
          age: 5909928557
          classification: L
          radius: 687.2003564221552
          terranMass: 1.7000000762185814
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 12683
        temperature: 165
  - name: Atlas 3
    description: ''
    tags: []
    satellite:
      axialTilt: 21.14
      semiMajorAxis: 3567428085.2222214
      eccentricity: 0
      inclination: 1.14
      orbitalArc: 196
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 1545484569
      classification: A
      radius: 4750
      terranMass: 0.013205668584804658
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAcid.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 1536
    satellites:
      - name: Atlas 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 29.67
          semiMajorAxis: 424746.6956778101
          eccentricity: 0.02
          inclination: 1.77
          orbitalArc: 190
          showOrbit: true
          parentId: Atlas 3
        isPlanet:
          age: 420130409
          classification: D
          radius: 879.392744674555
          terranMass: 0.5099996632972428
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 390
  - name: Atlas 4
    description: ''
    tags: []
    satellite:
      axialTilt: 17.31
      semiMajorAxis: 3900509954.4444427
      eccentricity: 0.01
      inclination: 0.55
      orbitalArc: 175
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 723802237
      classification: D
      radius: 207
      terranMass: 0.024783369234153165
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 213
    satellites: []
  - name: Atlas 5
    description: ''
    tags: []
    satellite:
      axialTilt: 3.33
      semiMajorAxis: 4133771373.333326
      eccentricity: 0.02
      inclination: 0.12
      orbitalArc: 46
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 8909851005
      classification: K
      radius: 4002
      terranMass: 0.00010699559717643108
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 3153
    temperature: 154
    satellites:
      - name: Atlas 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 13.66
          semiMajorAxis: 241179.37235624227
          eccentricity: 0.01
          inclination: 0.23
          orbitalArc: 326
          showOrbit: true
          parentId: Atlas 5
        isPlanet:
          age: 5689732011
          classification: H
          radius: 834.53070019461
          terranMass: 2.100000071115418
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 0
        temperature: 633
  - name: Atlas 6
    description: ''
    tags: []
    satellite:
      axialTilt: 7.17
      semiMajorAxis: 4225640560.555542
      eccentricity: 0.01
      inclination: 1.5
      orbitalArc: 277
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 275306993
      classification: D
      radius: 349
      terranMass: 0.01643331139933288
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 228
    satellites: []
  - name: Atlas 7
    description: ''
    tags: []
    satellite:
      axialTilt: 9.14
      semiMajorAxis: 4375898406.185059
      eccentricity: 0.02
      inclination: 1.69
      orbitalArc: 317
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 521405257
      classification: D
      radius: 58
      terranMass: 0.0072433613911731705
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 179
    satellites: []
  - name: Atlas 8
    description: ''
    tags: []
    satellite:
      axialTilt: 20.76
      semiMajorAxis: 4458281560
      eccentricity: 0.01
      inclination: 0.16
      orbitalArc: 172
      showOrbit: true
      parentId: Atlas
    isPlanet:
      age: 2818173107
      classification: F
      radius: 6202
      terranMass: 0.02757694100949249
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 852
    satellites:
      - name: Atlas 8a
        description: ''
        tags: []
        satellite:
          axialTilt: 7.51
          semiMajorAxis: 155902.74443321698
          eccentricity: 0.01
          inclination: 0.17
          orbitalArc: 239
          showOrbit: true
          parentId: Atlas 8
        isPlanet:
          age: 1025332217
          classification: A
          radius: 1307.1230932767555
          terranMass: 0.1000006082888362
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1453
      - name: Atlas 8b
        description: ''
        tags: []
        satellite:
          axialTilt: 2.85
          semiMajorAxis: 376638.8790920014
          eccentricity: 0.01
          inclination: 1.51
          orbitalArc: 73
          showOrbit: true
          parentId: Atlas 8
        isPlanet:
          age: 648232117
          classification: D
          radius: 1354.8161118417318
          terranMass: 1.0499997014978464
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 182
commSatellite: null
assets: {}
