apiVersion: solarSystem/v1
kind: solarSystems
name: Acubens
description: A solar system named Acubens
position:
  x: -60084460.24295974
  'y': -17724308.08880789
  z: -59296310.97664348
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Acubens
stars:
  - name: Acubens A
    description: ''
    tags: []
    solarMass: 2.1
    age: 2277590099986
    spectralType: A
    hue: 180
    isWhite: true
    radius: 3.655
    temperature: 7943
    satellite:
      axialTilt: 0
      semiMajorAxis: 43.86
      eccentricity: 0
      inclination: 0
      orbitalArc: 172
      showOrbit: false
      parentId: Acubens
  - name: Acubens B
    description: ''
    tags: []
    solarMass: 2.1
    age: 2277590099986
    spectralType: A
    hue: 180
    isWhite: true
    radius: 3.655
    temperature: 7943
    satellite:
      axialTilt: 0
      semiMajorAxis: 43.86
      eccentricity: 0
      inclination: 0
      orbitalArc: 352
      showOrbit: false
      parentId: Acubens
planets:
  - name: Acubens 1
    description: ''
    tags: []
    satellite:
      axialTilt: 1.43
      semiMajorAxis: 415131836
      eccentricity: 0
      inclination: 0.36
      orbitalArc: 256
      showOrbit: true
      parentId: Acubens
    isPlanet:
      age: 20112931
      classification: D
      radius: 243
      terranMass: 0.0013017482740807305
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 342
    satellites: []
  - name: Acubens 2
    description: ''
    tags: []
    satellite:
      axialTilt: 2.78
      semiMajorAxis: 777055646
      eccentricity: 0.01
      inclination: 0.89
      orbitalArc: 355
      showOrbit: true
      parentId: Acubens
    isPlanet:
      age: 28366576
      classification: C
      radius: 2120
      terranMass: 0.022795314797158458
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 43
    satellites: []
  - name: Acubens 3
    description: ''
    tags: []
    satellite:
      axialTilt: 9.75
      semiMajorAxis: 1238977679
      eccentricity: 0.01
      inclination: 1.13
      orbitalArc: 202
      showOrbit: true
      parentId: Acubens
    isPlanet:
      age: 566636739
      classification: C
      radius: 2155
      terranMass: 0.011673659184984947
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 45
    satellites:
      - name: Acubens 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.78
          semiMajorAxis: 73168.44311315162
          eccentricity: 0.01
          inclination: 0.43
          orbitalArc: 211
          showOrbit: true
          parentId: Acubens 3
        isPlanet:
          age: 790486105
          classification: C
          radius: 185.5647631625912
          terranMass: 0.600000035553295
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 42
      - name: Acubens 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 15.26
          semiMajorAxis: 97799.101950642
          eccentricity: 0.01
          inclination: 1.46
          orbitalArc: 142
          showOrbit: true
          parentId: Acubens 3
        isPlanet:
          age: 159049085
          classification: D
          radius: 360.01238940976623
          terranMass: 0.7399998438484345
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 219
      - name: Acubens 3c
        description: ''
        tags: []
        satellite:
          axialTilt: 14.91
          semiMajorAxis: 137827.3729667655
          eccentricity: 0
          inclination: 0.26
          orbitalArc: 250
          showOrbit: true
          parentId: Acubens 3
        isPlanet:
          age: 9031959347
          classification: O
          radius: 310.42201118640884
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 71986392
        temperature: 293
commSatellite: null
assets: {}
