apiVersion: solarSystem/v1
kind: solarSystems
name: Sarin
description: A solar system named Sarin
position:
  x: 35157709.029910475
  'y': -16592718.564142233
  z: -6988223.707247598
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sarin
stars:
  - name: Sarin A
    description: ''
    tags: []
    solarMass: 2.4
    age: 3339141908902
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.2
    temperature: 9620
    satellite:
      axialTilt: 0
      semiMajorAxis: 26.400000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 286
      showOrbit: false
      parentId: Sarin
  - name: Sarin B
    description: ''
    tags: []
    solarMass: 2.4
    age: 3339141908902
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.2
    temperature: 9620
    satellite:
      axialTilt: 0
      semiMajorAxis: 26.400000000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 466
      showOrbit: false
      parentId: Sarin
planets:
  - name: Sarin 1
    description: ''
    tags: []
    satellite:
      axialTilt: 17.14
      semiMajorAxis: 187777426
      eccentricity: 0
      inclination: 1.66
      orbitalArc: 205
      showOrbit: true
      parentId: Sarin
    isPlanet:
      age: 802068073
      classification: D
      radius: 311
      terranMass: 0.00043111916852877654
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 335
    satellites: []
commSatellite: null
assets: {}
