apiVersion: solarSystem/v1
kind: solarSystems
name: Keid
description: A solar system named Keid
position:
  x: -7606280.241763127
  'y': 1138893.1421861951
  z: 3739786.3448140062
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Keid
stars:
  - name: Keid A
    description: ''
    tags: []
    solarMass: 0.78
    age: 100794627046233
    spectralType: K
    hue: 30
    isWhite: false
    radius: 0.804
    temperature: 5126
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.648
      eccentricity: 0
      inclination: 0
      orbitalArc: 101
      showOrbit: false
      parentId: Keid
  - name: Keid B
    description: ''
    tags: []
    solarMass: 0.78
    age: 100794627046233
    spectralType: K
    hue: 30
    isWhite: false
    radius: 0.804
    temperature: 5126
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.648
      eccentricity: 0
      inclination: 0
      orbitalArc: 281
      showOrbit: false
      parentId: Keid
planets:
  - name: Keid 1
    description: ''
    tags: []
    satellite:
      axialTilt: 12.28
      semiMajorAxis: 11874374
      eccentricity: 0.01
      inclination: 1
      orbitalArc: 238
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 608540463
      classification: D
      radius: 240
      terranMass: 0.025791201167970502
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 365
    satellites: []
  - name: Keid 2
    description: ''
    tags: []
    satellite:
      axialTilt: 25.79
      semiMajorAxis: 52544833.33333437
      eccentricity: 0.01
      inclination: 1.85
      orbitalArc: 58
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 809505935
      classification: D
      radius: 273
      terranMass: 0.00023912954282682145
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 266
    satellites: []
  - name: Keid 3
    description: ''
    tags: []
    satellite:
      axialTilt: 7.02
      semiMajorAxis: 82446372.66675642
      eccentricity: 0
      inclination: 1.42
      orbitalArc: 0
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 4504785065
      classification: L
      radius: 5509
      terranMass: 0.02627606715266969
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 26409
    temperature: 321
    satellites:
      - name: Keid 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 19.99
          semiMajorAxis: 201232.54264420702
          eccentricity: 0
          inclination: 1.77
          orbitalArc: 38
          showOrbit: true
          parentId: Keid 3
        isPlanet:
          age: 6553539194
          classification: M
          radius: 994.5014995175767
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial4.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 4620126502
        temperature: 298
      - name: Keid 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 3.69
          semiMajorAxis: 304758.628383744
          eccentricity: 0.01
          inclination: 0.74
          orbitalArc: 244
          showOrbit: true
          parentId: Keid 3
        isPlanet:
          age: 783499489
          classification: D
          radius: 810.3482625676315
          terranMass: 0.0699997848138587
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 303
      - name: Keid 3c
        description: ''
        tags: []
        satellite:
          axialTilt: 22.96
          semiMajorAxis: 457041.9316581603
          eccentricity: 0.01
          inclination: 0.84
          orbitalArc: 26
          showOrbit: true
          parentId: Keid 3
        isPlanet:
          age: 977970681
          classification: D
          radius: 978.6765131866388
          terranMass: 1.3299997736032678
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 361
  - name: Keid 4
    description: ''
    tags: []
    satellite:
      axialTilt: 3.79
      semiMajorAxis: 95980130.45563756
      eccentricity: 0.02
      inclination: 0.36
      orbitalArc: 106
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 9453698800
      classification: L
      radius: 2704
      terranMass: 0.0038920480449693953
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 7130
    temperature: 172
    satellites: []
  - name: Keid 5
    description: ''
    tags: []
    satellite:
      axialTilt: 30.52
      semiMajorAxis: 104499248.24306418
      eccentricity: 0.02
      inclination: 1.16
      orbitalArc: 218
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 9014134696
      classification: L
      radius: 4901
      terranMass: 0.0016127093062976113
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: null
    population: 41747
    temperature: 242
    satellites:
      - name: Keid 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 27.97
          semiMajorAxis: 262809.62213066436
          eccentricity: 0.01
          inclination: 1.06
          orbitalArc: 24
          showOrbit: true
          parentId: Keid 5
        isPlanet:
          age: 8937509924
          classification: P
          radius: 658.6707321570535
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 164967
        temperature: 270
  - name: Keid 6
    description: ''
    tags: []
    satellite:
      axialTilt: 31.19
      semiMajorAxis: 2041807430.8287094
      eccentricity: 0.01
      inclination: 0.77
      orbitalArc: 23
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 6458145488
      classification: 'N'
      radius: 5849
      terranMass: 0.025981845477009623
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 190445592
    temperature: 531
    satellites:
      - name: Keid 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.47
          semiMajorAxis: 443449.05468174774
          eccentricity: 0.02
          inclination: 1.78
          orbitalArc: 237
          showOrbit: true
          parentId: Keid 6
        isPlanet:
          age: 717700103
          classification: D
          radius: 892.2516190779633
          terranMass: 1.2399999734262044
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 374
  - name: Keid 7
    description: ''
    tags: []
    satellite:
      axialTilt: 35.22
      semiMajorAxis: 3199842133
      eccentricity: 0.01
      inclination: 0.59
      orbitalArc: 172
      showOrbit: true
      parentId: Keid
    isPlanet:
      age: 669816460
      classification: D
      radius: 360
      terranMass: 0.011691857781406188
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 259
    satellites: []
commSatellite: null
assets: {}
