apiVersion: stations/v1
kind: stationComplements
name: 3 Small
hasShipMap: false
stations:
  - name: Pilot
    description: Controls the movement of the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Flight Controls
        icon: /plugins/Thorium Default/stationComplements/assets/Pilot Card.svg
        component: Pilot
      - name: Navigation
        icon: /plugins/Thorium Default/stationComplements/assets/Navigation.svg
        component: Navigation
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Engineer
    description: Allocates ship power and manages the engines and reactors
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Sensors
        icon: /plugins/Thorium Default/stationComplements/assets/Sensors.svg
        component: Sensors
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
      - name: Remote Access
        icon: /plugins/Thorium Default/stationComplements/assets/RemoteAccess.svg
        component: RemoteAccess
        size: sm
    messageGroups: []
  - name: Tactical
    description: Defends the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Targeting
        icon: /plugins/Thorium Default/stationComplements/assets/Targeting.svg
        component: Targeting
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
flightMode: nova
assets: {}
