apiVersion: solarSystem/v1
kind: solarSystems
name: Tania Borealis
description: A solar system named Tania Borealis
position:
  x: -23073843.000224195
  'y': -49421729.49755748
  z: -47888483.22531901
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tania Borealis
stars:
  - name: Tania Borealis A
    description: ''
    tags: []
    solarMass: 2.11
    age: 3146245715855
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.3
    temperature: 9247
    satellite:
      axialTilt: 0
      semiMajorAxis: 27.599999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 68
      showOrbit: false
      parentId: Tania Borealis
  - name: Tania Borealis B
    description: ''
    tags: []
    solarMass: 2.11
    age: 3146245715855
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.3
    temperature: 9247
    satellite:
      axialTilt: 0
      semiMajorAxis: 27.599999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 248
      showOrbit: false
      parentId: Tania Borealis
planets:
  - name: Tania Borealis 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.46
      semiMajorAxis: 424100143.0000001
      eccentricity: 0
      inclination: 0.64
      orbitalArc: 240
      showOrbit: true
      parentId: Tania Borealis
    isPlanet:
      age: 1092618585
      classification: F
      radius: 7185
      terranMass: 0.019247357533722278
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 834
    satellites: []
  - name: Tania Borealis 2
    description: ''
    tags: []
    satellite:
      axialTilt: 13.48
      semiMajorAxis: 1128791803.3333337
      eccentricity: 0.02
      inclination: 1.73
      orbitalArc: 16
      showOrbit: true
      parentId: Tania Borealis
    isPlanet:
      age: 784621422
      classification: C
      radius: 4348
      terranMass: 0.00909026471725041
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 41
    satellites:
      - name: Tania Borealis 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 3.44
          semiMajorAxis: 195205.4635900663
          eccentricity: 0.02
          inclination: 0.63
          orbitalArc: 137
          showOrbit: true
          parentId: Tania Borealis 2
        isPlanet:
          age: 769620315
          classification: D
          radius: 603.2010027514308
          terranMass: 1.1099996394897975
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 154
      - name: Tania Borealis 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 0.46
          semiMajorAxis: 358731.3325143091
          eccentricity: 0.02
          inclination: 1.82
          orbitalArc: 111
          showOrbit: true
          parentId: Tania Borealis 2
        isPlanet:
          age: 3893665139
          classification: M
          radius: 930.0520560492417
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 2886572220
        temperature: 294
      - name: Tania Borealis 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 27.19
          semiMajorAxis: 457740.15337904176
          eccentricity: 0
          inclination: 0.41
          orbitalArc: 203
          showOrbit: true
          parentId: Tania Borealis 2
        isPlanet:
          age: 6119820251
          classification: H
          radius: 1042.6882764898446
          terranMass: 0.9000001049568128
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 754
  - name: Tania Borealis 3
    description: ''
    tags: []
    satellite:
      axialTilt: 7.5
      semiMajorAxis: 1719222968
      eccentricity: 0.01
      inclination: 1.76
      orbitalArc: 3
      showOrbit: true
      parentId: Tania Borealis
    isPlanet:
      age: 554358387
      classification: D
      radius: 59
      terranMass: 0.008492724684568577
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 396
    satellites: []
commSatellite: null
assets: {}
