apiVersion: solarSystem/v1
kind: solarSystems
name: Algenib
description: A solar system named Algenib
position:
  x: -11426511.483310638
  'y': -53724715.451881886
  z: 197633775.60603374
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Algenib
stars:
  - name: Algenib A
    description: ''
    tags: []
    solarMass: 8.8
    age: 74297416688
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.4
    temperature: 22000
    satellite:
      axialTilt: 0
      semiMajorAxis: 64.80000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 327
      showOrbit: false
      parentId: Algenib
  - name: Algenib B
    description: ''
    tags: []
    solarMass: 8.8
    age: 74297416688
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.4
    temperature: 22000
    satellite:
      axialTilt: 0
      semiMajorAxis: 64.80000000000001
      eccentricity: 0
      inclination: 0
      orbitalArc: 507
      showOrbit: false
      parentId: Algenib
planets: []
commSatellite: null
assets: {}
