apiVersion: solarSystem/v1
kind: solarSystems
name: Achird
description: A solar system named Achird
position:
  x: -1156802.615377128
  'y': -8644580.575547956
  z: 5316178.673824069
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Achird
stars:
  - name: Achird A
    description: ''
    tags: []
    solarMass: 1.0258
    age: 42388796883606
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.0336
    temperature: 6012
    satellite:
      axialTilt: 0
      semiMajorAxis: 12.403200000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 57
      showOrbit: false
      parentId: Achird
  - name: Achird B
    description: ''
    tags: []
    solarMass: 1.0258
    age: 42388796883606
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.0336
    temperature: 6012
    satellite:
      axialTilt: 0
      semiMajorAxis: 12.403200000000002
      eccentricity: 0
      inclination: 0
      orbitalArc: 237
      showOrbit: false
      parentId: Achird
planets:
  - name: Achird 1
    description: ''
    tags: []
    satellite:
      axialTilt: 23.76
      semiMajorAxis: 183919152.33333263
      eccentricity: 0
      inclination: 0.83
      orbitalArc: 0
      showOrbit: true
      parentId: Achird
    isPlanet:
      age: 7926729635
      classification: K
      radius: 3899
      terranMass: 0.0011660145077497205
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 7088
    temperature: 259
    satellites:
      - name: Achird 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.65
          semiMajorAxis: 118634.42675629881
          eccentricity: 0.01
          inclination: 1.26
          orbitalArc: 0
          showOrbit: true
          parentId: Achird 1
        isPlanet:
          age: 4326187713
          classification: L
          radius: 677.4338716241028
          terranMass: 1.3000001236150367
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 26624
        temperature: 284
      - name: Achird 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 34.79
          semiMajorAxis: 346706.5541719762
          eccentricity: 0.01
          inclination: 1.33
          orbitalArc: 168
          showOrbit: true
          parentId: Achird 1
        isPlanet:
          age: 6390473344
          classification: O
          radius: 815.7801274634735
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 376570218
        temperature: 295
  - name: Achird 2
    description: ''
    tags: []
    satellite:
      axialTilt: 35.84
      semiMajorAxis: 422251876.4444351
      eccentricity: 0.01
      inclination: 0.15
      orbitalArc: 98
      showOrbit: true
      parentId: Achird
    isPlanet:
      age: 5307159043
      classification: J
      radius: 44535
      terranMass: 0.40975083592574835
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 210
    satellites: []
  - name: Achird 3
    description: ''
    tags: []
    satellite:
      axialTilt: 24.65
      semiMajorAxis: 926724500.3333042
      eccentricity: 0.01
      inclination: 0.4
      orbitalArc: 43
      showOrbit: true
      parentId: Achird
    isPlanet:
      age: 5105611956
      classification: J
      radius: 49132
      terranMass: 1.2962629922249502
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 287
    satellites: []
  - name: Achird 4
    description: ''
    tags: []
    satellite:
      axialTilt: 1.33
      semiMajorAxis: 1851080706
      eccentricity: 0
      inclination: 0
      orbitalArc: 149
      showOrbit: true
      parentId: Achird
    isPlanet:
      age: 7931793080
      classification: J
      radius: 32585
      terranMass: 0.20857716864058215
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 268
    satellites: []
commSatellite: null
assets: {}
