apiVersion: solarSystem/v1
kind: solarSystems
name: Tarazed
description: A solar system named Tarazed
position:
  x: 182642335.1357158
  'y': -38263932.00069264
  z: 91320624.95219381
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tarazed
stars:
  - name: Tarazed A
    description: ''
    tags: []
    solarMass: 3.51
    age: 85154697373
    spectralType: K
    hue: 30
    isWhite: false
    radius: 91.81
    temperature: 4098
    satellite:
      axialTilt: 0
      semiMajorAxis: 1101.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 60
      showOrbit: false
      parentId: Tarazed
  - name: Tarazed B
    description: ''
    tags: []
    solarMass: 3.51
    age: 85154697373
    spectralType: K
    hue: 30
    isWhite: false
    radius: 91.81
    temperature: 4098
    satellite:
      axialTilt: 0
      semiMajorAxis: 1101.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 240
      showOrbit: false
      parentId: Tarazed
planets:
  - name: Tarazed 1
    description: ''
    tags: []
    satellite:
      axialTilt: 17.69
      semiMajorAxis: 1882980903.6666658
      eccentricity: 0
      inclination: 0.9
      orbitalArc: 281
      showOrbit: true
      parentId: Tarazed
    isPlanet:
      age: 615161896
      classification: A
      radius: 977
      terranMass: 0.003933104630346146
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 1696
    satellites: []
  - name: Tarazed 2
    description: ''
    tags: []
    satellite:
      axialTilt: 21.09
      semiMajorAxis: 2766841343.777777
      eccentricity: 0
      inclination: 1.64
      orbitalArc: 283
      showOrbit: true
      parentId: Tarazed
    isPlanet:
      age: 574013227
      classification: D
      radius: 405
      terranMass: 0.004850940696500456
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 293
    satellites: []
  - name: Tarazed 3
    description: ''
    tags: []
    satellite:
      axialTilt: 15.99
      semiMajorAxis: 3867407858.555556
      eccentricity: 0.01
      inclination: 1.68
      orbitalArc: 119
      showOrbit: true
      parentId: Tarazed
    isPlanet:
      age: 41800844
      classification: C
      radius: 1857
      terranMass: 0.00558577906007529
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 51
    satellites:
      - name: Tarazed 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.07
          semiMajorAxis: 123020.96746385732
          eccentricity: 0.01
          inclination: 1.39
          orbitalArc: 214
          showOrbit: true
          parentId: Tarazed 3
        isPlanet:
          age: 673766319
          classification: D
          radius: 262.30483467773416
          terranMass: 0.5699996945490844
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 292
  - name: Tarazed 4
    description: ''
    tags: []
    satellite:
      axialTilt: 16.8
      semiMajorAxis: 4748660599
      eccentricity: 0.01
      inclination: 1.97
      orbitalArc: 52
      showOrbit: true
      parentId: Tarazed
    isPlanet:
      age: 9602559276
      classification: 'N'
      radius: 6212
      terranMass: 0.012767982541180212
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_surface.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 155449312
    temperature: 369
    satellites: []
commSatellite: null
assets: {}
