apiVersion: solarSystem/v1
kind: solarSystems
name: Mizar
description: A solar system named Mizar
position:
  x: 8971554.011801094
  'y': -35684127.085949354
  z: -23394358.761680294
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Mizar
stars:
  - name: 'Mizar '
    description: ''
    tags: []
    solarMass: 2.2224
    age: 3391555994550
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.4
    temperature: 9000
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 293
      showOrbit: false
      parentId: Mizar
planets:
  - name: Mizar 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.77
      semiMajorAxis: 1068191996
      eccentricity: 0.01
      inclination: 1.39
      orbitalArc: 38
      showOrbit: true
      parentId: Mizar
    isPlanet:
      age: 7143622172
      classification: K
      radius: 4056
      terranMass: 0.014605449268458442
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: null
    population: 8616
    temperature: 245
    satellites:
      - name: Mizar 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.99
          semiMajorAxis: 216006.47036918675
          eccentricity: 0.01
          inclination: 1.79
          orbitalArc: 236
          showOrbit: true
          parentId: Mizar 1
        isPlanet:
          age: 314692029
          classification: C
          radius: 430.0890423840119
          terranMass: 1.4000000217060409
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 40
      - name: Mizar 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 11.73
          semiMajorAxis: 359398.0785218413
          eccentricity: 0.02
          inclination: 1.62
          orbitalArc: 63
          showOrbit: true
          parentId: Mizar 1
        isPlanet:
          age: 767955567
          classification: E
          radius: 1009.5451643871947
          terranMass: 2.10000014125488
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1189
commSatellite: null
assets: {}
