apiVersion: solarSystem/v1
kind: solarSystems
name: Chalawan
description: A solar system named Chalawan
position:
  x: -4797507.122317968
  'y': -15656334.25282779
  z: -17739172.34656497
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Chalawan
stars:
  - name: Chalawan A
    description: ''
    tags: []
    solarMass: 1.02
    age: 32527443338882
    spectralType: G
    hue: 45
    isWhite: false
    radius: 1.23
    temperature: 5880
    satellite:
      axialTilt: 0
      semiMajorAxis: 14.76
      eccentricity: 0
      inclination: 0
      orbitalArc: 292
      showOrbit: false
      parentId: Chalawan
  - name: Chalawan B
    description: ''
    tags: []
    solarMass: 1.02
    age: 32527443338882
    spectralType: G
    hue: 45
    isWhite: false
    radius: 1.23
    temperature: 5880
    satellite:
      axialTilt: 0
      semiMajorAxis: 14.76
      eccentricity: 0
      inclination: 0
      orbitalArc: 472
      showOrbit: false
      parentId: Chalawan
planets:
  - name: Chalawan 1
    description: ''
    tags: []
    satellite:
      axialTilt: 15.13
      semiMajorAxis: 1501396909.6666665
      eccentricity: 0.02
      inclination: 1.42
      orbitalArc: 40
      showOrbit: true
      parentId: Chalawan
    isPlanet:
      age: 8262884230
      classification: J
      radius: 41766
      terranMass: 1.9653954996588632
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 196
    satellites:
      - name: Chalawan 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 9.97
          semiMajorAxis: 1110163.765109709
          eccentricity: 0.02
          inclination: 0.85
          orbitalArc: 178
          showOrbit: true
          parentId: Chalawan 1
        isPlanet:
          age: 4618181961
          classification: P
          radius: 2883.542247038205
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 30735
        temperature: 260
  - name: Chalawan 2
    description: ''
    tags: []
    satellite:
      axialTilt: 37.87
      semiMajorAxis: 3141636311
      eccentricity: 0
      inclination: 1.82
      orbitalArc: 275
      showOrbit: true
      parentId: Chalawan
    isPlanet:
      age: 955983628
      classification: D
      radius: 315
      terranMass: 0.0032596602675337687
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 381
    satellites: []
commSatellite: null
assets: {}
