apiVersion: solarSystem/v1
kind: solarSystems
name: Alnitak
description: A solar system named Alnitak
position:
  x: -659995883.5476525
  'y': 22464408.825988036
  z: 55540957.57558121
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alnitak
stars:
  - name: Alnitak A
    description: ''
    tags: []
    solarMass: 33
    age: 6282538651
    spectralType: B
    hue: 200
    isWhite: false
    radius: 20
    temperature: 29500
    satellite:
      axialTilt: 0
      semiMajorAxis: 240
      eccentricity: 0
      inclination: 0
      orbitalArc: 106
      showOrbit: false
      parentId: Alnitak
  - name: Alnitak B
    description: ''
    tags: []
    solarMass: 33
    age: 6282538651
    spectralType: B
    hue: 200
    isWhite: false
    radius: 20
    temperature: 29500
    satellite:
      axialTilt: 0
      semiMajorAxis: 240
      eccentricity: 0
      inclination: 0
      orbitalArc: 286
      showOrbit: false
      parentId: Alnitak
planets:
  - name: Alnitak 1
    description: ''
    tags: []
    satellite:
      axialTilt: 25.18
      semiMajorAxis: 12682325568
      eccentricity: 0.02
      inclination: 1.78
      orbitalArc: 284
      showOrbit: true
      parentId: Alnitak
    isPlanet:
      age: 2378254939
      classification: F
      radius: 6926
      terranMass: 0.003297482126678459
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 718
    satellites:
      - name: Alnitak 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 7.92
          semiMajorAxis: 212288.97177076145
          eccentricity: 0.01
          inclination: 0.44
          orbitalArc: 89
          showOrbit: true
          parentId: Alnitak 1
        isPlanet:
          age: 3995487620
          classification: G
          radius: 750.1377094373196
          terranMass: 1.5
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 598
commSatellite: null
assets: {}
