apiVersion: solarSystem/v1
kind: solarSystems
name: Yildun
description: A solar system named Yildun
position:
  x: 5346963.392159732
  'y': -90304615.60712104
  z: -651397.8411161603
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Yildun
stars:
  - name: Yildun A
    description: ''
    tags: []
    solarMass: 2.35
    age: 1791641772193
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.8
    temperature: 9911
    satellite:
      axialTilt: 0
      semiMajorAxis: 33.599999999999994
      eccentricity: 0
      inclination: 0
      orbitalArc: 35
      showOrbit: false
      parentId: Yildun
  - name: Yildun B
    description: ''
    tags: []
    solarMass: 2.35
    age: 1791641772193
    spectralType: A
    hue: 180
    isWhite: true
    radius: 2.8
    temperature: 9911
    satellite:
      axialTilt: 0
      semiMajorAxis: 33.599999999999994
      eccentricity: 0
      inclination: 0
      orbitalArc: 215
      showOrbit: false
      parentId: Yildun
planets:
  - name: Yildun 1
    description: ''
    tags: []
    satellite:
      axialTilt: 28.06
      semiMajorAxis: 324707330.6666659
      eccentricity: 0.01
      inclination: 1.75
      orbitalArc: 179
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 423243171
      classification: D
      radius: 412
      terranMass: 0.0187199075929963
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 262
    satellites: []
  - name: Yildun 2
    description: ''
    tags: []
    satellite:
      axialTilt: 10.43
      semiMajorAxis: 1052623702.444443
      eccentricity: 0.02
      inclination: 0.49
      orbitalArc: 284
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 263182646
      classification: D
      radius: 197
      terranMass: 0.002654396366958904
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 342
    satellites: []
  - name: Yildun 3
    description: ''
    tags: []
    satellite:
      axialTilt: 30.7
      semiMajorAxis: 1245248109.2962866
      eccentricity: 0.01
      inclination: 1.56
      orbitalArc: 10
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 7531320644
      classification: K
      radius: 4017
      terranMass: 0.022265614187293014
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 23571
    temperature: 277
    satellites:
      - name: Yildun 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 37.09
          semiMajorAxis: 143781.14209616245
          eccentricity: 0
          inclination: 0.71
          orbitalArc: 90
          showOrbit: true
          parentId: Yildun 3
        isPlanet:
          age: 619462661
          classification: D
          radius: 354.6268859458335
          terranMass: 0.6999996629795688
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 348
      - name: Yildun 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 27.55
          semiMajorAxis: 267090.7162606399
          eccentricity: 0.01
          inclination: 0.02
          orbitalArc: 286
          showOrbit: true
          parentId: Yildun 3
        isPlanet:
          age: 9987901685
          classification: M
          radius: 878.9444596711068
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial3.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 1328329389
        temperature: 289
      - name: Yildun 3c
        description: ''
        tags: []
        satellite:
          axialTilt: 27.35
          semiMajorAxis: 329451.1438314377
          eccentricity: 0.01
          inclination: 1.54
          orbitalArc: 215
          showOrbit: true
          parentId: Yildun 3
        isPlanet:
          age: 9578626047
          classification: P
          radius: 790.050704631745
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 101385
        temperature: 257
  - name: Yildun 4
    description: ''
    tags: []
    satellite:
      axialTilt: 37.02
      semiMajorAxis: 1444183577.0617158
      eccentricity: 0
      inclination: 1.71
      orbitalArc: 349
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 9629330267
      classification: 'N'
      radius: 7060
      terranMass: 0.008375832662190273
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Venusian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 433181847
    temperature: 623
    satellites:
      - name: Yildun 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.24
          semiMajorAxis: 173401.83011581207
          eccentricity: 0
          inclination: 1.33
          orbitalArc: 304
          showOrbit: true
          parentId: Yildun 4
        isPlanet:
          age: 6081495369
          classification: P
          radius: 530.2808260422388
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 157349
        temperature: 260
  - name: Yildun 5
    description: ''
    tags: []
    satellite:
      axialTilt: 14.36
      semiMajorAxis: 1569923618.1234324
      eccentricity: 0.01
      inclination: 1.24
      orbitalArc: 186
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 3533076404
      classification: G
      radius: 5084
      terranMass: 0.009585579368771422
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCarbide.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 512
    satellites:
      - name: Yildun 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.4
          semiMajorAxis: 152695.19671077316
          eccentricity: 0.01
          inclination: 0.01
          orbitalArc: 246
          showOrbit: true
          parentId: Yildun 5
        isPlanet:
          age: 5023490757
          classification: P
          radius: 305.9071764340874
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 93574
        temperature: 255
      - name: Yildun 5b
        description: ''
        tags: []
        satellite:
          axialTilt: 9.13
          semiMajorAxis: 434714.6530652213
          eccentricity: 0
          inclination: 1.97
          orbitalArc: 124
          showOrbit: true
          parentId: Yildun 5
        isPlanet:
          age: 7620605858
          classification: K
          radius: 1070.7257464660624
          terranMass: 1.5000000251966865
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 7348
        temperature: 168
  - name: Yildun 6
    description: ''
    tags: []
    satellite:
      axialTilt: 27.72
      semiMajorAxis: 1650104335.234324
      eccentricity: 0.01
      inclination: 1.86
      orbitalArc: 80
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 4473808977
      classification: P
      radius: 7221
      terranMass: 0.013868129579668898
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 24844
    temperature: 260
    satellites:
      - name: Yildun 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.07
          semiMajorAxis: 144230.91522696294
          eccentricity: 0.01
          inclination: 0.31
          orbitalArc: 324
          showOrbit: true
          parentId: Yildun 6
        isPlanet:
          age: 9782711192
          classification: P
          radius: 395.8153616899311
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 51639
        temperature: 268
      - name: Yildun 6b
        description: ''
        tags: []
        satellite:
          axialTilt: 13.03
          semiMajorAxis: 314142.40011153056
          eccentricity: 0.01
          inclination: 1.33
          orbitalArc: 234
          showOrbit: true
          parentId: Yildun 6
        isPlanet:
          age: 586262480
          classification: D
          radius: 1015.0653541633664
          terranMass: 1.0599999510632745
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 151
      - name: Yildun 6c
        description: ''
        tags: []
        satellite:
          axialTilt: 19.88
          semiMajorAxis: 468771.1267367822
          eccentricity: 0.02
          inclination: 1.33
          orbitalArc: 110
          showOrbit: true
          parentId: Yildun 6
        isPlanet:
          age: 9826514929
          classification: M
          radius: 1100.4017059548878
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial1.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 8853646332
        temperature: 297
  - name: Yildun 7
    description: ''
    tags: []
    satellite:
      axialTilt: 24.99
      semiMajorAxis: 1767541985
      eccentricity: 0.01
      inclination: 0.95
      orbitalArc: 88
      showOrbit: true
      parentId: Yildun
    isPlanet:
      age: 8600783587
      classification: O
      radius: 7085
      terranMass: 0.022263426168301008
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 266207480
    temperature: 296
    satellites:
      - name: Yildun 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 18.99
          semiMajorAxis: 114160.30143688543
          eccentricity: 0.01
          inclination: 1.72
          orbitalArc: 350
          showOrbit: true
          parentId: Yildun 7
        isPlanet:
          age: 866657854
          classification: C
          radius: 502.14370863428195
          terranMass: 1.000000039349664
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 43
      - name: Yildun 7b
        description: ''
        tags: []
        satellite:
          axialTilt: 15.74
          semiMajorAxis: 252447.93999834318
          eccentricity: 0.01
          inclination: 1.04
          orbitalArc: 319
          showOrbit: true
          parentId: Yildun 7
        isPlanet:
          age: 7535008526
          classification: H
          radius: 776.7628923025944
          terranMass: 1.100000119725269
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 0
        temperature: 740
commSatellite: null
assets: {}
