apiVersion: solarSystem/v1
kind: solarSystems
name: Alpheratz
description: A solar system named Alpheratz
position:
  x: -1631264.9110081801
  'y': -24804471.420025937
  z: 44552505.43681724
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alpheratz
stars:
  - name: Alpheratz A
    description: ''
    tags: []
    solarMass: 3.63
    age: 1187707851710
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.94
    temperature: 11950
    satellite:
      axialTilt: 0
      semiMajorAxis: 35.28
      eccentricity: 0
      inclination: 0
      orbitalArc: 78
      showOrbit: false
      parentId: Alpheratz
  - name: Alpheratz B
    description: ''
    tags: []
    solarMass: 3.63
    age: 1187707851710
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.94
    temperature: 11950
    satellite:
      axialTilt: 0
      semiMajorAxis: 35.28
      eccentricity: 0
      inclination: 0
      orbitalArc: 258
      showOrbit: false
      parentId: Alpheratz
planets:
  - name: Alpheratz 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.59
      semiMajorAxis: 733071283
      eccentricity: 0.01
      inclination: 0.16
      orbitalArc: 264
      showOrbit: true
      parentId: Alpheratz
    isPlanet:
      age: 685420904
      classification: D
      radius: 58
      terranMass: 0.00196228533822783
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 224
    satellites: []
commSatellite: null
assets: {}
