apiVersion: solarSystem/v1
kind: solarSystems
name: Helvetios
description: A solar system named Helvetios
position:
  x: 6685951.0196089735
  'y': -9409154.804039907
  z: 23892576.53912877
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Helvetios
stars:
  - name: Helvetios A
    description: ''
    tags: []
    solarMass: 1.09
    age: 42794683360667
    spectralType: G
    hue: 45
    isWhite: false
    radius: 1.152
    temperature: 5768
    satellite:
      axialTilt: 0
      semiMajorAxis: 13.823999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 170
      showOrbit: false
      parentId: Helvetios
  - name: Helvetios B
    description: ''
    tags: []
    solarMass: 1.09
    age: 42794683360667
    spectralType: G
    hue: 45
    isWhite: false
    radius: 1.152
    temperature: 5768
    satellite:
      axialTilt: 0
      semiMajorAxis: 13.823999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 350
      showOrbit: false
      parentId: Helvetios
planets:
  - name: Helvetios 1
    description: ''
    tags: []
    satellite:
      axialTilt: 31.28
      semiMajorAxis: 71104388.99999863
      eccentricity: 0.01
      inclination: 1.03
      orbitalArc: 50
      showOrbit: true
      parentId: Helvetios
    isPlanet:
      age: 58356930
      classification: D
      radius: 375
      terranMass: 0.002715892189631853
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 182
    satellites: []
  - name: Helvetios 2
    description: ''
    tags: []
    satellite:
      axialTilt: 34.41
      semiMajorAxis: 211268764
      eccentricity: 0.02
      inclination: 0.01
      orbitalArc: 104
      showOrbit: true
      parentId: Helvetios
    isPlanet:
      age: 9253427668
      classification: K
      radius: 3094
      terranMass: 0.042672742725329456
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 49326
    temperature: 283
    satellites:
      - name: Helvetios 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 2.2
          semiMajorAxis: 161148.60267906563
          eccentricity: 0
          inclination: 1.06
          orbitalArc: 346
          showOrbit: true
          parentId: Helvetios 2
        isPlanet:
          age: 3390694576
          classification: O
          radius: 599.0654374686454
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 661620861
        temperature: 291
commSatellite: null
assets: {}
