apiVersion: solarSystem/v1
kind: solarSystems
name: Adhafera
description: A solar system named Adhafera
position:
  x: -21026756.68932311
  'y': -20902974.41734637
  z: -43442840.37256046
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Adhafera
stars:
  - name: Adhafera A
    description: ''
    tags: []
    solarMass: 3
    age: 692333869384
    spectralType: F
    hue: 60
    isWhite: false
    radius: 10.5
    temperature: 6900
    satellite:
      axialTilt: 0
      semiMajorAxis: 126
      eccentricity: 0
      inclination: 0
      orbitalArc: 17
      showOrbit: false
      parentId: Adhafera
  - name: Adhafera B
    description: ''
    tags: []
    solarMass: 3
    age: 692333869384
    spectralType: F
    hue: 60
    isWhite: false
    radius: 10.5
    temperature: 6900
    satellite:
      axialTilt: 0
      semiMajorAxis: 126
      eccentricity: 0
      inclination: 0
      orbitalArc: 197
      showOrbit: false
      parentId: Adhafera
planets:
  - name: Adhafera 1
    description: ''
    tags: []
    satellite:
      axialTilt: 24.7
      semiMajorAxis: 640137379.0000007
      eccentricity: 0.01
      inclination: 0.49
      orbitalArc: 233
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 4989741629
      classification: H
      radius: 4012
      terranMass: 0.02209374838013565
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 898
    satellites:
      - name: Adhafera 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 2.62
          semiMajorAxis: 146363.07196635078
          eccentricity: 0
          inclination: 1.79
          orbitalArc: 317
          showOrbit: true
          parentId: Adhafera 1
        isPlanet:
          age: 770963629
          classification: D
          radius: 567.6585668376317
          terranMass: 0.15999975715051185
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 284
      - name: Adhafera 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 21.22
          semiMajorAxis: 319588.70943652256
          eccentricity: 0.02
          inclination: 0.44
          orbitalArc: 106
          showOrbit: true
          parentId: Adhafera 1
        isPlanet:
          age: 7230631861
          classification: B
          radius: 980.3334645292102
          terranMass: 0.1000004831651026
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/plutomap1k.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 171
  - name: Adhafera 2
    description: ''
    tags: []
    satellite:
      axialTilt: 28.37
      semiMajorAxis: 930185666.0000017
      eccentricity: 0.01
      inclination: 0.92
      orbitalArc: 358
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 108002134
      classification: D
      radius: 396
      terranMass: 0.0002452617355101862
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 209
    satellites: []
  - name: Adhafera 3
    description: ''
    tags: []
    satellite:
      axialTilt: 19.37
      semiMajorAxis: 1394463800.000005
      eccentricity: 0.01
      inclination: 0.57
      orbitalArc: 350
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 261835367
      classification: D
      radius: 279
      terranMass: 0.0029730815671858623
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 363
    satellites: []
  - name: Adhafera 4
    description: ''
    tags: []
    satellite:
      axialTilt: 38.21
      semiMajorAxis: 1807349731.000025
      eccentricity: 0.01
      inclination: 0.92
      orbitalArc: 184
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 5422169423
      classification: P
      radius: 6487
      terranMass: 0.0033754215333320716
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 126088
    temperature: 264
    satellites: []
  - name: Adhafera 5
    description: ''
    tags: []
    satellite:
      axialTilt: 20.53
      semiMajorAxis: 2798867852.0000253
      eccentricity: 0
      inclination: 0.55
      orbitalArc: 314
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 5285065316
      classification: K
      radius: 2505
      terranMass: 0.03540685460729007
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 21180
    temperature: 165
    satellites:
      - name: Adhafera 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.9
          semiMajorAxis: 285048.3858049868
          eccentricity: 0.01
          inclination: 1.96
          orbitalArc: 56
          showOrbit: true
          parentId: Adhafera 5
        isPlanet:
          age: 96925467
          classification: D
          radius: 622.3763882204952
          terranMass: 0.19999975097513434
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 325
  - name: Adhafera 6
    description: ''
    tags: []
    satellite:
      axialTilt: 18.92
      semiMajorAxis: 3144131690.0000653
      eccentricity: 0.01
      inclination: 0.14
      orbitalArc: 59
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 4962874229
      classification: J
      radius: 46586
      terranMass: 0.41394574534821926
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: null
    population: 0
    temperature: 269
    satellites:
      - name: Adhafera 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 25.3
          semiMajorAxis: 1829477.0966369817
          eccentricity: 0.01
          inclination: 1.46
          orbitalArc: 255
          showOrbit: true
          parentId: Adhafera 6
        isPlanet:
          age: 5177024347
          classification: K
          radius: 8263.42723398328
          terranMass: 2.3000001429715025
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 18507
        temperature: 276
      - name: Adhafera 6b
        description: ''
        tags: []
        satellite:
          axialTilt: 15.31
          semiMajorAxis: 4220940.968136548
          eccentricity: 0.01
          inclination: 1.61
          orbitalArc: 195
          showOrbit: true
          parentId: Adhafera 6
        isPlanet:
          age: 9671918924
          classification: O
          radius: 10422.076464534686
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 116564191
        temperature: 293
  - name: Adhafera 7
    description: ''
    tags: []
    satellite:
      axialTilt: 30.81
      semiMajorAxis: 3571729010
      eccentricity: 0
      inclination: 1.19
      orbitalArc: 195
      showOrbit: true
      parentId: Adhafera
    isPlanet:
      age: 1334261336
      classification: A
      radius: 770
      terranMass: 0.005314431706920974
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAcid.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 1673
    satellites:
      - name: Adhafera 7a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.25
          semiMajorAxis: 29948.746534985552
          eccentricity: 0.02
          inclination: 1.52
          orbitalArc: 255
          showOrbit: true
          parentId: Adhafera 7
        isPlanet:
          age: 6712197956
          classification: H
          radius: 65.8214209560122
          terranMass: 0.9000000882743703
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 782
commSatellite: null
assets: {}
