apiVersion: solarSystem/v1
kind: solarSystems
name: Gienah
description: A solar system named Gienah
position:
  x: 5322214.108280701
  'y': 24413044.466787007
  z: -77047565.70790473
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Gienah
stars:
  - name: Gienah A
    description: ''
    tags: []
    solarMass: 1.103
    age: 1053252959532
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.13
    temperature: 4699
    satellite:
      axialTilt: 0
      semiMajorAxis: 133.56
      eccentricity: 0
      inclination: 0
      orbitalArc: 293
      showOrbit: false
      parentId: Gienah
  - name: Gienah B
    description: ''
    tags: []
    solarMass: 1.103
    age: 1053252959532
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.13
    temperature: 4699
    satellite:
      axialTilt: 0
      semiMajorAxis: 133.56
      eccentricity: 0
      inclination: 0
      orbitalArc: 473
      showOrbit: false
      parentId: Gienah
planets:
  - name: Gienah 1
    description: ''
    tags: []
    satellite:
      axialTilt: 36.8
      semiMajorAxis: 273828777
      eccentricity: 0.01
      inclination: 1.37
      orbitalArc: 169
      showOrbit: true
      parentId: Gienah
    isPlanet:
      age: 238668079
      classification: D
      radius: 74
      terranMass: 0.019305350163583816
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 327
    satellites: []
  - name: Gienah 2
    description: ''
    tags: []
    satellite:
      axialTilt: 23.39
      semiMajorAxis: 1808399011.6666675
      eccentricity: 0.01
      inclination: 1.89
      orbitalArc: 32
      showOrbit: true
      parentId: Gienah
    isPlanet:
      age: 76859117
      classification: B
      radius: 2190
      terranMass: 0.018208592447780555
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 286
    satellites:
      - name: Gienah 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.76
          semiMajorAxis: 66551.63066096918
          eccentricity: 0
          inclination: 1.92
          orbitalArc: 64
          showOrbit: true
          parentId: Gienah 2
        isPlanet:
          age: 103873815
          classification: D
          radius: 358.0381059412701
          terranMass: 0.3499998164320328
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 399
      - name: Gienah 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 39.63
          semiMajorAxis: 120800.91951792303
          eccentricity: 0
          inclination: 1
          orbitalArc: 175
          showOrbit: true
          parentId: Gienah 2
        isPlanet:
          age: 9685340779
          classification: H
          radius: 252.19398646748022
          terranMass: 1.1000001256031848
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 655
  - name: Gienah 3
    description: ''
    tags: []
    satellite:
      axialTilt: 25.93
      semiMajorAxis: 3336463900
      eccentricity: 0.02
      inclination: 1.67
      orbitalArc: 116
      showOrbit: true
      parentId: Gienah
    isPlanet:
      age: 363517950
      classification: D
      radius: 191
      terranMass: 0.0004134187050388952
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 264
    satellites: []
commSatellite: null
assets: {}
