apiVersion: solarSystem/v1
kind: solarSystems
name: Gudja
description: A solar system named Gudja
position:
  x: 159621315.01340023
  'y': -62231079.166799165
  z: -102928455.04605821
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Gudja
stars:
  - name: Gudja A
    description: ''
    tags: []
    solarMass: 2.7
    age: 137509702704
    spectralType: K
    hue: 30
    isWhite: false
    radius: 71.31
    temperature: 3863
    satellite:
      axialTilt: 0
      semiMajorAxis: 855.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 97
      showOrbit: false
      parentId: Gudja
  - name: Gudja B
    description: ''
    tags: []
    solarMass: 2.7
    age: 137509702704
    spectralType: K
    hue: 30
    isWhite: false
    radius: 71.31
    temperature: 3863
    satellite:
      axialTilt: 0
      semiMajorAxis: 855.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 277
      showOrbit: false
      parentId: Gudja
planets:
  - name: Gudja 1
    description: ''
    tags: []
    satellite:
      axialTilt: 7.36
      semiMajorAxis: 3659038236
      eccentricity: 0
      inclination: 1.61
      orbitalArc: 98
      showOrbit: true
      parentId: Gudja
    isPlanet:
      age: 1869932921
      classification: E
      radius: 6050
      terranMass: 0.018153817196800783
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot_light.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 832
    satellites: []
commSatellite: null
assets: {}
