apiVersion: solarSystem/v1
kind: solarSystems
name: Syrma
description: A solar system named Syrma
position:
  x: 21208355.788156267
  'y': 3986250.541230821
  z: -31438392.163014874
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Syrma
stars:
  - name: Syrma A
    description: ''
    tags: []
    solarMass: 1.44
    age: 7397406781659
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.89
    temperature: 6055
    satellite:
      axialTilt: 0
      semiMajorAxis: 34.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 330
      showOrbit: false
      parentId: Syrma
  - name: Syrma B
    description: ''
    tags: []
    solarMass: 1.44
    age: 7397406781659
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.89
    temperature: 6055
    satellite:
      axialTilt: 0
      semiMajorAxis: 34.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 510
      showOrbit: false
      parentId: Syrma
planets: []
commSatellite: null
assets: {}
