apiVersion: inventory/v1
kind: inventory
name: Network Adapter
plural: Network Adapters
description: Equipment which translates computer signals between two interfaces.
volume: 0.5
assets:
  image: /plugins/Thorium Default/inventory/Network Adapter/assets/image.svg
continuous: false
durability: 1
abundance: 1
tags: []
flags:
  repair:
    type:
      - Computer Specialist
      - General Engineer
      - Exocomp
