apiVersion: stations/v1
kind: stationComplements
name: 2 Small
hasShipMap: false
stations:
  - name: Pilot
    description: Controls the movement of the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Flight Controls
        icon: /plugins/Thorium Default/stationComplements/assets/Pilot Card.svg
        component: Pilot
      - name: Navigation
        icon: /plugins/Thorium Default/stationComplements/assets/Navigation.svg
        component: Navigation
      - name: Sensors
        icon: /plugins/Thorium Default/stationComplements/assets/Sensors.svg
        component: Sensors
      - name: Alert Level
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: AlertLevel
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Tactical
    description: Defends the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Targeting
        icon: /plugins/Thorium Default/stationComplements/assets/Targeting.svg
        component: Targeting
      - name: Systems Monitor
        icon: /plugins/Thorium Default/stationComplements/assets/SystemsMonitor.svg
        component: SystemsMonitor
      - name: Damage Reports
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: DamageReports
      - name: Cargo Control
        icon: /plugins/Thorium Default/stationComplements/assets/CargoControl.svg
        component: CargoControl
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
flightMode: nova
assets: {}
