apiVersion: solarSystem/v1
kind: solarSystems
name: Rasalas
description: A solar system named Rasalas
position:
  x: -30895430.923835825
  'y': -28597258.66067059
  z: -49811568.170925796
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Rasalas
stars:
  - name: Rasalas A
    description: ''
    tags: []
    solarMass: 1.5
    age: 1467328891889
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.89
    temperature: 4519
    satellite:
      axialTilt: 0
      semiMajorAxis: 142.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 176
      showOrbit: false
      parentId: Rasalas
  - name: Rasalas B
    description: ''
    tags: []
    solarMass: 1.5
    age: 1467328891889
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.89
    temperature: 4519
    satellite:
      axialTilt: 0
      semiMajorAxis: 142.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 356
      showOrbit: false
      parentId: Rasalas
planets:
  - name: Rasalas 1
    description: ''
    tags: []
    satellite:
      axialTilt: 11.02
      semiMajorAxis: 1105633237
      eccentricity: 0.01
      inclination: 1.8
      orbitalArc: 166
      showOrbit: true
      parentId: Rasalas
    isPlanet:
      age: 4930469612
      classification: O
      radius: 5451
      terranMass: 0.009943607266164294
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 536964660
    temperature: 299
    satellites: []
commSatellite: null
assets: {}
