apiVersion: solarSystem/v1
kind: solarSystems
name: Polaris
description: A solar system named Polaris
position:
  x: -1570450.3613776292
  'y': -198796482.02315152
  z: 2013373.9780841866
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Polaris
stars:
  - name: Polaris A
    description: ''
    tags: []
    solarMass: 5.13
    age: 105571118750
    spectralType: F
    hue: 60
    isWhite: false
    radius: 46.27
    temperature: 6015
    satellite:
      axialTilt: 0
      semiMajorAxis: 555.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 323
      showOrbit: false
      parentId: Polaris
  - name: Polaris B
    description: ''
    tags: []
    solarMass: 5.13
    age: 105571118750
    spectralType: F
    hue: 60
    isWhite: false
    radius: 46.27
    temperature: 6015
    satellite:
      axialTilt: 0
      semiMajorAxis: 555.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 503
      showOrbit: false
      parentId: Polaris
planets:
  - name: Polaris 1
    description: ''
    tags: []
    satellite:
      axialTilt: 25.77
      semiMajorAxis: 1821818395.3333333
      eccentricity: 0.01
      inclination: 0.3
      orbitalArc: 4
      showOrbit: true
      parentId: Polaris
    isPlanet:
      age: 7659560394
      classification: J
      radius: 52405
      terranMass: 1.0533243033355857
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 303
    satellites:
      - name: Polaris 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 14.64
          semiMajorAxis: 1580914.4977391292
          eccentricity: 0
          inclination: 0.73
          orbitalArc: 251
          showOrbit: true
          parentId: Polaris 1
        isPlanet:
          age: 5448120905
          classification: L
          radius: 4773.92306702588
          terranMass: 1.1000000214441914
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 31334
        temperature: 314
      - name: Polaris 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 4.44
          semiMajorAxis: 2327524.0832523885
          eccentricity: 0.01
          inclination: 0.03
          orbitalArc: 23
          showOrbit: true
          parentId: Polaris 1
        isPlanet:
          age: 529812927
          classification: D
          radius: 8775.75289665349
          terranMass: 0.4199999874042788
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 151
      - name: Polaris 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 23.54
          semiMajorAxis: 3550716.878258831
          eccentricity: 0.02
          inclination: 1.33
          orbitalArc: 264
          showOrbit: true
          parentId: Polaris 1
        isPlanet:
          age: 593172025
          classification: D
          radius: 9443.39595281604
          terranMass: 1.1199999071959892
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 351
  - name: Polaris 2
    description: ''
    tags: []
    satellite:
      axialTilt: 36.63
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.38
      orbitalArc: 43
      showOrbit: true
      parentId: Polaris
    isPlanet:
      age: 649461840
      classification: C
      radius: 2271
      terranMass: 0.004245289445173829
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 37
    satellites:
      - name: Polaris 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 19.95
          semiMajorAxis: 62007.16073250925
          eccentricity: 0
          inclination: 0.34
          orbitalArc: 124
          showOrbit: true
          parentId: Polaris 2
        isPlanet:
          age: 6921700484
          classification: M
          radius: 269.1951529819391
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Varied and extensive vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial4.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 7212054064
        temperature: 291
      - name: Polaris 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 4.89
          semiMajorAxis: 88692.82110444069
          eccentricity: 0.01
          inclination: 1.38
          orbitalArc: 77
          showOrbit: true
          parentId: Polaris 2
        isPlanet:
          age: 4912447647
          classification: P
          radius: 384.0044243246211
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 136367
        temperature: 269
      - name: Polaris 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 33.44
          semiMajorAxis: 124030.6145772693
          eccentricity: 0.02
          inclination: 0.11
          orbitalArc: 194
          showOrbit: true
          parentId: Polaris 2
        isPlanet:
          age: 2853279051
          classification: B
          radius: 492.18497848122735
          terranMass: 0.40000052350343684
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 610
commSatellite: null
assets: {}
