apiVersion: solarSystem/v1
kind: solarSystems
name: Gacrux
description: A solar system named Gacrux
position:
  x: 3430282.518702205
  'y': 39132168.86558117
  z: -25069338.661413897
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Gacrux
stars:
  - name: Gacrux A
    description: ''
    tags: []
    solarMass: 1.5
    age: 87655708088
    spectralType: M
    hue: 0
    isWhite: false
    radius: 73
    temperature: 3689
    satellite:
      axialTilt: 0
      semiMajorAxis: 876
      eccentricity: 0
      inclination: 0
      orbitalArc: 356
      showOrbit: false
      parentId: Gacrux
  - name: Gacrux B
    description: ''
    tags: []
    solarMass: 1.5
    age: 87655708088
    spectralType: M
    hue: 0
    isWhite: false
    radius: 73
    temperature: 3689
    satellite:
      axialTilt: 0
      semiMajorAxis: 876
      eccentricity: 0
      inclination: 0
      orbitalArc: 536
      showOrbit: false
      parentId: Gacrux
planets:
  - name: Gacrux 1
    description: ''
    tags: []
    satellite:
      axialTilt: 30.95
      semiMajorAxis: 1463706857.6666658
      eccentricity: 0.01
      inclination: 1.04
      orbitalArc: 281
      showOrbit: true
      parentId: Gacrux
    isPlanet:
      age: 553482356
      classification: D
      radius: 136
      terranMass: 0.008535158758034032
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 291
    satellites: []
  - name: Gacrux 2
    description: ''
    tags: []
    satellite:
      axialTilt: 30.87
      semiMajorAxis: 2485782267.6666656
      eccentricity: 0.02
      inclination: 0.29
      orbitalArc: 292
      showOrbit: true
      parentId: Gacrux
    isPlanet:
      age: 6549547698
      classification: P
      radius: 7194
      terranMass: 0.0065063020631219975
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 125134
    temperature: 268
    satellites:
      - name: Gacrux 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 35.51
          semiMajorAxis: 259528.47372261187
          eccentricity: 0
          inclination: 1.57
          orbitalArc: 93
          showOrbit: true
          parentId: Gacrux 2
        isPlanet:
          age: 6659330053
          classification: H
          radius: 924.4672747875953
          terranMass: 1.100000011606204
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 0
        temperature: 689
      - name: Gacrux 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 5.14
          semiMajorAxis: 541475.5443960375
          eccentricity: 0
          inclination: 1.37
          orbitalArc: 68
          showOrbit: true
          parentId: Gacrux 2
        isPlanet:
          age: 7004740959
          classification: K
          radius: 1769.5279228628676
          terranMass: 2.1000001340900476
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 37587
        temperature: 189
  - name: Gacrux 3
    description: ''
    tags: []
    satellite:
      axialTilt: 26.75
      semiMajorAxis: 3420867386
      eccentricity: 0.02
      inclination: 0.51
      orbitalArc: 224
      showOrbit: true
      parentId: Gacrux
    isPlanet:
      age: 8382583046
      classification: O
      radius: 5715
      terranMass: 0.024923293835582047
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 461695667
    temperature: 296
    satellites:
      - name: Gacrux 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 6.14
          semiMajorAxis: 236239.79832500033
          eccentricity: 0.02
          inclination: 0.06
          orbitalArc: 275
          showOrbit: true
          parentId: Gacrux 3
        isPlanet:
          age: 997551805
          classification: D
          radius: 896.5607947083913
          terranMass: 1.3899997355229605
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 265
      - name: Gacrux 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 33.99
          semiMajorAxis: 436403.5646706748
          eccentricity: 0
          inclination: 0.36
          orbitalArc: 159
          showOrbit: true
          parentId: Gacrux 3
        isPlanet:
          age: 388327376
          classification: D
          radius: 1330.4986727764476
          terranMass: 0.5499997432550476
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 304
commSatellite: null
assets: {}
