apiVersion: solarSystem/v1
kind: solarSystems
name: Enif
description: A solar system named Enif
position:
  x: 199690810.86393204
  'y': -62239260.17651968
  z: 296572528.43603843
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Enif
stars:
  - name: Enif A
    description: ''
    tags: []
    solarMass: 11
    age: 67038511571
    spectralType: K
    hue: 30
    isWhite: false
    radius: 183
    temperature: 4100
    satellite:
      axialTilt: 0
      semiMajorAxis: 2196
      eccentricity: 0
      inclination: 0
      orbitalArc: 61
      showOrbit: false
      parentId: Enif
  - name: Enif B
    description: ''
    tags: []
    solarMass: 11
    age: 67038511571
    spectralType: K
    hue: 30
    isWhite: false
    radius: 183
    temperature: 4100
    satellite:
      axialTilt: 0
      semiMajorAxis: 2196
      eccentricity: 0
      inclination: 0
      orbitalArc: 241
      showOrbit: false
      parentId: Enif
planets:
  - name: Enif 1
    description: ''
    tags: []
    satellite:
      axialTilt: 9
      semiMajorAxis: 4341015877
      eccentricity: 0.01
      inclination: 1.9
      orbitalArc: 44
      showOrbit: true
      parentId: Enif
    isPlanet:
      age: 6318279992
      classification: H
      radius: 4044
      terranMass: 0.0037659452951427992
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 719
    satellites:
      - name: Enif 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 9.67
          semiMajorAxis: 98212.77390111634
          eccentricity: 0.02
          inclination: 0.25
          orbitalArc: 330
          showOrbit: true
          parentId: Enif 1
        isPlanet:
          age: 7753162662
          classification: K
          radius: 256.7884585173308
          terranMass: 1.1000001034023565
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 22745
        temperature: 186
      - name: Enif 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 4.34
          semiMajorAxis: 156216.65717079694
          eccentricity: 0
          inclination: 1.74
          orbitalArc: 295
          showOrbit: true
          parentId: Enif 1
        isPlanet:
          age: 356352822
          classification: C
          radius: 390.5416429269923
          terranMass: 1.9000001906435027
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 41
commSatellite: null
assets: {}
