apiVersion: solarSystem/v1
kind: solarSystems
name: Cebalrai
description: A solar system named Cebalrai
position:
  x: 42775437.46078972
  'y': -3425964.6962770508
  z: -3090093.4459519116
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Cebalrai
stars:
  - name: Cebalrai A
    description: ''
    tags: []
    radius: 12.17
    temperature: 4559
    solarMass: 1.44
    age: 1297992703892
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 154
      semiMajorAxis: 146.04
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Cebalrai
  - name: Cebalrai B
    description: ''
    tags: []
    radius: 12.17
    temperature: 4559
    solarMass: 1.44
    age: 1297992703892
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 334
      semiMajorAxis: 146.04
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Cebalrai
planets:
  - name: Cebalrai 1
    description: ''
    tags: []
    isPlanet:
      radius: 4143
      age: 721700291
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
      terranMass: 0.01152582521782132
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      classification: C
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 43
    satellite:
      semiMajorAxis: 575735472
      eccentricity: 0.02
      inclination: 1.26
      orbitalArc: 14
      axialTilt: 34.26
      parentId: Cebalrai
      showOrbit: true
    satellites:
      - name: Cebalrai 1a
        description: ''
        tags: []
        isPlanet:
          radius: 310.052742850688
          age: 777341592
          ringMapAsset: null
          terranMass: 1.2000001767068023
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
          classification: C
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 55
        satellite:
          semiMajorAxis: 99836.98319792154
          eccentricity: 0.01
          inclination: 0.79
          orbitalArc: 349
          axialTilt: 26.34
          parentId: Cebalrai 1
          showOrbit: true
        satellites: []
  - name: Cebalrai 2
    description: ''
    tags: []
    isPlanet:
      radius: 6369
      age: 2250244906
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
      terranMass: 0.016869470012755662
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      classification: F
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 632
    satellite:
      semiMajorAxis: 1082811430
      eccentricity: 0.01
      inclination: 1.53
      orbitalArc: 247
      axialTilt: 32.63
      parentId: Cebalrai
      showOrbit: true
    satellites: []
  - name: Cebalrai 3
    description: ''
    tags: []
    isPlanet:
      radius: 6219
      age: 5377324524
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: null
      terranMass: 0.0053618715446933805
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      classification: L
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
    population: 48406
    temperature: 274
    satellite:
      semiMajorAxis: 1347282526.9999993
      eccentricity: 0.01
      inclination: 1.62
      orbitalArc: 63
      axialTilt: 28.12
      parentId: Cebalrai
      showOrbit: true
    satellites: []
  - name: Cebalrai 4
    description: ''
    tags: []
    isPlanet:
      radius: 29393
      age: 3455123209
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
      terranMass: 0.8177199728874769
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 277
    satellite:
      semiMajorAxis: 2116600564.666666
      eccentricity: 0.01
      inclination: 0.82
      orbitalArc: 190
      axialTilt: 2.39
      parentId: Cebalrai
      showOrbit: true
    satellites:
      - name: Cebalrai 4a
        description: ''
        tags: []
        isPlanet:
          radius: 5329.188779575947
          age: 7087635102
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 79622
        temperature: 255
        satellite:
          semiMajorAxis: 1227761.7708628736
          eccentricity: 0.02
          inclination: 1.84
          orbitalArc: 206
          axialTilt: 6.67
          parentId: Cebalrai 4
          showOrbit: true
        satellites: []
      - name: Cebalrai 4b
        description: ''
        tags: []
        isPlanet:
          radius: 6158.332042934649
          age: 7250421265
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 66112
        temperature: 255
        satellite:
          semiMajorAxis: 2032596.5811549504
          eccentricity: 0.02
          inclination: 0.72
          orbitalArc: 39
          axialTilt: 21.38
          parentId: Cebalrai 4
          showOrbit: true
        satellites: []
      - name: Cebalrai 4c
        description: ''
        tags: []
        isPlanet:
          radius: 6847.591501925616
          age: 3940324853
          ringMapAsset: null
          terranMass: 0.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
          classification: G
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
        population: 0
        temperature: 502
        satellite:
          semiMajorAxis: 2965007.1203337917
          eccentricity: 0.01
          inclination: 1.14
          orbitalArc: 75
          axialTilt: 38.82
          parentId: Cebalrai 4
          showOrbit: true
        satellites: []
  - name: Cebalrai 5
    description: ''
    tags: []
    isPlanet:
      radius: 492
      age: 59266468
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
      terranMass: 0.013575746508935742
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 274
    satellite:
      semiMajorAxis: 3255519087
      eccentricity: 0.02
      inclination: 0.51
      orbitalArc: 96
      axialTilt: 25.3
      parentId: Cebalrai
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
