apiVersion: solarSystem/v1
kind: solarSystems
name: Elkurud
description: A solar system named Elkurud
position:
  x: -301264710.56974816
  'y': 229234868.80558848
  z: -9898183.997605858
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Elkurud
stars:
  - name: Elkurud A
    description: ''
    tags: []
    solarMass: 4.13
    age: 452703338032
    spectralType: A
    hue: 180
    isWhite: true
    radius: 7.377
    temperature: 9916
    satellite:
      axialTilt: 0
      semiMajorAxis: 88.524
      eccentricity: 0
      inclination: 0
      orbitalArc: 214
      showOrbit: false
      parentId: Elkurud
  - name: Elkurud B
    description: ''
    tags: []
    solarMass: 4.13
    age: 452703338032
    spectralType: A
    hue: 180
    isWhite: true
    radius: 7.377
    temperature: 9916
    satellite:
      axialTilt: 0
      semiMajorAxis: 88.524
      eccentricity: 0
      inclination: 0
      orbitalArc: 394
      showOrbit: false
      parentId: Elkurud
planets:
  - name: Elkurud 1
    description: ''
    tags: []
    satellite:
      axialTilt: 2.8
      semiMajorAxis: 1454823620.3333333
      eccentricity: 0.02
      inclination: 0.84
      orbitalArc: 212
      showOrbit: true
      parentId: Elkurud
    isPlanet:
      age: 31448392
      classification: D
      radius: 269
      terranMass: 0.015631748015061026
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 162
    satellites: []
  - name: Elkurud 2
    description: ''
    tags: []
    satellite:
      axialTilt: 5.96
      semiMajorAxis: 2326301556.3333335
      eccentricity: 0
      inclination: 1.68
      orbitalArc: 146
      showOrbit: true
      parentId: Elkurud
    isPlanet:
      age: 5172262723
      classification: J
      radius: 46685
      terranMass: 0.14298326650820284
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 241
    satellites:
      - name: Elkurud 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 34.83
          semiMajorAxis: 1277983.8297863957
          eccentricity: 0
          inclination: 0.91
          orbitalArc: 187
          showOrbit: true
          parentId: Elkurud 2
        isPlanet:
          age: 837209597
          classification: D
          radius: 4169.380259446714
          terranMass: 0.2199996656700669
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 321
      - name: Elkurud 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 28.32
          semiMajorAxis: 2602215.785993996
          eccentricity: 0.01
          inclination: 1.01
          orbitalArc: 84
          showOrbit: true
          parentId: Elkurud 2
        isPlanet:
          age: 883845892
          classification: D
          radius: 7721.708563780404
          terranMass: 0.26999980935425794
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 237
  - name: Elkurud 3
    description: ''
    tags: []
    satellite:
      axialTilt: 15.55
      semiMajorAxis: 4000000000
      eccentricity: 0.02
      inclination: 1.49
      orbitalArc: 59
      showOrbit: true
      parentId: Elkurud
    isPlanet:
      age: 3547841980
      classification: J
      radius: 32705
      terranMass: 0.9597113383549061
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 222
    satellites:
      - name: Elkurud 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 14.49
          semiMajorAxis: 1365486.3226027326
          eccentricity: 0.02
          inclination: 1.16
          orbitalArc: 223
          showOrbit: true
          parentId: Elkurud 3
        isPlanet:
          age: 436429670
          classification: D
          radius: 4201.4963772391775
          terranMass: 0.6399999724937115
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 269
commSatellite: null
assets: {}
