apiVersion: stations/v1
kind: stationComplements
name: 5 Small
hasShipMap: false
stations:
  - name: Pilot
    description: Controls the movement of the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Flight Controls
        icon: /plugins/Thorium Default/stationComplements/assets/Pilot Card.svg
        component: Pilot
      - name: Navigation
        icon: /plugins/Thorium Default/stationComplements/assets/Navigation.svg
        component: Navigation
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Engineer
    description: Allocates ship power and manages the engines and reactors
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Systems Monitor
        icon: /plugins/Thorium Default/stationComplements/assets/SystemsMonitor.svg
        component: SystemsMonitor
      - name: Damage Reports
        icon: /plugins/Thorium Default/stationComplements/assets/DamageReports.svg
        component: DamageReports
      - name: Exocomps
        icon: /plugins/Thorium Default/stationComplements/assets/Exocomps.svg
        component: Exocomps
      - name: Engineering Panel
        icon: >-
          /plugins/Thorium
          Default/stationComplements/assets/EngineeringPanels.svg
        component: EngineeringPanels
        config: {}
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Tactical
    description: Defends the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Targeting
        icon: /plugins/Thorium Default/stationComplements/assets/Targeting.svg
        component: Targeting
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Operations
    description: Communications and internal ship management
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Short Range Comm
        icon: /plugins/Thorium Default/stationComplements/assets/ShortRangeComm.svg
        component: ShortRangeComm
      - name: Long Range Comm
        icon: /plugins/Thorium Default/stationComplements/assets/LongRangeComm.svg
        component: LongRangeComm
      - name: Cargo Control
        icon: /plugins/Thorium Default/stationComplements/assets/CargoControl.svg
        component: CargoControl
      - name: Documents
        icon: /plugins/Thorium Default/stationComplements/assets/Documents.svg
        component: Documents
    widgets:
      - name: Remote Access
        icon: /plugins/Thorium Default/stationComplements/assets/RemoteAccess.svg
        component: RemoteAccess
        size: sm
      - name: Code Cyphers
        icon: /plugins/Thorium Default/stationComplements/assets/CodeCyphers.svg
        component: CodeCyphers
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Sensors
    description: Scans for objects outside of the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Sensors
        icon: /plugins/Thorium Default/stationComplements/assets/Sensors.svg
        component: Sensors
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
flightMode: nova
assets: {}
