apiVersion: solarSystem/v1
kind: solarSystems
name: Biham
description: A solar system named Biham
position:
  x: 22175443.546430252
  'y': -5224113.163869971
  z: 42689434.96455025
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Biham
stars:
  - name: 'Biham '
    description: ''
    tags: []
    solarMass: 2.09
    age: 2391324761070
    spectralType: A
    hue: 180
    isWhite: true
    radius: 3.623
    temperature: 7872
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 291
      showOrbit: false
      parentId: Biham
planets:
  - name: Biham 1
    description: ''
    tags: []
    satellite:
      axialTilt: 23.48
      semiMajorAxis: 507527016
      eccentricity: 0
      inclination: 1.26
      orbitalArc: 319
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 5321501727
      classification: M
      radius: 6794
      terranMass: 0.001071278081175703
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 5201804067
    temperature: 300
    satellites: []
  - name: Biham 2
    description: ''
    tags: []
    satellite:
      axialTilt: 31.59
      semiMajorAxis: 778531234.6666654
      eccentricity: 0.01
      inclination: 1.5
      orbitalArc: 278
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 8323090416
      classification: M
      radius: 5943
      terranMass: 0.004760384094496348
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial2.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 5669146479
    temperature: 290
    satellites:
      - name: Biham 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 21.37
          semiMajorAxis: 186894.2229788569
          eccentricity: 0
          inclination: 1.68
          orbitalArc: 265
          showOrbit: true
          parentId: Biham 2
        isPlanet:
          age: 4011021945
          classification: P
          radius: 824.5384384930339
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 87348
        temperature: 266
      - name: Biham 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 25.29
          semiMajorAxis: 495532.50151114183
          eccentricity: 0.01
          inclination: 0.21
          orbitalArc: 86
          showOrbit: true
          parentId: Biham 2
        isPlanet:
          age: 5358374624
          classification: L
          radius: 1152.401166304981
          terranMass: 0.7000000226672011
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 17374
        temperature: 304
  - name: Biham 3
    description: ''
    tags: []
    satellite:
      axialTilt: 9.36
      semiMajorAxis: 1509200366.1111102
      eccentricity: 0
      inclination: 1.81
      orbitalArc: 64
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 7573288620
      classification: K
      radius: 2887
      terranMass: 0.0029934293716422154
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 43443
    temperature: 212
    satellites:
      - name: Biham 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 39.29
          semiMajorAxis: 140696.4743808968
          eccentricity: 0.01
          inclination: 0.8
          orbitalArc: 83
          showOrbit: true
          parentId: Biham 3
        isPlanet:
          age: 1564690884
          classification: A
          radius: 282.5230409254956
          terranMass: 0.5000001538464275
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1764
  - name: Biham 4
    description: ''
    tags: []
    satellite:
      axialTilt: 24.54
      semiMajorAxis: 2137793004.037034
      eccentricity: 0.01
      inclination: 1.99
      orbitalArc: 329
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 697585586
      classification: C
      radius: 3383
      terranMass: 0.02799743560037536
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 47
    satellites: []
  - name: Biham 5
    description: ''
    tags: []
    satellite:
      axialTilt: 17.56
      semiMajorAxis: 2797344158.802461
      eccentricity: 0
      inclination: 1.93
      orbitalArc: 268
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 7788777875
      classification: J
      radius: 57895
      terranMass: 0.520406107215771
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 270
    satellites: []
  - name: Biham 6
    description: ''
    tags: []
    satellite:
      axialTilt: 16.53
      semiMajorAxis: 3310759304
      eccentricity: 0
      inclination: 1.41
      orbitalArc: 339
      showOrbit: true
      parentId: Biham
    isPlanet:
      age: 326354710
      classification: C
      radius: 2609
      terranMass: 0.018935426156292155
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 34
    satellites: []
commSatellite: null
assets: {}
