apiVersion: solarSystem/v1
kind: solarSystems
name: Tianguan
description: A solar system named Tianguan
position:
  x: -214818395.2330138
  'y': -83471619.90602846
  z: 21020774.52274726
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tianguan
stars:
  - name: Tianguan A
    description: ''
    tags: []
    solarMass: 11.2
    age: 369943273740
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.5
    temperature: 15500
    satellite:
      axialTilt: 0
      semiMajorAxis: 66
      eccentricity: 0
      inclination: 0
      orbitalArc: 254
      showOrbit: false
      parentId: Tianguan
  - name: Tianguan B
    description: ''
    tags: []
    solarMass: 11.2
    age: 369943273740
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.5
    temperature: 15500
    satellite:
      axialTilt: 0
      semiMajorAxis: 66
      eccentricity: 0
      inclination: 0
      orbitalArc: 434
      showOrbit: false
      parentId: Tianguan
planets:
  - name: Tianguan 1
    description: ''
    tags: []
    satellite:
      axialTilt: 17.59
      semiMajorAxis: 1932980725.6666658
      eccentricity: 0.02
      inclination: 1.28
      orbitalArc: 359
      showOrbit: true
      parentId: Tianguan
    isPlanet:
      age: 8616892302
      classification: J
      radius: 53803
      terranMass: 0.19154035537539527
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 168
    satellites: []
  - name: Tianguan 2
    description: ''
    tags: []
    satellite:
      axialTilt: 33.47
      semiMajorAxis: 3277549808.666666
      eccentricity: 0.01
      inclination: 0
      orbitalArc: 301
      showOrbit: true
      parentId: Tianguan
    isPlanet:
      age: 4937888325
      classification: J
      radius: 32797
      terranMass: 1.3441292674709413
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 252
    satellites: []
  - name: Tianguan 3
    description: ''
    tags: []
    satellite:
      axialTilt: 21.01
      semiMajorAxis: 4043731103
      eccentricity: 0.02
      inclination: 1.8
      orbitalArc: 272
      showOrbit: true
      parentId: Tianguan
    isPlanet:
      age: 9634135822
      classification: P
      radius: 6338
      terranMass: 0.0006146010507630652
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 74493
    temperature: 270
    satellites:
      - name: Tianguan 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 28.06
          semiMajorAxis: 218874.5528949622
          eccentricity: 0.01
          inclination: 1.04
          orbitalArc: 118
          showOrbit: true
          parentId: Tianguan 3
        isPlanet:
          age: 3632939161
          classification: P
          radius: 352.6033428032658
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 87727
        temperature: 264
      - name: Tianguan 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 10.55
          semiMajorAxis: 485962.85316034546
          eccentricity: 0.02
          inclination: 1.77
          orbitalArc: 356
          showOrbit: true
          parentId: Tianguan 3
        isPlanet:
          age: 707519928
          classification: C
          radius: 1272.1540658647787
          terranMass: 1.8000000247624603
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 53
commSatellite: null
assets: {}
