apiVersion: solarSystem/v1
kind: solarSystems
name: Yed Prior
description: A solar system named Yed Prior
position:
  x: 80382694.02125512
  'y': 5795088.760802379
  z: -39926081.070464484
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Yed Prior
stars:
  - name: Yed Prior A
    description: ''
    tags: []
    solarMass: 1.39
    age: 144226332791
    spectralType: K
    hue: 30
    isWhite: false
    radius: 53.5
    temperature: 3733
    satellite:
      axialTilt: 0
      semiMajorAxis: 642
      eccentricity: 0
      inclination: 0
      orbitalArc: 44
      showOrbit: false
      parentId: Yed Prior
  - name: Yed Prior B
    description: ''
    tags: []
    solarMass: 1.39
    age: 144226332791
    spectralType: K
    hue: 30
    isWhite: false
    radius: 53.5
    temperature: 3733
    satellite:
      axialTilt: 0
      semiMajorAxis: 642
      eccentricity: 0
      inclination: 0
      orbitalArc: 224
      showOrbit: false
      parentId: Yed Prior
planets:
  - name: Yed Prior 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.06
      semiMajorAxis: 3220133082
      eccentricity: 0.01
      inclination: 1.98
      orbitalArc: 19
      showOrbit: true
      parentId: Yed Prior
    isPlanet:
      age: 7434301036
      classification: P
      radius: 6496
      terranMass: 0.005708721954889763
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 41093
    temperature: 256
    satellites: []
commSatellite: null
assets: {}
