apiVersion: solarSystem/v1
kind: solarSystems
name: Propus
description: A solar system named Propus
position:
  x: -339413452.2698966
  'y': -140933657.45823863
  z: -22064319.560649347
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Propus
stars:
  - name: 'Propus '
    description: ''
    tags: []
    solarMass: 5.1
    age: 83539530838
    spectralType: M
    hue: 0
    isWhite: false
    radius: 153
    temperature: 3502
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 142
      showOrbit: false
      parentId: Propus
planets:
  - name: Propus 1
    description: ''
    tags: []
    satellite:
      axialTilt: 32.09
      semiMajorAxis: 1620320593.9999995
      eccentricity: 0.01
      inclination: 0.96
      orbitalArc: 124
      showOrbit: true
      parentId: Propus
    isPlanet:
      age: 6597052657
      classification: H
      radius: 5403
      terranMass: 0.003972896497809684
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 895
    satellites: []
  - name: Propus 2
    description: ''
    tags: []
    satellite:
      axialTilt: 8.53
      semiMajorAxis: 2673917068.6666665
      eccentricity: 0.02
      inclination: 1.03
      orbitalArc: 132
      showOrbit: true
      parentId: Propus
    isPlanet:
      age: 117947414
      classification: E
      radius: 5458
      terranMass: 0.02951044741792073
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 1409
    satellites: []
  - name: Propus 3
    description: ''
    tags: []
    satellite:
      axialTilt: 31.22
      semiMajorAxis: 3481535847.666667
      eccentricity: 0.01
      inclination: 0.29
      orbitalArc: 76
      showOrbit: true
      parentId: Propus
    isPlanet:
      age: 5637270713
      classification: K
      radius: 4392
      terranMass: 0.015379283083962176
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 43600
    temperature: 229
    satellites: []
  - name: Propus 4
    description: ''
    tags: []
    satellite:
      axialTilt: 33.38
      semiMajorAxis: 4560561411
      eccentricity: 0
      inclination: 1.35
      orbitalArc: 193
      showOrbit: true
      parentId: Propus
    isPlanet:
      age: 1591309904
      classification: F
      radius: 5745
      terranMass: 0.015917953189968536
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 820
    satellites:
      - name: Propus 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 13.84
          semiMajorAxis: 360283.45472944283
          eccentricity: 0.01
          inclination: 1.82
          orbitalArc: 292
          showOrbit: true
          parentId: Propus 4
        isPlanet:
          age: 3800965669
          classification: P
          radius: 1329.4592425440694
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 136949
        temperature: 255
commSatellite: null
assets: {}
