apiVersion: solarSystem/v1
kind: solarSystems
name: Bharani
description: A solar system named Bharani
position:
  x: -52430009.49481139
  'y': -39990911.81984574
  z: 57225391.39054368
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Bharani
stars:
  - name: Bharani A
    description: ''
    tags: []
    solarMass: 3.1
    age: 1002600355976
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.982
    temperature: 11900
    satellite:
      axialTilt: 0
      semiMajorAxis: 35.784000000000006
      eccentricity: 0
      inclination: 0
      orbitalArc: 55
      showOrbit: false
      parentId: Bharani
  - name: Bharani B
    description: ''
    tags: []
    solarMass: 3.1
    age: 1002600355976
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.982
    temperature: 11900
    satellite:
      axialTilt: 0
      semiMajorAxis: 35.784000000000006
      eccentricity: 0
      inclination: 0
      orbitalArc: 235
      showOrbit: false
      parentId: Bharani
planets:
  - name: Bharani 1
    description: ''
    tags: []
    satellite:
      axialTilt: 24.8
      semiMajorAxis: 647460254
      eccentricity: 0.01
      inclination: 1.32
      orbitalArc: 358
      showOrbit: true
      parentId: Bharani
    isPlanet:
      age: 705182094
      classification: D
      radius: 347
      terranMass: 0.006980466236435491
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 264
    satellites: []
  - name: Bharani 2
    description: ''
    tags: []
    satellite:
      axialTilt: 3.11
      semiMajorAxis: 1403746827
      eccentricity: 0.01
      inclination: 0.48
      orbitalArc: 42
      showOrbit: true
      parentId: Bharani
    isPlanet:
      age: 3308590056
      classification: O
      radius: 5675
      terranMass: 0.004943627395537595
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 555893577
    temperature: 301
    satellites:
      - name: Bharani 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.07
          semiMajorAxis: 177346.92782920462
          eccentricity: 0.02
          inclination: 0.13
          orbitalArc: 186
          showOrbit: true
          parentId: Bharani 2
        isPlanet:
          age: 1783854761
          classification: F
          radius: 1063.797502089885
          terranMass: 0.9000001344795344
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 520
      - name: Bharani 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 17.28
          semiMajorAxis: 526168.4638949519
          eccentricity: 0.01
          inclination: 0.69
          orbitalArc: 340
          showOrbit: true
          parentId: Bharani 2
        isPlanet:
          age: 7378585423
          classification: P
          radius: 1220.8085009163617
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 191022
        temperature: 263
commSatellite: null
assets: {}
