apiVersion: solarSystem/v1
kind: solarSystems
name: Ogma
description: A solar system named Ogma
position:
  x: 95357931.22842413
  'y': -81579924.6599944
  z: -39258132.20601276
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Ogma
stars:
  - name: 'Ogma '
    description: ''
    tags: []
    radius: 1.541
    temperature: 6147
    solarMass: 1.345
    age: 22878810379156
    spectralType: F
    hue: 60
    isWhite: false
    satellite:
      orbitalArc: 40
      semiMajorAxis: 0
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Ogma
planets:
  - name: Ogma 1
    description: ''
    tags: []
    isPlanet:
      radius: 4286
      age: 6548159741
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
      terranMass: 0.015065955656620212
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      classification: K
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
    population: 19331
    temperature: 205
    satellite:
      semiMajorAxis: 166546114.66666734
      eccentricity: 0
      inclination: 1.44
      orbitalArc: 272
      axialTilt: 7.68
      parentId: Ogma
      showOrbit: true
    satellites: []
  - name: Ogma 2
    description: ''
    tags: []
    isPlanet:
      radius: 134
      age: 320199260
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
      terranMass: 0.01684770637202424
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      classification: D
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
    population: 0
    temperature: 301
    satellite:
      semiMajorAxis: 1762409924.7777786
      eccentricity: 0.01
      inclination: 0.52
      orbitalArc: 338
      axialTilt: 4.49
      parentId: Ogma
      showOrbit: true
    satellites: []
  - name: Ogma 3
    description: ''
    tags: []
    isPlanet:
      radius: 26567
      age: 7597977162
      cloudMapAsset: null
      ringMapAsset: null
      terranMass: 0.5116269584131956
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 338
    satellite:
      semiMajorAxis: 2607122733
      eccentricity: 0.01
      inclination: 0.63
      orbitalArc: 56
      axialTilt: 24.37
      parentId: Ogma
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
