apiVersion: solarSystem/v1
kind: solarSystems
name: Subra
description: A solar system named Subra
position:
  x: -39832899.508661605
  'y': -12198366.408755789
  z: -57499506.04005751
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Subra
stars:
  - name: 'Subra '
    description: ''
    tags: []
    solarMass: 2.074
    age: 2619130346756
    spectralType: F
    hue: 60
    isWhite: false
    radius: 5.73
    temperature: 6107
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 324
      showOrbit: false
      parentId: Subra
planets:
  - name: Subra 1
    description: ''
    tags: []
    satellite:
      axialTilt: 29.75
      semiMajorAxis: 519341379
      eccentricity: 0.01
      inclination: 1.14
      orbitalArc: 277
      showOrbit: true
      parentId: Subra
    isPlanet:
      age: 5826170634
      classification: M
      radius: 5274
      terranMass: 0.025468226394841496
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 5228573024
    temperature: 300
    satellites:
      - name: Subra 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 10.33
          semiMajorAxis: 43889.50216065073
          eccentricity: 0
          inclination: 1.6
          orbitalArc: 54
          showOrbit: true
          parentId: Subra 1
        isPlanet:
          age: 308646363
          classification: D
          radius: 316.4590699836982
          terranMass: 0.18999974047776225
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 367
      - name: Subra 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 13.54
          semiMajorAxis: 214437.16711907194
          eccentricity: 0.01
          inclination: 0.08
          orbitalArc: 201
          showOrbit: true
          parentId: Subra 1
        isPlanet:
          age: 3077020917
          classification: P
          radius: 377.7415229010027
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 61781
        temperature: 260
      - name: Subra 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 7.66
          semiMajorAxis: 437900.11942786083
          eccentricity: 0.02
          inclination: 0.76
          orbitalArc: 9
          showOrbit: true
          parentId: Subra 1
        isPlanet:
          age: 313421837
          classification: C
          radius: 1089.3037796712956
          terranMass: 1.3000000506988099
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 44
  - name: Subra 2
    description: ''
    tags: []
    satellite:
      axialTilt: 29.46
      semiMajorAxis: 1284016839
      eccentricity: 0.01
      inclination: 0.09
      orbitalArc: 160
      showOrbit: true
      parentId: Subra
    isPlanet:
      age: 3477364359
      classification: M
      radius: 7019
      terranMass: 0.009523996089590713
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial1.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 9329182505
    temperature: 301
    satellites: []
commSatellite: null
assets: {}
