apiVersion: solarSystem/v1
kind: solarSystems
name: Castor
description: A solar system named Castor
position:
  x: -20862912.786318526
  'y': -14170148.634876918
  z: -9136223.936482865
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Castor
stars:
  - name: Castor A
    description: ''
    tags: []
    solarMass: 2.371
    age: 2799225453285
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.089
    temperature: 10286
    satellite:
      axialTilt: 0
      semiMajorAxis: 25.067999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 161
      showOrbit: false
      parentId: Castor
  - name: Castor B
    description: ''
    tags: []
    solarMass: 2.371
    age: 2799225453285
    spectralType: B
    hue: 200
    isWhite: false
    radius: 2.089
    temperature: 10286
    satellite:
      axialTilt: 0
      semiMajorAxis: 25.067999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 341
      showOrbit: false
      parentId: Castor
planets:
  - name: Castor 1
    description: ''
    tags: []
    satellite:
      axialTilt: 25.26
      semiMajorAxis: 461072745.6666667
      eccentricity: 0
      inclination: 1.72
      orbitalArc: 141
      showOrbit: true
      parentId: Castor
    isPlanet:
      age: 963463222
      classification: D
      radius: 400
      terranMass: 0.00895033070865996
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 248
    satellites: []
  - name: Castor 2
    description: ''
    tags: []
    satellite:
      axialTilt: 32.64
      semiMajorAxis: 702141169.7777781
      eccentricity: 0.01
      inclination: 0.14
      orbitalArc: 261
      showOrbit: true
      parentId: Castor
    isPlanet:
      age: 4257009588
      classification: O
      radius: 7017
      terranMass: 0.004898567263129765
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 353216283
    temperature: 298
    satellites: []
  - name: Castor 3
    description: ''
    tags: []
    satellite:
      axialTilt: 16.3
      semiMajorAxis: 925673855
      eccentricity: 0.02
      inclination: 1.24
      orbitalArc: 191
      showOrbit: true
      parentId: Castor
    isPlanet:
      age: 738957191
      classification: D
      radius: 238
      terranMass: 0.001087259667068961
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 346
    satellites: []
commSatellite: null
assets: {}
