apiVersion: stations/v1
kind: stationComplements
name: 1 Small Legacy
hasShipMap: false
stations:
  - name: Pilot
    description: Directs the movement of the ship and controls the engines
    logo: /plugins/Thorium Default/stationComplements/assets/Pilot.svg
    cards:
      - name: Engine Control
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyEngineControl
      - name: Navigation
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyNavigation
      - name: Thrusters
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyThrusters
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Engineer
    description: Controls the power, reactors, and maintenance of the ship
    logo: /plugins/Thorium Default/stationComplements/assets/Engineer.svg
    cards:
      - name: Power Distribution
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyPowerDistribution
      - name: Reactor Control
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyReactorControl
      - name: Coolant Control
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacyCoolantControl
    widgets:
      - name: Remote Access
        icon: /plugins/Thorium Default/stationComplements/assets/RemoteAccess.svg
        component: RemoteAccess
        size: sm
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
    messageGroups: []
  - name: Operations
    description: Assorted other stuff
    logo: /plugins/Thorium Default/stationComplements/assets/Operations.svg
    cards:
      - name: Sensor Scans
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacySensorScans
      - name: Sensor Grid
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: LegacySensorGrid
      - name: Alert Level
        icon: /plugins/Thorium Default/stationComplements/assets/AlertCondition.svg
        component: AlertLevel
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
      - name: Documents
        icon: /plugins/Thorium Default/stationComplements/assets/Documents.svg
        component: Documents
    widgets:
      - name: Objectives
        icon: /plugins/Thorium Default/stationComplements/assets/Objectives.svg
        component: Objectives
        size: sm
      - name: Officers Log
        icon: /plugins/Thorium Default/stationComplements/assets/OfficersLog.svg
        component: OfficersLog
      - name: Code Cyphers
        icon: /plugins/Thorium Default/stationComplements/assets/CodeCyphers.svg
        component: CodeCyphers
      - name: Messaging
        icon: /plugins/Thorium Default/stationComplements/assets/Messaging.svg
        component: Messaging
        size: lg
    messageGroups: []
flightMode: legacy
assets: {}
