apiVersion: timeline/v1
kind: reports
name: Mini Exocomp Drain
description: Send an exocomp to the relevant room and have it drain the system
category: Exocomps
tags: []
flightMode: nova
assets: {}
prerequisiteBlocks:
  - count: one
    entity: $shipId
    systemType: exocomps
    variable: exocomps
    id: blo-mp5m1app0g
    type: ShipSystemGetter
  - "0":
      conditions:
        - comparison: is not empty
          value1: $exocomps
          value2: ""
        - value1: $damageType
          value2: Plumbing
          comparison: "="
      triggerBlocks:
        - id: blo-mp5m1apq3y
          type: TimelineAvailability
          isAvailable: true
      id: blo-mp5m1apr3d
      type: IfCondition
    "1":
      conditions:
        - comparison: is not empty
          value1: $exocomps
          value2: ""
        - value1: $damageType
          value2: Corrosion
          comparison: "="
      triggerBlocks:
        - id: blo-mp5m1aps03
          type: TimelineAvailability
          isAvailable: true
      id: blo-mp5m1apt5g
      type: IfCondition
autoApplyWhenCompleted: true
steps:
  - id: dr-mp5m1apu2j
    name: Step 1
    description: >-
      The {systemName} has filled with fluid that needs to be removed. Send an
      exocomp to {room} with {parts}. Instruct the exocomp to {action} for
      {duration} seconds.
    tags: []
    blocks:
      - action: exocomps.createExocompAssignment
        values:
          damageReportId: $damageReportId
          requiredPartCount: RANDOM(1,3)
          requiredAction: drain
        id: blo-mp5m1apv2p
        type: Action
      - property: action
        variable: action
        id: blo-mp5m1apw6k
        type: ResultPropertyIntoVariable
      - property: actionDuration
        variable: duration
        id: blo-mp5m1apx0e
        type: ResultPropertyIntoVariable
      - property: assignmentId
        variable: assignmentId
        id: blo-mp5m1apy6q
        type: ResultPropertyIntoVariable
      - property: parts
        variable: parts
        id: blo-mp5m1apz3o
        type: ResultPropertyIntoVariable
      - property: room
        variable: room
        id: blo-mp5m1aq05b
        type: ResultPropertyIntoVariable
      - event: damageReports.completeDamageAssignment
        multiple: false
        persist: false
        triggerBlocks:
          - id: blo-mp5m1aq20o
            type: ResultPropertyIntoVariable
            property: damageAssignmentId
            variable: completedAssignmentId
          - id: blo-mp5m1aq33v
            type: IfCondition
            conditions:
              - comparison: "="
                value1: $completedAssignmentId
                value2: $assignmentId
            triggerBlocks:
              - id: blo-mp5m1aq414
                type: Action
                action: timeline.advance
                values: {}
        id: blo-mp5m1aq14s
        type: EventCondition
