apiVersion: solarSystem/v1
kind: solarSystems
name: Cursa
description: A solar system named Cursa
position:
  x: -45424194.07593815
  'y': 4150151.3051279983
  z: 10518371.056853345
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Cursa
stars:
  - name: Cursa A
    description: ''
    tags: []
    solarMass: 2.55
    age: 3058078011521
    spectralType: A
    hue: 180
    isWhite: true
    radius: 3.14
    temperature: 8357
    satellite:
      axialTilt: 0
      semiMajorAxis: 37.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 13
      showOrbit: false
      parentId: Cursa
  - name: Cursa B
    description: ''
    tags: []
    solarMass: 2.55
    age: 3058078011521
    spectralType: A
    hue: 180
    isWhite: true
    radius: 3.14
    temperature: 8357
    satellite:
      axialTilt: 0
      semiMajorAxis: 37.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 193
      showOrbit: false
      parentId: Cursa
planets:
  - name: Cursa 1
    description: ''
    tags: []
    satellite:
      axialTilt: 4.09
      semiMajorAxis: 527577149.000001
      eccentricity: 0.01
      inclination: 0
      orbitalArc: 267
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 5930156571
      classification: H
      radius: 4438
      terranMass: 0.0047770312135689405
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 508
    satellites:
      - name: Cursa 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 28.2
          semiMajorAxis: 140680.99189788348
          eccentricity: 0.02
          inclination: 1.52
          orbitalArc: 238
          showOrbit: true
          parentId: Cursa 1
        isPlanet:
          age: 8593876357
          classification: P
          radius: 747.2980222693641
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 120358
        temperature: 265
      - name: Cursa 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 11.96
          semiMajorAxis: 286248.8649800773
          eccentricity: 0.02
          inclination: 0.68
          orbitalArc: 53
          showOrbit: true
          parentId: Cursa 1
        isPlanet:
          age: 4654934629
          classification: O
          radius: 973.4014855181105
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 612296728
        temperature: 302
      - name: Cursa 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 8.29
          semiMajorAxis: 438692.59295211715
          eccentricity: 0.01
          inclination: 1.44
          orbitalArc: 347
          showOrbit: true
          parentId: Cursa 1
        isPlanet:
          age: 887323907
          classification: C
          radius: 927.4684840425309
          terranMass: 0.8000000669759658
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 37
  - name: Cursa 2
    description: ''
    tags: []
    satellite:
      axialTilt: 14.45
      semiMajorAxis: 861677816.3333349
      eccentricity: 0.02
      inclination: 0.32
      orbitalArc: 299
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 6271259250
      classification: K
      radius: 4467
      terranMass: 0.0063271844605339465
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 7263
    temperature: 226
    satellites:
      - name: Cursa 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 28.58
          semiMajorAxis: 80553.31847297505
          eccentricity: 0
          inclination: 1.61
          orbitalArc: 230
          showOrbit: true
          parentId: Cursa 2
        isPlanet:
          age: 6678676052
          classification: P
          radius: 433.6859202740332
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 100493
        temperature: 258
      - name: Cursa 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 12.42
          semiMajorAxis: 140418.7465025439
          eccentricity: 0.02
          inclination: 1.82
          orbitalArc: 231
          showOrbit: true
          parentId: Cursa 2
        isPlanet:
          age: 230301385
          classification: C
          radius: 799.6875212384942
          terranMass: 1.7000001343515776
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 52
      - name: Cursa 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 14.42
          semiMajorAxis: 231799.8557549804
          eccentricity: 0.01
          inclination: 1.8
          orbitalArc: 181
          showOrbit: true
          parentId: Cursa 2
        isPlanet:
          age: 4117857645
          classification: P
          radius: 600.5177610232653
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 152990
        temperature: 257
  - name: Cursa 3
    description: ''
    tags: []
    satellite:
      axialTilt: 23.74
      semiMajorAxis: 1044216660.8888931
      eccentricity: 0.02
      inclination: 1.34
      orbitalArc: 228
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 8428138501
      classification: O
      radius: 5989
      terranMass: 0.014472442691207968
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 456563141
    temperature: 295
    satellites:
      - name: Cursa 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 25.62
          semiMajorAxis: 277919.03367498255
          eccentricity: 0.01
          inclination: 0.96
          orbitalArc: 345
          showOrbit: true
          parentId: Cursa 3
        isPlanet:
          age: 608575339
          classification: D
          radius: 999.7087542265559
          terranMass: 1.2699998053801551
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 337
  - name: Cursa 4
    description: ''
    tags: []
    satellite:
      axialTilt: 8.6
      semiMajorAxis: 1294585922.8888931
      eccentricity: 0
      inclination: 1.91
      orbitalArc: 250
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 4420674823
      classification: L
      radius: 7326
      terranMass: 0.01658177669793009
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 37712
    temperature: 301
    satellites: []
  - name: Cursa 5
    description: ''
    tags: []
    satellite:
      axialTilt: 38.06
      semiMajorAxis: 1575665919.9629757
      eccentricity: 0.01
      inclination: 1.53
      orbitalArc: 239
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 5418613406
      classification: J
      radius: 38457
      terranMass: 0.6477181415079903
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 305
    satellites: []
  - name: Cursa 6
    description: ''
    tags: []
    satellite:
      axialTilt: 34.61
      semiMajorAxis: 2077081781
      eccentricity: 0.01
      inclination: 0.79
      orbitalArc: 131
      showOrbit: true
      parentId: Cursa
    isPlanet:
      age: 4018316519
      classification: J
      radius: 69126
      terranMass: 1.8399156598478827
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 281
    satellites: []
commSatellite: null
assets: {}
