apiVersion: solarSystem/v1
kind: solarSystems
name: Mimosa
description: A solar system named Mimosa
position:
  x: 15364767.631860655
  'y': 127136653.37142041
  z: -72720662.39092034
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Mimosa
stars:
  - name: Mimosa A
    description: ''
    tags: []
    solarMass: 14.5
    age: 22683524885
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.3
    temperature: 28840
    satellite:
      axialTilt: 0
      semiMajorAxis: 87.6
      eccentricity: 0
      inclination: 0
      orbitalArc: 346
      showOrbit: false
      parentId: Mimosa
  - name: Mimosa B
    description: ''
    tags: []
    solarMass: 14.5
    age: 22683524885
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.3
    temperature: 28840
    satellite:
      axialTilt: 0
      semiMajorAxis: 87.6
      eccentricity: 0
      inclination: 0
      orbitalArc: 526
      showOrbit: false
      parentId: Mimosa
planets:
  - name: Mimosa 1
    description: ''
    tags: []
    satellite:
      axialTilt: 35.33
      semiMajorAxis: 2564710460.333333
      eccentricity: 0.01
      inclination: 0.31
      orbitalArc: 102
      showOrbit: true
      parentId: Mimosa
    isPlanet:
      age: 201345691
      classification: C
      radius: 770
      terranMass: 0.00025775267622422325
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 52
    satellites: []
  - name: Mimosa 2
    description: ''
    tags: []
    satellite:
      axialTilt: 33.37
      semiMajorAxis: 3352575409.7777753
      eccentricity: 0
      inclination: 1.09
      orbitalArc: 232
      showOrbit: true
      parentId: Mimosa
    isPlanet:
      age: 387132508
      classification: D
      radius: 391
      terranMass: 0.01296884650133799
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 359
    satellites: []
  - name: Mimosa 3
    description: ''
    tags: []
    satellite:
      axialTilt: 7.2
      semiMajorAxis: 4466673663.555552
      eccentricity: 0.02
      inclination: 0.97
      orbitalArc: 238
      showOrbit: true
      parentId: Mimosa
    isPlanet:
      age: 6757300670
      classification: H
      radius: 4877
      terranMass: 0.0010352174269666222
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 698
    satellites: []
  - name: Mimosa 4
    description: ''
    tags: []
    satellite:
      axialTilt: 38.3
      semiMajorAxis: 6211385197.407402
      eccentricity: 0
      inclination: 1.72
      orbitalArc: 2
      showOrbit: true
      parentId: Mimosa
    isPlanet:
      age: 621677041
      classification: D
      radius: 305
      terranMass: 0.00026112013830380655
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 392
    satellites: []
  - name: Mimosa 5
    description: ''
    tags: []
    satellite:
      axialTilt: 8.52
      semiMajorAxis: 8321056069
      eccentricity: 0.01
      inclination: 1.42
      orbitalArc: 317
      showOrbit: true
      parentId: Mimosa
    isPlanet:
      age: 2048560461
      classification: B
      radius: 2849
      terranMass: 0.008983563639911216
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_mercury.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 700
    satellites:
      - name: Mimosa 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 36.23
          semiMajorAxis: 105147.4737934814
          eccentricity: 0.02
          inclination: 0.5
          orbitalArc: 216
          showOrbit: true
          parentId: Mimosa 5
        isPlanet:
          age: 6972975712
          classification: H
          radius: 295.35807245359945
          terranMass: 1.7000000007405731
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 0
        temperature: 867
commSatellite: null
assets: {}
