apiVersion: solarSystem/v1
kind: solarSystems
name: Pipirima
description: A solar system named Pipirima
position:
  x: 187909896.36398378
  'y': 153547625.33233005
  z: -57148933.25934358
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Pipirima
stars:
  - name: Pipirima A
    description: ''
    tags: []
    solarMass: 9.1
    age: 75473708015
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.6
    temperature: 21700
    satellite:
      axialTilt: 0
      semiMajorAxis: 67.19999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 180
      showOrbit: false
      parentId: Pipirima
  - name: Pipirima B
    description: ''
    tags: []
    solarMass: 9.1
    age: 75473708015
    spectralType: B
    hue: 200
    isWhite: false
    radius: 5.6
    temperature: 21700
    satellite:
      axialTilt: 0
      semiMajorAxis: 67.19999999999999
      eccentricity: 0
      inclination: 0
      orbitalArc: 360
      showOrbit: false
      parentId: Pipirima
planets:
  - name: Pipirima 1
    description: ''
    tags: []
    satellite:
      axialTilt: 3.11
      semiMajorAxis: 3000240254.333333
      eccentricity: 0.01
      inclination: 0.4
      orbitalArc: 91
      showOrbit: true
      parentId: Pipirima
    isPlanet:
      age: 774403951
      classification: D
      radius: 383
      terranMass: 0.004667496231535672
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 335
    satellites: []
  - name: Pipirima 2
    description: ''
    tags: []
    satellite:
      axialTilt: 3.75
      semiMajorAxis: 5475796981
      eccentricity: 0.01
      inclination: 0.01
      orbitalArc: 18
      showOrbit: true
      parentId: Pipirima
    isPlanet:
      age: 1304526806
      classification: F
      radius: 6697
      terranMass: 0.013603939280226364
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 811
    satellites:
      - name: Pipirima 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 16.9
          semiMajorAxis: 248414.90937249627
          eccentricity: 0.02
          inclination: 0.04
          orbitalArc: 83
          showOrbit: true
          parentId: Pipirima 2
        isPlanet:
          age: 6258208007
          classification: K
          radius: 359.1402833285254
          terranMass: 1.5000000313702397
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 35640
        temperature: 217
      - name: Pipirima 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 15.87
          semiMajorAxis: 327447.1964459886
          eccentricity: 0.01
          inclination: 0.95
          orbitalArc: 175
          showOrbit: true
          parentId: Pipirima 2
        isPlanet:
          age: 224413386
          classification: D
          radius: 1238.7701691957702
          terranMass: 0.29999998599699107
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 286
      - name: Pipirima 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 5.19
          semiMajorAxis: 447708.5417786228
          eccentricity: 0.01
          inclination: 0.78
          orbitalArc: 90
          showOrbit: true
          parentId: Pipirima 2
        isPlanet:
          age: 8198214306
          classification: H
          radius: 1360.8162364091877
          terranMass: 0.9000000569294165
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 0
        temperature: 545
commSatellite: null
assets: {}
