apiVersion: solarSystem/v1
kind: solarSystems
name: Sceptrum
description: A solar system named Sceptrum
position:
  x: -52527141.11538948
  'y': 14294206.614395691
  z: 19591976.798397027
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sceptrum
stars:
  - name: 'Sceptrum '
    description: ''
    tags: []
    solarMass: 1.07
    age: 1431320894464
    spectralType: K
    hue: 30
    isWhite: false
    radius: 9.8
    temperature: 4603
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 196
      showOrbit: false
      parentId: Sceptrum
planets:
  - name: Sceptrum 1
    description: ''
    tags: []
    satellite:
      axialTilt: 9.73
      semiMajorAxis: 619594706.9999993
      eccentricity: 0.01
      inclination: 0.06
      orbitalArc: 166
      showOrbit: true
      parentId: Sceptrum
    isPlanet:
      age: 208678852
      classification: D
      radius: 209
      terranMass: 0.020998439441740218
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 148
    satellites: []
  - name: Sceptrum 2
    description: ''
    tags: []
    satellite:
      axialTilt: 3.52
      semiMajorAxis: 1363224406
      eccentricity: 0
      inclination: 0.69
      orbitalArc: 127
      showOrbit: true
      parentId: Sceptrum
    isPlanet:
      age: 6606156956
      classification: O
      radius: 5312
      terranMass: 0.01332449299535353
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 458689276
    temperature: 303
    satellites:
      - name: Sceptrum 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 35.45
          semiMajorAxis: 473823.99143746274
          eccentricity: 0.01
          inclination: 1.6
          orbitalArc: 54
          showOrbit: true
          parentId: Sceptrum 2
        isPlanet:
          age: 8396525266
          classification: O
          radius: 1010.2856960287052
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Tropical.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 247849463
        temperature: 299
commSatellite: null
assets: {}
