apiVersion: solarSystem/v1
kind: solarSystems
name: Wasat
description: A solar system named Wasat
position:
  x: -27722283.356485695
  'y': -11911092.419060051
  z: -10106937.935088238
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Wasat
stars:
  - name: Wasat A
    description: ''
    tags: []
    solarMass: 1.57
    age: 7485979166201
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.31
    temperature: 6900
    satellite:
      axialTilt: 0
      semiMajorAxis: 27.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 355
      showOrbit: false
      parentId: Wasat
  - name: Wasat B
    description: ''
    tags: []
    solarMass: 1.57
    age: 7485979166201
    spectralType: F
    hue: 60
    isWhite: false
    radius: 2.31
    temperature: 6900
    satellite:
      axialTilt: 0
      semiMajorAxis: 27.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 535
      showOrbit: false
      parentId: Wasat
planets:
  - name: Wasat 1
    description: ''
    tags: []
    satellite:
      axialTilt: 7.56
      semiMajorAxis: 626855393
      eccentricity: 0.01
      inclination: 1.55
      orbitalArc: 158
      showOrbit: true
      parentId: Wasat
    isPlanet:
      age: 438753070
      classification: D
      radius: 432
      terranMass: 0.025705727526169828
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 292
    satellites: []
  - name: Wasat 2
    description: ''
    tags: []
    satellite:
      axialTilt: 9.89
      semiMajorAxis: 1025953911
      eccentricity: 0.01
      inclination: 0.48
      orbitalArc: 27
      showOrbit: true
      parentId: Wasat
    isPlanet:
      age: 8852575561
      classification: J
      radius: 34794
      terranMass: 1.3576045733533346
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous3.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 242
    satellites:
      - name: Wasat 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 21.96
          semiMajorAxis: 988906.5395605871
          eccentricity: 0.02
          inclination: 1.36
          orbitalArc: 63
          showOrbit: true
          parentId: Wasat 2
        isPlanet:
          age: 9088495611
          classification: K
          radius: 1965.3736622291324
          terranMass: 0.900000112354001
          isHabitable: true
          lifeforms:
            - None
            - Primitive single-celled organisms
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
          ringMapAsset: null
        population: 42927
        temperature: 260
      - name: Wasat 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 38.17
          semiMajorAxis: 2035265.2106977263
          eccentricity: 0.02
          inclination: 0.51
          orbitalArc: 188
          showOrbit: true
          parentId: Wasat 2
        isPlanet:
          age: 105506099
          classification: A
          radius: 6579.534746761629
          terranMass: 0.5000001089380411
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/mercurymap.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1562
      - name: Wasat 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 28.42
          semiMajorAxis: 2737876.2508499557
          eccentricity: 0
          inclination: 1.6
          orbitalArc: 34
          showOrbit: true
          parentId: Wasat 2
        isPlanet:
          age: 4369049267
          classification: P
          radius: 7822.503573857017
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 134486
        temperature: 255
commSatellite: null
assets: {}
