apiVersion: solarSystem/v1
kind: solarSystems
name: Alkes
description: A solar system named Alkes
position:
  x: -18290442.6107948
  'y': 23284298.0175392
  z: -67993089.13603826
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alkes
stars:
  - name: Alkes A
    description: ''
    tags: []
    solarMass: 1.81
    age: 1420249718492
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12.32
    temperature: 4691
    satellite:
      axialTilt: 0
      semiMajorAxis: 147.84
      eccentricity: 0
      inclination: 0
      orbitalArc: 233
      showOrbit: false
      parentId: Alkes
  - name: Alkes B
    description: ''
    tags: []
    solarMass: 1.81
    age: 1420249718492
    spectralType: K
    hue: 30
    isWhite: false
    radius: 12.32
    temperature: 4691
    satellite:
      axialTilt: 0
      semiMajorAxis: 147.84
      eccentricity: 0
      inclination: 0
      orbitalArc: 413
      showOrbit: false
      parentId: Alkes
planets:
  - name: Alkes 1
    description: ''
    tags: []
    satellite:
      axialTilt: 13.81
      semiMajorAxis: 845366963.9999998
      eccentricity: 0
      inclination: 0.08
      orbitalArc: 210
      showOrbit: true
      parentId: Alkes
    isPlanet:
      age: 437478884
      classification: E
      radius: 7223
      terranMass: 0.0030138103782120906
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 1369
    satellites: []
  - name: Alkes 2
    description: ''
    tags: []
    satellite:
      axialTilt: 23.37
      semiMajorAxis: 1244723010.9999974
      eccentricity: 0.01
      inclination: 0.35
      orbitalArc: 30
      showOrbit: true
      parentId: Alkes
    isPlanet:
      age: 6149061405
      classification: L
      radius: 6469
      terranMass: 0.0005460543575523726
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 31955
    temperature: 219
    satellites:
      - name: Alkes 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 38.47
          semiMajorAxis: 252270.63175320983
          eccentricity: 0
          inclination: 0.89
          orbitalArc: 134
          showOrbit: true
          parentId: Alkes 2
        isPlanet:
          age: 336289271
          classification: D
          radius: 809.5206594880137
          terranMass: 1.319999794449547
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 378
      - name: Alkes 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 22.66
          semiMajorAxis: 511719.871431009
          eccentricity: 0.01
          inclination: 0.61
          orbitalArc: 106
          showOrbit: true
          parentId: Alkes 2
        isPlanet:
          age: 5620993329
          classification: P
          radius: 1368.2349503502915
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 142203
        temperature: 260
  - name: Alkes 3
    description: ''
    tags: []
    satellite:
      axialTilt: 18.39
      semiMajorAxis: 2261946292.3333263
      eccentricity: 0.02
      inclination: 0.89
      orbitalArc: 344
      showOrbit: true
      parentId: Alkes
    isPlanet:
      age: 131927701
      classification: D
      radius: 410
      terranMass: 0.012805383971933688
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 374
    satellites: []
  - name: Alkes 4
    description: ''
    tags: []
    satellite:
      axialTilt: 37.15
      semiMajorAxis: 2825026038
      eccentricity: 0
      inclination: 0.83
      orbitalArc: 25
      showOrbit: true
      parentId: Alkes
    isPlanet:
      age: 302504775
      classification: D
      radius: 311
      terranMass: 0.02247959204544001
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 283
    satellites: []
commSatellite: null
assets: {}
