apiVersion: solarSystem/v1
kind: solarSystems
name: Elnath
description: A solar system named Elnath
position:
  x: -61206615.994837165
  'y': -33745598.949868985
  z: 9067712.292786138
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Elnath
stars:
  - name: Elnath A
    description: ''
    tags: []
    solarMass: 5
    age: 381582052250
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.7
    temperature: 13600
    satellite:
      axialTilt: 0
      semiMajorAxis: 56.400000000000006
      eccentricity: 0
      inclination: 0
      orbitalArc: 183
      showOrbit: false
      parentId: Elnath
  - name: Elnath B
    description: ''
    tags: []
    solarMass: 5
    age: 381582052250
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.7
    temperature: 13600
    satellite:
      axialTilt: 0
      semiMajorAxis: 56.400000000000006
      eccentricity: 0
      inclination: 0
      orbitalArc: 363
      showOrbit: false
      parentId: Elnath
planets:
  - name: Elnath 1
    description: ''
    tags: []
    satellite:
      axialTilt: 13.74
      semiMajorAxis: 2347622969.333333
      eccentricity: 0.02
      inclination: 1.28
      orbitalArc: 220
      showOrbit: true
      parentId: Elnath
    isPlanet:
      age: 7569661407
      classification: M
      radius: 5331
      terranMass: 0.022629309024226225
      isHabitable: true
      lifeforms:
        - Varied and extensive vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Terrestrial4.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 7910641467
    temperature: 290
    satellites: []
  - name: Elnath 2
    description: ''
    tags: []
    satellite:
      axialTilt: 34.2
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.76
      orbitalArc: 340
      showOrbit: true
      parentId: Elnath
    isPlanet:
      age: 5621518665
      classification: J
      radius: 52933
      terranMass: 0.41649650030105756
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 275
    satellites: []
commSatellite: null
assets: {}
