apiVersion: solarSystem/v1
kind: solarSystems
name: Imai
description: A solar system named Imai
position:
  x: 6216434.099103895
  'y': 155127296.46485445
  z: -93932051.80893613
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Imai
stars:
  - name: Imai A
    description: ''
    tags: []
    solarMass: 8.9
    age: 57012238328
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.21
    temperature: 20400
    satellite:
      axialTilt: 0
      semiMajorAxis: 86.52
      eccentricity: 0
      inclination: 0
      orbitalArc: 115
      showOrbit: false
      parentId: Imai
  - name: Imai B
    description: ''
    tags: []
    solarMass: 8.9
    age: 57012238328
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.21
    temperature: 20400
    satellite:
      axialTilt: 0
      semiMajorAxis: 86.52
      eccentricity: 0
      inclination: 0
      orbitalArc: 295
      showOrbit: false
      parentId: Imai
planets:
  - name: Imai 1
    description: ''
    tags: []
    satellite:
      axialTilt: 17.39
      semiMajorAxis: 2986122262.333333
      eccentricity: 0.02
      inclination: 0.36
      orbitalArc: 214
      showOrbit: true
      parentId: Imai
    isPlanet:
      age: 366270391
      classification: C
      radius: 2967
      terranMass: 0.007606997880662565
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 0
    temperature: 45
    satellites: []
  - name: Imai 2
    description: ''
    tags: []
    satellite:
      axialTilt: 38.51
      semiMajorAxis: 6052903199.333332
      eccentricity: 0.02
      inclination: 1.45
      orbitalArc: 170
      showOrbit: true
      parentId: Imai
    isPlanet:
      age: 210863694
      classification: D
      radius: 379
      terranMass: 0.0004885960637789305
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 296
    satellites: []
  - name: Imai 3
    description: ''
    tags: []
    satellite:
      axialTilt: 19.82
      semiMajorAxis: 9016835124
      eccentricity: 0.01
      inclination: 1.14
      orbitalArc: 346
      showOrbit: true
      parentId: Imai
    isPlanet:
      age: 798573590
      classification: D
      radius: 68
      terranMass: 0.002459235966609203
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 217
    satellites: []
commSatellite: null
assets: {}
