apiVersion: solarSystem/v1
kind: solarSystems
name: Deneb Algedi
description: A solar system named Deneb Algedi
position:
  x: 10718218.886630472
  'y': 5653956.282671177
  z: 16354339.494245097
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Deneb Algedi
stars:
  - name: Deneb Algedi A
    description: ''
    tags: []
    solarMass: 2
    age: 11127642174781
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.91
    temperature: 7301
    satellite:
      axialTilt: 0
      semiMajorAxis: 22.919999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 7
      showOrbit: false
      parentId: Deneb Algedi
  - name: Deneb Algedi B
    description: ''
    tags: []
    solarMass: 2
    age: 11127642174781
    spectralType: F
    hue: 60
    isWhite: false
    radius: 1.91
    temperature: 7301
    satellite:
      axialTilt: 0
      semiMajorAxis: 22.919999999999998
      eccentricity: 0
      inclination: 0
      orbitalArc: 187
      showOrbit: false
      parentId: Deneb Algedi
planets:
  - name: Deneb Algedi 1
    description: ''
    tags: []
    satellite:
      axialTilt: 16.78
      semiMajorAxis: 200399127
      eccentricity: 0.01
      inclination: 1.54
      orbitalArc: 241
      showOrbit: true
      parentId: Deneb Algedi
    isPlanet:
      age: 6568592359
      classification: P
      radius: 5534
      terranMass: 0.004188499035474028
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 125982
    temperature: 267
    satellites: []
  - name: Deneb Algedi 2
    description: ''
    tags: []
    satellite:
      axialTilt: 30.37
      semiMajorAxis: 425110143
      eccentricity: 0.01
      inclination: 1.47
      orbitalArc: 63
      showOrbit: true
      parentId: Deneb Algedi
    isPlanet:
      age: 5266710015
      classification: K
      radius: 2854
      terranMass: 0.0018617072765317203
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 38281
    temperature: 297
    satellites:
      - name: Deneb Algedi 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 12.01
          semiMajorAxis: 46644.80036040605
          eccentricity: 0
          inclination: 0.15
          orbitalArc: 26
          showOrbit: true
          parentId: Deneb Algedi 2
        isPlanet:
          age: 7440695992
          classification: H
          radius: 232.41445802140854
          terranMass: 1.9000001259685222
          isHabitable: false
          lifeforms:
            - None
            - Primitive single-celled organisms
            - Draught-resistant plants
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_venus_atmosphere.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 763
      - name: Deneb Algedi 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 11.73
          semiMajorAxis: 102657.25409420769
          eccentricity: 0.01
          inclination: 0.2
          orbitalArc: 109
          showOrbit: true
          parentId: Deneb Algedi 2
        isPlanet:
          age: 5688409697
          classification: L
          radius: 299.2922859889437
          terranMass: 1.700000082343223
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
          ringMapAsset: null
        population: 48669
        temperature: 330
commSatellite: null
assets: {}
