apiVersion: solarSystem/v1
kind: solarSystems
name: Mira
description: A solar system named Mira
position:
  x: -90012846.78557627
  'y': 8196491.972527463
  z: 129335060.50913133
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Mira
stars:
  - name: Mira A
    description: ''
    tags: []
    solarMass: 1.18
    age: 8515967084
    spectralType: M
    hue: 0
    isWhite: false
    radius: 332
    temperature: 2918
    satellite:
      axialTilt: 0
      semiMajorAxis: 3984
      eccentricity: 0
      inclination: 0
      orbitalArc: 296
      showOrbit: false
      parentId: Mira
  - name: Mira B
    description: ''
    tags: []
    solarMass: 1.18
    age: 8515967084
    spectralType: M
    hue: 0
    isWhite: false
    radius: 332
    temperature: 2918
    satellite:
      axialTilt: 0
      semiMajorAxis: 3984
      eccentricity: 0
      inclination: 0
      orbitalArc: 476
      showOrbit: false
      parentId: Mira
planets:
  - name: Mira 1
    description: ''
    tags: []
    satellite:
      axialTilt: 19.33
      semiMajorAxis: 2439947731.666666
      eccentricity: 0.01
      inclination: 0.89
      orbitalArc: 232
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 6664510244
      classification: H
      radius: 4649
      terranMass: 0.019512753999854658
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
        - Draught-resistant plants
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDesertic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 553
    satellites: []
  - name: Mira 2
    description: ''
    tags: []
    satellite:
      axialTilt: 13.75
      semiMajorAxis: 3084550094.555556
      eccentricity: 0.02
      inclination: 0.14
      orbitalArc: 235
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 780242720
      classification: D
      radius: 329
      terranMass: 0.0038979694666785537
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 331
    satellites: []
  - name: Mira 3
    description: ''
    tags: []
    satellite:
      axialTilt: 7.24
      semiMajorAxis: 3693177130.7407455
      eccentricity: 0.01
      inclination: 1.44
      orbitalArc: 24
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 994056310
      classification: C
      radius: 2698
      terranMass: 0.017197292376832627
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 41
    satellites:
      - name: Mira 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 30
          semiMajorAxis: 88167.69821642431
          eccentricity: 0
          inclination: 1.85
          orbitalArc: 275
          showOrbit: true
          parentId: Mira 3
        isPlanet:
          age: 388332331
          classification: D
          radius: 343.7096888424386
          terranMass: 0.1899997672612106
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 379
      - name: Mira 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 18.66
          semiMajorAxis: 222463.68213396237
          eccentricity: 0.02
          inclination: 0.23
          orbitalArc: 179
          showOrbit: true
          parentId: Mira 3
        isPlanet:
          age: 6755946355
          classification: P
          radius: 567.5093931988836
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 80316
        temperature: 263
  - name: Mira 4
    description: ''
    tags: []
    satellite:
      axialTilt: 2.42
      semiMajorAxis: 3917591169.3457227
      eccentricity: 0.01
      inclination: 1.67
      orbitalArc: 212
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 950696834
      classification: A
      radius: 1179
      terranMass: 0.0009549081805408638
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAuric.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 1435
    satellites: []
  - name: Mira 5
    description: ''
    tags: []
    satellite:
      axialTilt: 3.24
      semiMajorAxis: 4298368267.498128
      eccentricity: 0.01
      inclination: 0.03
      orbitalArc: 187
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 6386660803
      classification: K
      radius: 2787
      terranMass: 0.01828767741250811
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 19856
    temperature: 147
    satellites: []
  - name: Mira 6
    description: ''
    tags: []
    satellite:
      axialTilt: 36.09
      semiMajorAxis: 5448012569.332086
      eccentricity: 0.01
      inclination: 0.49
      orbitalArc: 5
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 846117562
      classification: C
      radius: 2835
      terranMass: 0.002531524076095459
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 54
    satellites:
      - name: Mira 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 3.03
          semiMajorAxis: 45088.18914923734
          eccentricity: 0.02
          inclination: 1.36
          orbitalArc: 224
          showOrbit: true
          parentId: Mira 6
        isPlanet:
          age: 211366918
          classification: D
          radius: 162.30722371746256
          terranMass: 0.979999732225292
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 161
      - name: Mira 6b
        description: ''
        tags: []
        satellite:
          axialTilt: 12.89
          semiMajorAxis: 110959.85792698109
          eccentricity: 0.01
          inclination: 0.47
          orbitalArc: 300
          showOrbit: true
          parentId: Mira 6
        isPlanet:
          age: 2070928911
          classification: F
          radius: 226.57323619428166
          terranMass: 1.7000000938173039
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 749
      - name: Mira 6c
        description: ''
        tags: []
        satellite:
          axialTilt: 25.88
          semiMajorAxis: 156241.01242093992
          eccentricity: 0.01
          inclination: 0.6
          orbitalArc: 161
          showOrbit: true
          parentId: Mira 6
        isPlanet:
          age: 501512896
          classification: C
          radius: 580.8216075127879
          terranMass: 1.0000001981962372
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 47
  - name: Mira 7
    description: ''
    tags: []
    satellite:
      axialTilt: 18.1
      semiMajorAxis: 6085270009
      eccentricity: 0
      inclination: 1.38
      orbitalArc: 49
      showOrbit: true
      parentId: Mira
    isPlanet:
      age: 8021494552
      classification: O
      radius: 7409
      terranMass: 0.007778755256505393
      isHabitable: true
      lifeforms:
        - Aquatic-based vegetation and animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 109639210
    temperature: 302
    satellites: []
commSatellite: null
assets: {}
