apiVersion: solarSystem/v1
kind: solarSystems
name: Tureis
description: A solar system named Tureis
position:
  x: -25865633.794313148
  'y': 13757066.82628618
  z: -16091194.738556417
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Tureis
stars:
  - name: Tureis A
    description: ''
    tags: []
    solarMass: 1.5
    age: 3570167854597
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.52
    temperature: 6650
    satellite:
      axialTilt: 0
      semiMajorAxis: 42.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 356
      showOrbit: false
      parentId: Tureis
  - name: Tureis B
    description: ''
    tags: []
    solarMass: 1.5
    age: 3570167854597
    spectralType: F
    hue: 60
    isWhite: false
    radius: 3.52
    temperature: 6650
    satellite:
      axialTilt: 0
      semiMajorAxis: 42.24
      eccentricity: 0
      inclination: 0
      orbitalArc: 536
      showOrbit: false
      parentId: Tureis
planets:
  - name: Tureis 1
    description: ''
    tags: []
    satellite:
      axialTilt: 15.12
      semiMajorAxis: 678000470.9999993
      eccentricity: 0.02
      inclination: 1.4
      orbitalArc: 286
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 79961443
      classification: D
      radius: 276
      terranMass: 0.013629536249543512
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 0
    temperature: 282
    satellites: []
  - name: Tureis 2
    description: ''
    tags: []
    satellite:
      axialTilt: 21.41
      semiMajorAxis: 1003588761.6666648
      eccentricity: 0
      inclination: 0.65
      orbitalArc: 226
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 5276769274
      classification: J
      radius: 52855
      terranMass: 0.7416002339687198
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 305
    satellites:
      - name: Tureis 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 5.65
          semiMajorAxis: 2174691.815740304
          eccentricity: 0.01
          inclination: 1.2
          orbitalArc: 34
          showOrbit: true
          parentId: Tureis 2
        isPlanet:
          age: 100300036
          classification: D
          radius: 6903.783542032711
          terranMass: 0.889999735027825
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 371
  - name: Tureis 3
    description: ''
    tags: []
    satellite:
      axialTilt: 24.06
      semiMajorAxis: 1376417984.6666646
      eccentricity: 0
      inclination: 1.47
      orbitalArc: 324
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 451282225
      classification: D
      radius: 95
      terranMass: 0.002926022467308379
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 221
    satellites: []
  - name: Tureis 4
    description: ''
    tags: []
    satellite:
      axialTilt: 23.9
      semiMajorAxis: 1876720419.5555487
      eccentricity: 0.01
      inclination: 1.15
      orbitalArc: 138
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 396990003
      classification: C
      radius: 2870
      terranMass: 0.013780548521027136
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 47
    satellites:
      - name: Tureis 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 14.87
          semiMajorAxis: 147572.36160148104
          eccentricity: 0
          inclination: 0.49
          orbitalArc: 262
          showOrbit: true
          parentId: Tureis 4
        isPlanet:
          age: 7245519891
          classification: P
          radius: 301.16808490098174
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 128405
        temperature: 265
  - name: Tureis 5
    description: ''
    tags: []
    satellite:
      axialTilt: 35.89
      semiMajorAxis: 3086945571.8147964
      eccentricity: 0.02
      inclination: 0.73
      orbitalArc: 74
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 550610140
      classification: D
      radius: 200
      terranMass: 0.008439839491771612
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 215
    satellites: []
  - name: Tureis 6
    description: ''
    tags: []
    satellite:
      axialTilt: 14.59
      semiMajorAxis: 3710991094
      eccentricity: 0.01
      inclination: 1.33
      orbitalArc: 2
      showOrbit: true
      parentId: Tureis
    isPlanet:
      age: 6580336110
      classification: J
      radius: 56831
      terranMass: 0.15402452513436432
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous4.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 0
    temperature: 169
    satellites:
      - name: Tureis 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 22.63
          semiMajorAxis: 4373264.381032803
          eccentricity: 0
          inclination: 1.19
          orbitalArc: 124
          showOrbit: true
          parentId: Tureis 6
        isPlanet:
          age: 8519821655
          classification: O
          radius: 12215.822293387719
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 460730877
        temperature: 295
commSatellite: null
assets: {}
