apiVersion: solarSystem/v1
kind: solarSystems
name: Alsafi
description: A solar system named Alsafi
position:
  x: 3156433.5064255777
  'y': -9256769.085445054
  z: 1345679.2989161047
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alsafi
stars:
  - name: Alsafi A
    description: ''
    tags: []
    solarMass: 0.84
    age: 106591626289800
    spectralType: G
    hue: 45
    isWhite: false
    radius: 0.772
    temperature: 5255
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.264
      eccentricity: 0
      inclination: 0
      orbitalArc: 99
      showOrbit: false
      parentId: Alsafi
  - name: Alsafi B
    description: ''
    tags: []
    solarMass: 0.84
    age: 106591626289800
    spectralType: G
    hue: 45
    isWhite: false
    radius: 0.772
    temperature: 5255
    satellite:
      axialTilt: 0
      semiMajorAxis: 9.264
      eccentricity: 0
      inclination: 0
      orbitalArc: 279
      showOrbit: false
      parentId: Alsafi
planets:
  - name: Alsafi 1
    description: ''
    tags: []
    satellite:
      axialTilt: 6.28
      semiMajorAxis: 439928715.00000024
      eccentricity: 0.01
      inclination: 0.77
      orbitalArc: 344
      showOrbit: true
      parentId: Alsafi
    isPlanet:
      age: 5176193516
      classification: K
      radius: 4363
      terranMass: 0.022002689565018444
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 15522
    temperature: 257
    satellites:
      - name: Alsafi 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 26
          semiMajorAxis: 116680.49144170854
          eccentricity: 0.01
          inclination: 0.64
          orbitalArc: 142
          showOrbit: true
          parentId: Alsafi 1
        isPlanet:
          age: 761920693
          classification: C
          radius: 260.447525539528
          terranMass: 1.4000001977429193
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 36
  - name: Alsafi 2
    description: ''
    tags: []
    satellite:
      axialTilt: 12.58
      semiMajorAxis: 672649027.3333342
      eccentricity: 0.01
      inclination: 1.76
      orbitalArc: 91
      showOrbit: true
      parentId: Alsafi
    isPlanet:
      age: 960928641
      classification: C
      radius: 2335
      terranMass: 0.020520663375686716
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureDust.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 43
    satellites: []
  - name: Alsafi 3
    description: ''
    tags: []
    satellite:
      axialTilt: 33.22
      semiMajorAxis: 1548444045.666669
      eccentricity: 0.01
      inclination: 0.18
      orbitalArc: 134
      showOrbit: true
      parentId: Alsafi
    isPlanet:
      age: 6229826882
      classification: J
      radius: 65422
      terranMass: 0.537580285684108
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 268
    satellites:
      - name: Alsafi 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 8.66
          semiMajorAxis: 2366648.8323213346
          eccentricity: 0
          inclination: 1.38
          orbitalArc: 82
          showOrbit: true
          parentId: Alsafi 3
        isPlanet:
          age: 1260824968
          classification: F
          radius: 3872.266712690929
          terranMass: 0.5000000807306372
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 743
      - name: Alsafi 3b
        description: ''
        tags: []
        satellite:
          axialTilt: 25.14
          semiMajorAxis: 5575267.676451475
          eccentricity: 0.01
          inclination: 0.96
          orbitalArc: 176
          showOrbit: true
          parentId: Alsafi 3
        isPlanet:
          age: 850880232
          classification: D
          radius: 13211.534778321033
          terranMass: 0.6199996273055948
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 381
  - name: Alsafi 4
    description: ''
    tags: []
    satellite:
      axialTilt: 2.34
      semiMajorAxis: 2968970924
      eccentricity: 0.02
      inclination: 1.09
      orbitalArc: 96
      showOrbit: true
      parentId: Alsafi
    isPlanet:
      age: 572765704
      classification: C
      radius: 1413
      terranMass: 0.0038286605637482124
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 54
    satellites: []
commSatellite: null
assets: {}
