apiVersion: solarSystem/v1
kind: solarSystems
name: Eltanin
description: A solar system named Eltanin
position:
  x: 50429095.200771675
  'y': -63379797.16280958
  z: -746828.9618257955
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Eltanin
stars:
  - name: Eltanin A
    description: ''
    tags: []
    radius: 51.8
    temperature: 3964
    solarMass: 2.14
    age: 186289747927
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 126
      semiMajorAxis: 621.5999999999999
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Eltanin
  - name: Eltanin B
    description: ''
    tags: []
    radius: 51.8
    temperature: 3964
    solarMass: 2.14
    age: 186289747927
    spectralType: K
    hue: 30
    isWhite: false
    satellite:
      orbitalArc: 306
      semiMajorAxis: 621.5999999999999
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Eltanin
planets:
  - name: Eltanin 1
    description: ''
    tags: []
    isPlanet:
      radius: 51453
      age: 3750839567
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: null
      terranMass: 0.4081662465581126
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_neptune.jpg
      classification: J
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 135
    satellite:
      semiMajorAxis: 4000000000
      eccentricity: 0
      inclination: 1.86
      orbitalArc: 99
      axialTilt: 0.92
      parentId: Eltanin
      showOrbit: true
    satellites:
      - name: Eltanin 1a
        description: ''
        tags: []
        isPlanet:
          radius: 8974.446808983828
          age: 1104798855
          ringMapAsset: null
          terranMass: 1.5000000834050158
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
          classification: E
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
        population: 0
        temperature: 1246
        satellite:
          semiMajorAxis: 1518051.5439350447
          eccentricity: 0.01
          inclination: 0.93
          orbitalArc: 148
          axialTilt: 39.91
          parentId: Eltanin 1
          showOrbit: true
        satellites: []
      - name: Eltanin 1b
        description: ''
        tags: []
        isPlanet:
          radius: 9019.857665397205
          age: 5476112213
          cloudMapAsset: null
          ringMapAsset: null
          terranMass: 1.5
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          classification: P
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
        population: 144021
        temperature: 256
        satellite:
          semiMajorAxis: 2480460.8579842313
          eccentricity: 0
          inclination: 1.23
          orbitalArc: 231
          axialTilt: 16.55
          parentId: Eltanin 1
          showOrbit: true
        satellites: []
commSatellite: null
assets: {}
