apiVersion: solarSystem/v1
kind: solarSystems
name: Matar
description: A solar system named Matar
position:
  x: 25021960.619098514
  'y': -44211062.10857979
  z: 71654217.69519211
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Matar
stars:
  - name: 'Matar '
    description: ''
    tags: []
    solarMass: 3.51
    age: 552286240502
    spectralType: K
    hue: 30
    isWhite: false
    radius: 24.51
    temperature: 4970
    satellite:
      axialTilt: 0
      semiMajorAxis: 0
      eccentricity: 0
      inclination: 0
      orbitalArc: 269
      showOrbit: false
      parentId: Matar
planets:
  - name: Matar 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.33
      semiMajorAxis: 2087390796
      eccentricity: 0.01
      inclination: 0.08
      orbitalArc: 176
      showOrbit: true
      parentId: Matar
    isPlanet:
      age: 7927324782
      classification: K
      radius: 4226
      terranMass: 0.01739235256028187
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: null
    population: 40226
    temperature: 296
    satellites: []
commSatellite: null
assets: {}
