apiVersion: solarSystem/v1
kind: solarSystems
name: Sargas
description: A solar system named Sargas
position:
  x: 114838251.12254836
  'y': 107606774.5008055
  z: -11402241.211591415
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Sargas
stars:
  - name: Sargas A
    description: ''
    tags: []
    solarMass: 3.1
    age: 93001067863
    spectralType: F
    hue: 60
    isWhite: false
    radius: 35
    temperature: 6294
    satellite:
      axialTilt: 0
      semiMajorAxis: 420
      eccentricity: 0
      inclination: 0
      orbitalArc: 43
      showOrbit: false
      parentId: Sargas
  - name: Sargas B
    description: ''
    tags: []
    solarMass: 3.1
    age: 93001067863
    spectralType: F
    hue: 60
    isWhite: false
    radius: 35
    temperature: 6294
    satellite:
      axialTilt: 0
      semiMajorAxis: 420
      eccentricity: 0
      inclination: 0
      orbitalArc: 223
      showOrbit: false
      parentId: Sargas
planets:
  - name: Sargas 1
    description: ''
    tags: []
    satellite:
      axialTilt: 31.04
      semiMajorAxis: 2335152445.333333
      eccentricity: 0
      inclination: 1.15
      orbitalArc: 147
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 734045298
      classification: D
      radius: 311
      terranMass: 0.0090931738027175
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 346
    satellites: []
  - name: Sargas 2
    description: ''
    tags: []
    satellite:
      axialTilt: 15.08
      semiMajorAxis: 3010748804.444443
      eccentricity: 0.02
      inclination: 1.93
      orbitalArc: 245
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 679423033
      classification: D
      radius: 278
      terranMass: 0.01464349848596384
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSmall.png
    population: 0
    temperature: 265
    satellites: []
  - name: Sargas 3
    description: ''
    tags: []
    satellite:
      axialTilt: 6.62
      semiMajorAxis: 3424842661.8518486
      eccentricity: 0.01
      inclination: 0.62
      orbitalArc: 89
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 8038331263
      classification: J
      radius: 61183
      terranMass: 0.1097209293941783
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 243
    satellites:
      - name: Sargas 3a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.14
          semiMajorAxis: 3761412.962143982
          eccentricity: 0.01
          inclination: 0.3
          orbitalArc: 129
          showOrbit: true
          parentId: Sargas 3
        isPlanet:
          age: 9438241302
          classification: O
          radius: 12455.009808423782
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 485008618
        temperature: 291
  - name: Sargas 4
    description: ''
    tags: []
    satellite:
      axialTilt: 33.84
      semiMajorAxis: 3662945473.111097
      eccentricity: 0
      inclination: 0.83
      orbitalArc: 48
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 4794608100
      classification: J
      radius: 29035
      terranMass: 0.3373634812835053
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_uranus.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSwept.png
      ringMapAsset: null
    population: 0
    temperature: 167
    satellites: []
  - name: Sargas 5
    description: ''
    tags: []
    satellite:
      axialTilt: 20.48
      semiMajorAxis: 4037974693.851828
      eccentricity: 0.01
      inclination: 0.07
      orbitalArc: 22
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 3909363520
      classification: J
      radius: 50453
      terranMass: 0.9853979691619514
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiantSharp.png
      ringMapAsset: null
    population: 0
    temperature: 136
    satellites: []
  - name: Sargas 6
    description: ''
    tags: []
    satellite:
      axialTilt: 5.35
      semiMajorAxis: 4207945636.1727576
      eccentricity: 0.01
      inclination: 1.25
      orbitalArc: 271
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 5979014459
      classification: K
      radius: 4644
      terranMass: 0.001957945398967526
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 46017
    temperature: 209
    satellites:
      - name: Sargas 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 15.07
          semiMajorAxis: 418684.41379903734
          eccentricity: 0.02
          inclination: 0.19
          orbitalArc: 81
          showOrbit: true
          parentId: Sargas 6
        isPlanet:
          age: 6733445938
          classification: O
          radius: 1004.0393616283869
          terranMass: 1.5
          isHabitable: true
          lifeforms:
            - Aquatic-based vegetation and animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Swamp.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 425365979
        temperature: 290
  - name: Sargas 7
    description: ''
    tags: []
    satellite:
      axialTilt: 38.71
      semiMajorAxis: 4295334909
      eccentricity: 0.02
      inclination: 0.02
      orbitalArc: 351
      showOrbit: true
      parentId: Sargas
    isPlanet:
      age: 4368913262
      classification: K
      radius: 3146
      terranMass: 0.04267363723941317
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: null
    population: 1731
    temperature: 297
    satellites: []
commSatellite: null
assets: {}
