apiVersion: solarSystem/v1
kind: solarSystems
name: Electra
description: A solar system named Electra
position:
  x: -159605614.80682614
  'y': -85950893.25267905
  z: 106770403.79806387
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Electra
stars:
  - name: Electra A
    description: ''
    tags: []
    solarMass: 4.6
    age: 218527900048
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.06
    temperature: 13484
    satellite:
      axialTilt: 0
      semiMajorAxis: 72.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 28
      showOrbit: false
      parentId: Electra
  - name: Electra B
    description: ''
    tags: []
    solarMass: 4.6
    age: 218527900048
    spectralType: B
    hue: 200
    isWhite: false
    radius: 6.06
    temperature: 13484
    satellite:
      axialTilt: 0
      semiMajorAxis: 72.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 208
      showOrbit: false
      parentId: Electra
planets:
  - name: Electra 1
    description: ''
    tags: []
    satellite:
      axialTilt: 30.82
      semiMajorAxis: 1747536372.3333342
      eccentricity: 0.02
      inclination: 0.69
      orbitalArc: 29
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 741227722
      classification: D
      radius: 362
      terranMass: 0.005885203822745906
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesDust.png
    population: 0
    temperature: 287
    satellites: []
  - name: Electra 2
    description: ''
    tags: []
    satellite:
      axialTilt: 37.86
      semiMajorAxis: 2967627595.333334
      eccentricity: 0.01
      inclination: 0.58
      orbitalArc: 124
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 7708117561
      classification: P
      radius: 6511
      terranMass: 0.008276767363021329
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 101926
    temperature: 263
    satellites:
      - name: Electra 2a
        description: ''
        tags: []
        satellite:
          axialTilt: 9.77
          semiMajorAxis: 83923.89168906608
          eccentricity: 0.01
          inclination: 1.06
          orbitalArc: 253
          showOrbit: true
          parentId: Electra 2
        isPlanet:
          age: 777088168
          classification: D
          radius: 325.72378923643237
          terranMass: 0.30999981128144793
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 317
      - name: Electra 2b
        description: ''
        tags: []
        satellite:
          axialTilt: 34.02
          semiMajorAxis: 391908.9684279697
          eccentricity: 0.01
          inclination: 0.17
          orbitalArc: 218
          showOrbit: true
          parentId: Electra 2
        isPlanet:
          age: 8289315014
          classification: P
          radius: 580.2813741414416
          terranMass: 0.5
          isHabitable: true
          lifeforms:
            - Hardy vegetation, animal life, humanoids
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 80459
        temperature: 270
      - name: Electra 2c
        description: ''
        tags: []
        satellite:
          axialTilt: 34.56
          semiMajorAxis: 608904.0064451904
          eccentricity: 0
          inclination: 1.81
          orbitalArc: 85
          showOrbit: true
          parentId: Electra 2
        isPlanet:
          age: 2764865193
          classification: F
          radius: 1492.4117805029177
          terranMass: 2.3000000796905216
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCrimson.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 695
  - name: Electra 3
    description: ''
    tags: []
    satellite:
      axialTilt: 25.58
      semiMajorAxis: 3329243915.222222
      eccentricity: 0
      inclination: 0.81
      orbitalArc: 197
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 3557890439
      classification: G
      radius: 6142
      terranMass: 0.0006373270259092857
      isHabitable: false
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChlorine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 0
    temperature: 473
    satellites: []
  - name: Electra 4
    description: ''
    tags: []
    satellite:
      axialTilt: 26.8
      semiMajorAxis: 3534211508.851851
      eccentricity: 0
      inclination: 1.77
      orbitalArc: 210
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 7434223257
      classification: K
      radius: 3981
      terranMass: 0.03943953549554751
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings2.png
    population: 5944
    temperature: 178
    satellites:
      - name: Electra 4a
        description: ''
        tags: []
        satellite:
          axialTilt: 6.65
          semiMajorAxis: 94673.30958328133
          eccentricity: 0
          inclination: 0.34
          orbitalArc: 174
          showOrbit: true
          parentId: Electra 4
        isPlanet:
          age: 287310858
          classification: D
          radius: 296.7815347438286
          terranMass: 0.8299996964540537
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 339
  - name: Electra 5
    description: ''
    tags: []
    satellite:
      axialTilt: 21.69
      semiMajorAxis: 3646327206.925914
      eccentricity: 0
      inclination: 0.96
      orbitalArc: 210
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 9672187318
      classification: K
      radius: 2867
      terranMass: 0.0003494608763114581
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesClouds.png
    population: 20884
    temperature: 292
    satellites:
      - name: Electra 5a
        description: ''
        tags: []
        satellite:
          axialTilt: 20.9
          semiMajorAxis: 256344.13655326804
          eccentricity: 0.02
          inclination: 1.55
          orbitalArc: 269
          showOrbit: true
          parentId: Electra 5
        isPlanet:
          age: 2152080244
          classification: F
          radius: 647.3336781648183
          terranMass: 1.3000001132279784
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCimmerian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 513
  - name: Electra 6
    description: ''
    tags: []
    satellite:
      axialTilt: 29.15
      semiMajorAxis: 3825123460.9382024
      eccentricity: 0.01
      inclination: 1.45
      orbitalArc: 156
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 5446280171
      classification: P
      radius: 6950
      terranMass: 0.018127991872753015
      isHabitable: true
      lifeforms:
        - Hardy vegetation, animal life, humanoids
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Alpine.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 146650
    temperature: 270
    satellites:
      - name: Electra 6a
        description: ''
        tags: []
        satellite:
          axialTilt: 3.6
          semiMajorAxis: 654791.5271482754
          eccentricity: 0.01
          inclination: 0.69
          orbitalArc: 112
          showOrbit: true
          parentId: Electra 6
        isPlanet:
          age: 84379844
          classification: D
          radius: 1666.136201395103
          terranMass: 1.2899997534080347
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 256
  - name: Electra 7
    description: ''
    tags: []
    satellite:
      axialTilt: 36.7
      semiMajorAxis: 3897252870.1423254
      eccentricity: 0
      inclination: 1.44
      orbitalArc: 271
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 332231259
      classification: D
      radius: 422
      terranMass: 0.0006548527706368574
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings4.png
    population: 0
    temperature: 400
    satellites: []
  - name: Electra 8
    description: ''
    tags: []
    satellite:
      axialTilt: 37.56
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 1.59
      orbitalArc: 112
      showOrbit: true
      parentId: Electra
    isPlanet:
      age: 350613924
      classification: C
      radius: 890
      terranMass: 0.003881419670927126
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureChondrite.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 0
    temperature: 52
    satellites:
      - name: Electra 8a
        description: ''
        tags: []
        satellite:
          axialTilt: 31.17
          semiMajorAxis: 37392.93809827916
          eccentricity: 0.01
          inclination: 0.97
          orbitalArc: 84
          showOrbit: true
          parentId: Electra 8
        isPlanet:
          age: 342099865
          classification: D
          radius: 89.6713143843625
          terranMass: 0.5899999490234109
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 346
commSatellite: null
assets: {}
