apiVersion: solarSystem/v1
kind: solarSystems
name: Fawaris
description: A solar system named Fawaris
position:
  x: 54913914.22836781
  'y': -61505071.17729901
  z: 27072989.47576432
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Fawaris
stars:
  - name: Fawaris A
    description: ''
    tags: []
    solarMass: 2.93
    age: 624328836885
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.81
    temperature: 10400
    satellite:
      axialTilt: 0
      semiMajorAxis: 57.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 33
      showOrbit: false
      parentId: Fawaris
  - name: Fawaris B
    description: ''
    tags: []
    solarMass: 2.93
    age: 624328836885
    spectralType: B
    hue: 200
    isWhite: false
    radius: 4.81
    temperature: 10400
    satellite:
      axialTilt: 0
      semiMajorAxis: 57.72
      eccentricity: 0
      inclination: 0
      orbitalArc: 213
      showOrbit: false
      parentId: Fawaris
planets:
  - name: Fawaris 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.82
      semiMajorAxis: 833976133
      eccentricity: 0.01
      inclination: 1.29
      orbitalArc: 84
      showOrbit: true
      parentId: Fawaris
    isPlanet:
      age: 79083559
      classification: D
      radius: 181
      terranMass: 0.006150352052520129
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Icy.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 371
    satellites: []
  - name: Fawaris 2
    description: ''
    tags: []
    satellite:
      axialTilt: 39.68
      semiMajorAxis: 2156899556.6666656
      eccentricity: 0
      inclination: 1.8
      orbitalArc: 150
      showOrbit: true
      parentId: Fawaris
    isPlanet:
      age: 7454510514
      classification: K
      radius: 4163
      terranMass: 0.013509987886984225
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureCyanic.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings3.png
    population: 35300
    temperature: 270
    satellites: []
  - name: Fawaris 3
    description: ''
    tags: []
    satellite:
      axialTilt: 19.37
      semiMajorAxis: 3277993553.11111
      eccentricity: 0.01
      inclination: 0.63
      orbitalArc: 275
      showOrbit: true
      parentId: Fawaris
    isPlanet:
      age: 7775510100
      classification: L
      radius: 5101
      terranMass: 0.006289100449294951
      isHabitable: true
      lifeforms:
        - Primitive single-celled organisms
        - Hardy plant life
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesRocks.png
    population: 9888
    temperature: 271
    satellites: []
  - name: Fawaris 4
    description: ''
    tags: []
    satellite:
      axialTilt: 18.4
      semiMajorAxis: 3936022860
      eccentricity: 0.02
      inclination: 0.33
      orbitalArc: 350
      showOrbit: true
      parentId: Fawaris
    isPlanet:
      age: 333080044
      classification: D
      radius: 261
      terranMass: 0.004549072957652025
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 0
    temperature: 267
    satellites: []
commSatellite: null
assets: {}
