apiVersion: solarSystem/v1
kind: solarSystems
name: Alfirk
description: A solar system named Alfirk
position:
  x: 74085261.98346749
  'y': -342224465.8118734
  z: 95389721.82776777
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Alfirk
stars:
  - name: Alfirk A
    description: ''
    tags: []
    solarMass: 7.4
    age: 26392382526
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.22
    temperature: 23600
    satellite:
      axialTilt: 0
      semiMajorAxis: 86.64
      eccentricity: 0
      inclination: 0
      orbitalArc: 266
      showOrbit: false
      parentId: Alfirk
  - name: Alfirk B
    description: ''
    tags: []
    solarMass: 7.4
    age: 26392382526
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7.22
    temperature: 23600
    satellite:
      axialTilt: 0
      semiMajorAxis: 86.64
      eccentricity: 0
      inclination: 0
      orbitalArc: 446
      showOrbit: false
      parentId: Alfirk
planets:
  - name: Alfirk 1
    description: ''
    tags: []
    satellite:
      axialTilt: 16.46
      semiMajorAxis: 4000000000
      eccentricity: 0.01
      inclination: 0.35
      orbitalArc: 343
      showOrbit: true
      parentId: Alfirk
    isPlanet:
      age: 7183474955
      classification: J
      radius: 34701
      terranMass: 0.322777313511534
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous2.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureGiant.png
      ringMapAsset: null
    population: 0
    temperature: 328
    satellites:
      - name: Alfirk 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 6.73
          semiMajorAxis: 1688894.0778176358
          eccentricity: 0
          inclination: 0.12
          orbitalArc: 109
          showOrbit: true
          parentId: Alfirk 1
        isPlanet:
          age: 744847674
          classification: E
          radius: 4159.837630092699
          terranMass: 0.10000013820704493
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureHot.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 1328
commSatellite: null
assets: {}
