apiVersion: solarSystem/v1
kind: solarSystems
name: Phact
description: A solar system named Phact
position:
  x: -113259210.85570222
  'y': 76910659.39672166
  z: 10083699.758454643
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Phact
stars:
  - name: Phact A
    description: ''
    tags: []
    solarMass: 4.5
    age: 239081733169
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7
    temperature: 12200
    satellite:
      axialTilt: 0
      semiMajorAxis: 84
      eccentricity: 0
      inclination: 0
      orbitalArc: 92
      showOrbit: false
      parentId: Phact
  - name: Phact B
    description: ''
    tags: []
    solarMass: 4.5
    age: 239081733169
    spectralType: B
    hue: 200
    isWhite: false
    radius: 7
    temperature: 12200
    satellite:
      axialTilt: 0
      semiMajorAxis: 84
      eccentricity: 0
      inclination: 0
      orbitalArc: 272
      showOrbit: false
      parentId: Phact
planets:
  - name: Phact 1
    description: ''
    tags: []
    satellite:
      axialTilt: 8.81
      semiMajorAxis: 2410455441.333333
      eccentricity: 0.01
      inclination: 0.6
      orbitalArc: 214
      showOrbit: true
      parentId: Phact
    isPlanet:
      age: 883129896
      classification: D
      radius: 66
      terranMass: 0.005854038413401127
      isHabitable: false
      lifeforms:
        - None
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/2k_moon.jpg
      cloudMapAsset: null
      ringMapAsset: /plugins/Thorium Default/assets/rings/ring_texturesSharp.png
    population: 0
    temperature: 246
    satellites: []
  - name: Phact 2
    description: ''
    tags: []
    satellite:
      axialTilt: 25.27
      semiMajorAxis: 3809426761
      eccentricity: 0
      inclination: 1.75
      orbitalArc: 359
      showOrbit: true
      parentId: Phact
    isPlanet:
      age: 8704793418
      classification: K
      radius: 4761
      terranMass: 0.007924818456032675
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/clouds_textureSoft.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 15678
    temperature: 149
    satellites: []
commSatellite: null
assets: {}
