apiVersion: solarSystem/v1
kind: solarSystems
name: Yed Posterior
description: A solar system named Yed Posterior
position:
  x: 50185554.84654862
  'y': 4560952.378342271
  z: -23850923.278652214
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Yed Posterior
stars:
  - name: Yed Posterior A
    description: ''
    tags: []
    solarMass: 1.85
    age: 1689490756911
    spectralType: K
    hue: 30
    isWhite: false
    radius: 10.39
    temperature: 4918
    satellite:
      axialTilt: 0
      semiMajorAxis: 124.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 329
      showOrbit: false
      parentId: Yed Posterior
  - name: Yed Posterior B
    description: ''
    tags: []
    solarMass: 1.85
    age: 1689490756911
    spectralType: K
    hue: 30
    isWhite: false
    radius: 10.39
    temperature: 4918
    satellite:
      axialTilt: 0
      semiMajorAxis: 124.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 509
      showOrbit: false
      parentId: Yed Posterior
planets:
  - name: Yed Posterior 1
    description: ''
    tags: []
    satellite:
      axialTilt: 33.05
      semiMajorAxis: 833332223
      eccentricity: 0.01
      inclination: 0.16
      orbitalArc: 57
      showOrbit: true
      parentId: Yed Posterior
    isPlanet:
      age: 6472297650
      classification: K
      radius: 4193
      terranMass: 0.018882352818015435
      isHabitable: true
      lifeforms:
        - None
        - Primitive single-celled organisms
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAlkali.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds1.png
      ringMapAsset: /plugins/Thorium Default/assets/rings/rings1.png
    population: 31775
    temperature: 142
    satellites:
      - name: Yed Posterior 1a
        description: ''
        tags: []
        satellite:
          axialTilt: 30.66
          semiMajorAxis: 41724.50194607466
          eccentricity: 0.02
          inclination: 1.05
          orbitalArc: 293
          showOrbit: true
          parentId: Yed Posterior 1
        isPlanet:
          age: 788367436
          classification: C
          radius: 218.55130703737987
          terranMass: 1.6000000453963565
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureAzure.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 34
      - name: Yed Posterior 1b
        description: ''
        tags: []
        satellite:
          axialTilt: 23.72
          semiMajorAxis: 88995.49463676361
          eccentricity: 0.01
          inclination: 0.83
          orbitalArc: 217
          showOrbit: true
          parentId: Yed Posterior 1
        isPlanet:
          age: 41285531
          classification: D
          radius: 299.8825650437112
          terranMass: 1.3699997662208363
          isHabitable: false
          lifeforms:
            - None
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBurnt.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 0
        temperature: 283
      - name: Yed Posterior 1c
        description: ''
        tags: []
        satellite:
          axialTilt: 34.7
          semiMajorAxis: 163866.66498659045
          eccentricity: 0.01
          inclination: 0.75
          orbitalArc: 245
          showOrbit: true
          parentId: Yed Posterior 1
        isPlanet:
          age: 8087196358
          classification: L
          radius: 387.39164299430365
          terranMass: 1.500000144004289
          isHabitable: true
          lifeforms:
            - Primitive single-celled organisms
            - Hardy plant life
          atmosphericComposition: []
          textureMapAsset: /plugins/Thorium Default/assets/planets/Martian.jpg
          cloudMapAsset: null
          ringMapAsset: null
        population: 45603
        temperature: 246
commSatellite: null
assets: {}
