apiVersion: solarSystem/v1
kind: solarSystems
name: Barnard's Star
description: A solar system named Barnard's Star
position:
  x: 3118938.6661331607
  'y': -254697.14334684098
  z: -29721.566487301952
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Barnard's Star
stars:
  - name: Barnard's Star A
    description: ''
    tags: []
    radius: 0.187
    temperature: 3195
    solarMass: 0.162
    age: 2563997727554245
    spectralType: M
    hue: 0
    isWhite: false
    satellite:
      orbitalArc: 59
      semiMajorAxis: 60.244
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Barnard's Star
  - name: Barnard's Star B
    description: ''
    tags: []
    radius: 0.187
    temperature: 3195
    solarMass: 0.162
    age: 2563997727554245
    spectralType: M
    hue: 0
    isWhite: false
    satellite:
      orbitalArc: 239
      semiMajorAxis: 20.244
      axialTilt: 0
      eccentricity: 0
      inclination: 0
      showOrbit: false
      parentId: Barnard's Star
planets:
  - name: Barnard's Star 1
    description: ''
    tags: []
    isPlanet:
      radius: 4037715
      age: 6901987674
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
      terranMass: 6.8581690833585265
      textureMapAsset: /plugins/Thorium Default/assets/planets/planet_textureBlueGiant.jpg
      classification: I
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
    population: 0
    temperature: 150
    satellite:
      semiMajorAxis: 1715881262
      eccentricity: 0.01
      inclination: 0.65
      orbitalArc: 7
      axialTilt: 28.91
      parentId: Barnard's Star
      showOrbit: true
    satellites: []
commSatellite: null
assets: {}
