apiVersion: solarSystem/v1
kind: solarSystems
name: Zubenelhakrabi
description: A solar system named Zubenelhakrabi
position:
  x: 66959543.1477415
  'y': 21884604.729228877
  z: -48860723.69789009
tags: []
habitableZoneInner: 0.9
habitableZoneOuter: 3
skyboxKey: Zubenelhakrabi
stars:
  - name: Zubenelhakrabi A
    description: ''
    tags: []
    solarMass: 1.15
    age: 985252335081
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.14
    temperature: 4826
    satellite:
      axialTilt: 0
      semiMajorAxis: 133.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 271
      showOrbit: false
      parentId: Zubenelhakrabi
  - name: Zubenelhakrabi B
    description: ''
    tags: []
    solarMass: 1.15
    age: 985252335081
    spectralType: K
    hue: 30
    isWhite: false
    radius: 11.14
    temperature: 4826
    satellite:
      axialTilt: 0
      semiMajorAxis: 133.68
      eccentricity: 0
      inclination: 0
      orbitalArc: 451
      showOrbit: false
      parentId: Zubenelhakrabi
planets:
  - name: Zubenelhakrabi 1
    description: ''
    tags: []
    satellite:
      axialTilt: 20
      semiMajorAxis: 2352541665
      eccentricity: 0
      inclination: 1.05
      orbitalArc: 75
      showOrbit: true
      parentId: Zubenelhakrabi
    isPlanet:
      age: 3832141465
      classification: J
      radius: 66781
      terranMass: 0.2778867520270606
      isHabitable: false
      lifeforms:
        - None
        - Floating single-celled lifeforms
        - Hydrocarbon-based gas bag animals
      atmosphericComposition: []
      textureMapAsset: /plugins/Thorium Default/assets/planets/Gaseous1.jpg
      cloudMapAsset: /plugins/Thorium Default/assets/clouds/Clouds4.png
      ringMapAsset: null
    population: 0
    temperature: 330
    satellites: []
commSatellite: null
assets: {}
